Repository aiven/terraform-provider-aiven, pull requests merged in 2021-11, with the labels that each got.

#601 add github action mutex to acc tests
  .github/workflows/acceptance-tests.yml
Labels: skip-changelog

#602 add sweeper to acc tests
  .github/workflows/acceptance-tests.yml
Labels: skip-changelog

#603 add semgrep action
  .github/workflows/acceptance-tests.yml
  .github/workflows/changelog-checker.yml
  .github/workflows/lint.yml
  .github/workflows/unit-tests.yml
  .semgrep.yml
Labels: skip-changelog

#608 add semgrep rule for copyright, fix stale copyright headers
  .semgrep.yml
  LICENSE
  aiven/datasource_aws_privatelink.go
  aiven/datasource_connection_pool.go
  aiven/datasource_database.go
  aiven/datasource_elasticsearch_acl.go
  aiven/datasource_kafka_acl.go
  aiven/datasource_kafka_topic.go
  aiven/datasource_project.go
  aiven/datasource_project_user.go
  aiven/datasource_project_vpc.go
  aiven/datasource_service.go
  aiven/datasource_service_component.go
  aiven/datasource_service_integration.go
  aiven/datasource_service_integration_endpoint.go
  aiven/datasource_service_user.go
  aiven/datasource_vpc_peering_connection.go
  aiven/provider.go
  aiven/resource_aws_privatelink.go
  aiven/resource_connection_pool.go
  aiven/resource_database.go
  aiven/resource_kafka_acl.go
  aiven/resource_kafka_topic.go
  aiven/resource_mirrormaker_replication_flow.go
  aiven/resource_project_user.go
  aiven/resource_project_vpc.go
  aiven/resource_service.go
  aiven/resource_service_integration.go
  aiven/resource_service_integration_endpoint.go
  aiven/resource_service_user.go
  aiven/resource_transit_gateway_vpc_attachement.go
  aiven/resource_vpc_peering_connection.go
  aiven/schema_converter.go
  aiven/service_change.go
  aiven/user_config.go
Labels: skip-changelog

#612 add goreleaser action
  .github/workflows/acceptance-tests.yml
  .github/workflows/release-artifacts.yml
  .goreleaser.yml
Labels: skip-changelog

#616 replace reference to `tables` with `table_id` in flinks docs/examples
  docs/resources/flink_job.md
  examples/flink/main.tf
  examples/resources/aiven_flink_job/resource.tf
Labels: skip-changelog

#618 Various documentation fixes
  aiven/templates/service_user_config_schema.go
  aiven/templates/service_user_config_schema.json
  docs/resources/opensearch_acl_rule.md
  docs/resources/pg.md
  docs/resources/service.md
  examples/resources/aiven_opensearch_acl_rule/resource.tf
Labels: enhancement

#619 improve acceptance tests; some repository fixes
  .github/CODEOWNERS
  .github/workflows/acceptance-tests.yml
  .github/workflows/changelog-checker.yml
  .semgrep.yml
  Makefile
  aiven/datasource_service_integration.go
  aiven/resource_azure_privatelink_test.go
  aiven/resource_flink_test.go
  aiven/resource_kafka_connector_test.go
  aiven/resource_kafka_topic_test.go
  aiven/resource_m3aggregator_test.go
  aiven/resource_m3db_test.go
  aiven/resource_mysql_test.go
  aiven/resource_pg_test.go
  aiven/resource_redis_test.go
  aiven/resource_service.go
  aiven/resource_service_integration_test.go
  aiven/resource_service_kafka_connect_test.go
  aiven/resource_service_mysql_test.go
  aiven/resource_service_pg_test.go
  aiven/resource_service_redis_test.go
  aiven/service_change.go
Labels: needs-acceptance-tests

#622 add data source for billing group
  CHANGELOG.md
  aiven/datasource_billing_group.go
  aiven/datasource_billing_group_test.go
  aiven/provider.go
  aiven/resource_billing_group_test.go
  docs/data-sources/billing_group.md
  examples/data-sources/aiven_billing_group/data-source.tf
Labels: needs-changelog, needs-acceptance-tests

#624 acc test for migration from es to os and consequent import
  aiven/resource_opensearch_test.go
Labels: needs-acceptance-tests

#623 sync flink resources
  CHANGELOG.md
  aiven/resource_flink_job.go
  aiven/resource_flink_table.go
  aiven/resource_flink_test.go
  docs/resources/flink_job.md
  docs/resources/flink_table.md
  examples/flink/main.tf
  examples/resources/aiven_flink_job/resource.tf
  examples/resources/aiven_flink_table/resource.tf
  examples/resources/aiven_pg/resource.tf
  go.mod
  go.sum
Labels: needs-changelog, needs-acceptance-tests

#605 add support for dynamic disk size
  .github/workflows/acceptance-tests.yml
  .gitignore
  CHANGELOG.md
  aiven/datasource_service.go
  aiven/provider.go
  aiven/resource_elasticsearch.go
  aiven/resource_flink.go
  aiven/resource_grafana.go
  aiven/resource_influxdb.go
  aiven/resource_kafka.go
  aiven/resource_kafka_connect.go
  aiven/resource_kafka_mirrormaker.go
  aiven/resource_m3aggregator.go
  aiven/resource_m3db.go
  aiven/resource_mysql.go
  aiven/resource_opensearch.go
  aiven/resource_pg.go
  aiven/resource_pg_test.go
  aiven/resource_redis.go
  aiven/resource_service.go
  aiven/resource_service_integration_test.go
  aiven/resource_service_pg_test.go
  aiven/resource_service_test.go
  docs/data-sources/cassandra.md
  docs/data-sources/elasticsearch.md
  docs/data-sources/flink.md
  docs/data-sources/grafana.md
  docs/data-sources/influxdb.md
  docs/data-sources/kafka.md
  docs/data-sources/kafka_connect.md
  docs/data-sources/kafka_mirrormaker.md
  docs/data-sources/m3aggregator.md
  docs/data-sources/m3db.md
  docs/data-sources/mysql.md
  docs/data-sources/opensearch.md
  docs/data-sources/pg.md
  docs/data-sources/redis.md
  docs/data-sources/service.md
  docs/resources/cassandra.md
  docs/resources/elasticsearch.md
  docs/resources/flink.md
  docs/resources/grafana.md
  docs/resources/influxdb.md
  docs/resources/kafka.md
  docs/resources/kafka_connect.md
  docs/resources/kafka_mirrormaker.md
  docs/resources/m3aggregator.md
  docs/resources/m3db.md
  docs/resources/mysql.md
  docs/resources/opensearch.md
  docs/resources/pg.md
  docs/resources/redis.md
  docs/resources/service.md
  go.mod
  go.sum
Labels: needs-changelog, needs-acceptance-tests
