Repository aiven/terraform-provider-aiven, pull requests merged in 2022-11, with the labels that each got.

#945 fix Azure vpc peering connection import
  CHANGELOG.md
  go.mod
  go.sum
  internal/service/vpc/resource_azure_vpc_peering_connection.go
  internal/service/vpc/resource_project_vpc.go
  internal/service/vpc/resource_transit_gateway_vpc_attachement.go
  internal/service/vpc/resource_vpc_peering_connection.go
Labels: bug

#946 Added missing OpenSearch external integration endpoint schema
  CHANGELOG.md
  docs/data-sources/service_integration_endpoint.md
  docs/resources/service_integration_endpoint.md
  internal/service/service_integration/resource_service_integration_endpoint.go
Labels: enhancement

#949 add aiven_pg_user import example to docs
  CHANGELOG.md
  docs/resources/pg_user.md
  examples/resources/aiven_pg_user/import.sh
Labels: documentation

#950 terraform sdk update to the latest version
  go.mod
  go.sum
Labels: enhancement, no changelog

#948 fix project create/update
  CHANGELOG.md
  docs/data-sources/grafana.md
  docs/resources/grafana.md
  go.mod
  go.sum
  internal/service/project/resource_project.go
  internal/service/project/resource_project_test.go
Labels: enhancement

#955 fix: flatten ip_filter in case it contains objects #2
  internal/schemautil/ipfilter.go
Labels: no changelog

#953 add aiven_azure_privatelink_connection_approval test
  CHANGELOG.md
  docs/resources/azure_privatelink_connection_approval.md
  examples/resources/aiven_azure_privatelink_connection_approval/resource.tf
  go.mod
  go.sum
  internal/service/vpc/resource_azure_privatelink_connection_approve.go
  internal/service/vpc/resource_azure_privatelink_connection_approve_test.go
Labels: enhancement

#958 v3.8.1 pre release
  CHANGELOG.md
  Makefile
  internal/schemautil/ipfilter.go
  internal/service/vpc/resource_project_vpc.go
Labels: pre-release

#966 revert datasource_project_vpc project and cloud_name deprecation
  CHANGELOG.md
  docs/data-sources/project_vpc.md
  examples/data-sources/aiven_project_vpc/data-source.tf
  internal/service/vpc/datasource_project_vpc.go
  internal/service/vpc/datasource_project_vpc_test.go
Labels: enhancement

#964 increase default timeout for kafka_connect service integration create, add example test
  CHANGELOG.md
  examples/kafka_connect/project.tf
  examples/kafka_connect/provider.tf
  examples/kafka_connect/services.tf
  examples/kafka_connect/variables.tf
  examples_tests/kafka_connect_test.go
  examples_tests/postgres_test.go
  internal/service/service_integration/resource_service_integration.go
  internal/sweep/sweep.go
Labels: customer request

#973 refactor(ssg): replace panics with errors
  CHANGELOG.md
  internal/schemautil/service.go
  internal/schemautil/userconfig/apiconvert/fromapi.go
  internal/schemautil/userconfig/apiconvert/fromapi_test.go
  internal/schemautil/userconfig/apiconvert/toapi.go
  internal/schemautil/userconfig/apiconvert/toapi_test.go
  internal/schemautil/userconfig/apiconvert/util.go
  internal/schemautil/userconfig/apiconvert/util_test.go
  internal/schemautil/userconfig/convert.go
  internal/schemautil/userconfig/handle.go
  internal/schemautil/userconfig/userconfig_test.go
  internal/schemautil/userconfig/util.go
  internal/service/pg/resource_pg.go
  internal/service/service_integration/resource_service_integration.go
  internal/service/service_integration/resource_service_integration_endpoint.go
Labels: enhancement

#974 chore: upgrade operator sdk
  go.mod
  go.sum
Labels: dependencies, no changelog

#975 fix sweep make command
  internal/sweep/sweep.go
Labels: bug, no changelog
