Repository aiven/terraform-provider-aiven, pull requests merged in 2022-12, with the labels that each got.

#978 add gcp vpc self link
  CHANGELOG.md
  docs/data-sources/gcp_vpc_peering_connection.md
  docs/resources/gcp_vpc_peering_connection.md
  internal/service/vpc/resource_gcp_vpc_peering_connection.go
  internal/service/vpc/resource_gcp_vpc_peering_connection_test.go
Labels: enhancement

#980 test: fix project acc tests
  internal/service/project/resource_billing_group_test.go
  internal/service/project/resource_project.go
Labels: no changelog

#970 support `clickhouse_postgresql` integration type in `aiven_service_integration`
  CHANGELOG.md
  docs/data-sources/service_integration.md
  docs/resources/service_integration.md
  internal/service/service_integration/resource_service_integration.go
  internal/service/service_integration/resource_service_integration_test.go
Labels: enhancement

#981 add grafana ip_filter, ip_filter_object tests
  internal/service/grafana/resource_grafana_test.go
  internal/service/grafana/resource_service_grafana_test.go
Labels: no changelog

#982 skip grafana ip_filter_object test
  internal/service/grafana/resource_service_grafana_test.go
Labels: no changelog

#985 test: add aiven_aws_privatelink
  internal/service/vpc/resource_aws_privatelink_test.go
  internal/service/vpc/resource_aws_vpc_peering_connection_test.go
  internal/service/vpc/resource_transit_gateway_vpc_attachement_test.go
Labels: no changelog

#990 add offset_syncs_topic_location support
  CHANGELOG.md
  docs/data-sources/mirrormaker_replication_flow.md
  docs/resources/mirrormaker_replication_flow.md
  internal/schemautil/common.go
  internal/service/kafka/resource_mirrormaker_replication_flow.go
  internal/service/kafka/resource_mirrormaker_replication_flow_test.go
Labels: enhancement

#998 ci: move acceptance test runs to european night
  .github/workflows/acceptance-tests.yml
Labels: no changelog

#1000 fix admin credentials diff
  CHANGELOG.md
  internal/schemautil/ipfilter.go
  internal/schemautil/schemautil.go
  internal/schemautil/sensitive.go
  internal/schemautil/service.go
  internal/schemautil/userconfig/util.go
  internal/service/pg/resource_pg_test.go
Labels: bug

#1006 refactor(schemautil): unclutter mutation logic
  internal/schemautil/ipfilter.go
  internal/schemautil/mutations.go
  internal/schemautil/schemautil.go
  internal/schemautil/sensitive.go
  internal/schemautil/service.go
Labels: enhancement, no changelog

#1010 fix clickhouse acc tests
  internal/service/clickhouse/resource_clickhouse_database_test.go
  internal/service/clickhouse/resource_clickhouse_grant_test.go
  internal/service/clickhouse/resource_clickhouse_role_test.go
  internal/service/clickhouse/resource_clickhouse_test.go
  internal/service/clickhouse/resource_clickhouse_user_test.go
  internal/service/service_integration/resource_service_integration_test.go
Labels: no changelog

#1009 feat(schemautil): normalize ip_filter_object
  CHANGELOG.md
  internal/schemautil/mutations.go
  internal/schemautil/mutations_test.go
  internal/schemautil/userconfig/apiconvert/toapi.go
  internal/schemautil/userconfig/apiconvert/toapi_test.go
Labels: enhancement

#1012 add kafka connector os example test
  examples/kafka_connect/services.tf
  examples/kafka_connect/variables.tf
  examples/kafka_connectors/es_sink/connector.tf
  examples/kafka_connectors/es_sink/project.tf
  examples/kafka_connectors/es_sink/services.tf
  examples/kafka_connectors/es_sink/variables.tf
  examples/kafka_connectors/os_sink/provider.tf
  examples/kafka_connectors/os_sink/services.tf
  examples/kafka_connectors/os_sink/variables.tf
  examples_tests/base.go
  examples_tests/kafka_connect_test.go
  examples_tests/kafka_connector_test.go
Labels: no changelog

#1013 add kafka prometheus example test
  examples/kafka_prometheus/main.tf
  examples/kafka_prometheus/provider.tf
  examples/kafka_prometheus/services.tf
  examples/kafka_prometheus/variables.tf
  examples_tests/kafka_prometheus_test.go
Labels: no changelog

#1014 fix(acctest): misbehavior due to incomplete fn
  internal/schemautil/userconfig/apiconvert/toapi.go
  internal/schemautil/userconfig/apiconvert/toapi_test.go
Labels: bug, no changelog

#1016 improve team member deletion
  CHANGELOG.md
  internal/service/account/resource_account_team_member.go
  internal/service/account/resource_account_team_member_test.go
Labels: enhancement
