Repository aiven/terraform-provider-aiven, pull requests merged in 2022-09, with the labels that each got.

#880 Update official provider name
  CHANGELOG.md
  docs/guides/install-terraform-v012.md
  docs/index.md
  examples/account/README.md
  examples/kafka_mirrormaker_bidirectional/README.md
  examples/kafka_mirrormaker_global/README.md
  templates/guides/install-terraform-v012.md
  templates/index.md
Labels: documentation

#855 update Flink version to 1.15
  CHANGELOG.md
  docs/resources/flink.md
  examples/resources/aiven_flink/resource.tf
  internal/schemautil/templates/service_user_config_schema.go
  internal/schemautil/templates/service_user_config_schema.json
Labels: enhancement

#884 add is_account_owner computed field
  CHANGELOG.md
  docs/data-sources/account.md
  docs/resources/account.md
  go.mod
  go.sum
  internal/service/account/datasource_account_test.go
  internal/service/account/resource_account.go
  internal/service/account/resource_account_test.go
Labels: enhancement

#886 refactor: fix tools consistency
  CHANGELOG.md
  Makefile
  tools/go.mod
Labels: enhancement

#892 force send user_config on service integration update
  CHANGELOG.md
  docs/data-sources/service_integration.md
  docs/resources/service_integration.md
  go.mod
  go.sum
  internal/service/service_integration/resource_service_integration.go
  internal/service/service_integration/resource_service_integration_test.go
Labels: bug, customer request

#894 feat: user config options schema generation
  CHANGELOG.md
  docs/data-sources/m3db.md
  docs/data-sources/service_integration.md
  docs/resources/influxdb.md
  docs/resources/m3db.md
  docs/resources/service_integration.md
  go.mod
  go.sum
  internal/schemautil/templates/endpoint_user_config_schema.go
  internal/schemautil/templates/gen.sh
  internal/schemautil/templates/integration_endpoints_user_config_schema.json
  internal/schemautil/templates/integration_user_config_schema.go
  internal/schemautil/templates/integrations_user_config_schema.json
  internal/schemautil/templates/schema.go
  internal/schemautil/templates/service_user_config_schema.go
  internal/schemautil/templates/service_user_config_schema.json
  internal/schemautil/user_config.go
  internal/schemautil/user_config_test.go
  internal/service/service_integration/resource_service_integration.go
Labels: enhancement

#895 codeowners: add mhoffm-aiven
  .github/CODEOWNERS
Labels: enhancement, skip workflows

#896 add missing docs examples
  CHANGELOG.md
  docs/data-sources/service_component.md
  docs/data-sources/service_integration.md
  docs/resources/service_integration.md
  docs/resources/vpc_peering_connection.md
  examples/resources/aiven_service_integration/resource.tf
  templates/data-sources/service_component.md.tmpl
  templates/data-sources/service_integration.md.tmpl
  templates/resources/service_integration.md.tmpl
  templates/resources/vpc_peering_connection.md.tmpl
Labels: enhancement

#897 ci(codeowners): change team
  .github/CODEOWNERS
Labels: enhancement, skip workflows

#899 fix: static_ips schema type change from list to set
  CHANGELOG.md
  docs/data-sources/cassandra.md
  docs/data-sources/clickhouse.md
  docs/data-sources/flink.md
  docs/data-sources/grafana.md
  docs/data-sources/influxdb.md
  docs/data-sources/kafka.md
  docs/data-sources/kafka_connect.md
  docs/data-sources/kafka_mirrormaker.md
  docs/data-sources/m3aggregator.md
  docs/data-sources/m3db.md
  docs/data-sources/mysql.md
  docs/data-sources/opensearch.md
  docs/data-sources/pg.md
  docs/data-sources/redis.md
  docs/resources/cassandra.md
  docs/resources/clickhouse.md
  docs/resources/flink.md
  docs/resources/grafana.md
  docs/resources/influxdb.md
  docs/resources/kafka.md
  docs/resources/kafka_connect.md
  docs/resources/kafka_mirrormaker.md
  docs/resources/m3aggregator.md
  docs/resources/m3db.md
  docs/resources/mysql.md
  docs/resources/opensearch.md
  docs/resources/pg.md
  docs/resources/redis.md
  internal/schemautil/custom_diff.go
  internal/schemautil/service.go
  internal/schemautil/static_ips.go
  internal/schemautil/wait.go
  internal/service/static_ip/resource_static_ip.go
Labels: enhancement

#900 add postgres example test
  .github/workflows/examples-tests.yml
  CHANGELOG.md
  CONTRIBUTING.md
  Makefile
  examples/postgres/README.md
  examples/postgres/bin/apply
  examples/postgres/bin/destroy
  examples/postgres/bin/setup
  examples/postgres/provider.tf
  examples/postgres/secrets.tfvars.tmp
  examples/postgres/service.tf
  examples/postgres/variables.tf
  examples_tests/base.go
  examples_tests/postgres_example_test.go
  go.mod
  go.sum
Labels: enhancement

#898 feat: user config static schema generator, objects only
  go.mod
  go.sum
  internal/schemautil/user_config/const.go
  internal/schemautil/user_config/convert.go
  internal/schemautil/user_config/handle.go
  internal/schemautil/user_config/integration_endpoint_types.go
  internal/schemautil/user_config/integration_types.go
  internal/schemautil/user_config/service_types.go
  internal/schemautil/user_config/user_config_test.go
  internal/schemautil/user_config/util.go
  main.go
Labels: enhancement, no changelog

#908 pre-release: v3.7.0
  CHANGELOG.md
Labels: pre-release, skip workflows
