Repository aiven/terraform-provider-aiven, pull requests merged in 2022-07, with the labels that each got.

#785 update the 404 error handling behavior during import and use SDKv2 functionality
  CHANGELOG.md
  internal/schemautil/service.go
  internal/service/account/resource_account.go
  internal/service/account/resource_account_authentication.go
  internal/service/account/resource_account_team.go
  internal/service/account/resource_account_team_member.go
  internal/service/account/resource_account_team_project.go
  internal/service/cassandra/resource_cassandra.go
  internal/service/clickhouse/resource_clickhouse.go
  internal/service/flink/resource_flink.go
  internal/service/flink/resource_flink_table.go
  internal/service/grafana/resource_grafana.go
  internal/service/influxdb/resource_influxdb.go
  internal/service/kafka/resource_kafka.go
  internal/service/kafka/resource_kafka_connect.go
  internal/service/kafka/resource_kafka_connector.go
  internal/service/kafka/resource_kafka_mirrormaker.go
  internal/service/kafka/resource_kafka_schema.go
  internal/service/kafka/resource_kafka_schema_configuration.go
  internal/service/m3db/resource_m3aggregator.go
  internal/service/m3db/resource_m3db.go
  internal/service/mysql/resource_mysql.go
  internal/service/opensearch/resource_opensearch.go
  internal/service/opensearch/resource_opensearch_acl_config.go
  internal/service/opensearch/resource_opensearch_acl_rule.go
  internal/service/pg/resource_pg.go
  internal/service/project/resource_billing_group.go
  internal/service/redis/resource_redis.go
  internal/service/vpc/resource_aws_privatelink.go
  internal/service/vpc/resource_azure_privatelink.go
  internal/service/vpc/resource_azure_privatelink_connection_approve.go
Labels: bug, enhancement

#797 add support for `auto_join_team_id` in account authentication resource
  CHANGELOG.md
  docs/data-sources/account_authentication.md
  docs/resources/account_authentication.md
  internal/service/account/resource_account_authentication.go
  internal/service/account/resource_account_authentication_test.go
Labels: enhancement

#787 test modification of `static_ips` in Terraform configs
  CHANGELOG.md
  internal/acctest/acctest.go
  internal/schemautil/custom_diff.go
  internal/schemautil/static_ips.go
  internal/schemautil/wait.go
  internal/service/pg/resource_pg_test.go
  internal/service/static_ip/resource_static_ip.go
Labels: enhancement

#801 fix simple_project example
  CHANGELOG.md
  sample_project/sample.tf
Labels: enhancement

#802 add support for Kafka Schema Registry ACLs
  CHANGELOG.md
  docs/data-sources/kafka_schema_registry_acl.md
  docs/resources/kafka_schema_registry_acl.md
  go.mod
  go.sum
  internal/provider/provider.go
  internal/service/kafka/datasource_kafka_schema_registry_acl.go
  internal/service/kafka/resource_kafka_schema_registry_acl.go
  internal/service/kafka/resource_kafka_schema_registry_acl_test.go
Labels: enhancement

#800 fix billing group data-source
  .github/workflows/acceptance-tests.yml
  .github/workflows/lint.yml
  .github/workflows/release-artifacts.yml
  .github/workflows/sweep.yml
  .github/workflows/unit-tests.yml
  CHANGELOG.md
  CONTRIBUTING.md
  docs/data-sources/billing_group.md
  go.mod
  go.sum
  internal/service/project/datasource_billing_group.go
  internal/service/project/datasource_billing_group_test.go
  internal/service/project/resource_billing_group_test.go
  tools/go.mod
  tools/go.sum
Labels: bug

#805 small static IP import fix
  CHANGELOG.md
  internal/service/static_ip/resource_static_ip.go
  internal/service/static_ip/resource_static_ip_test.go
Labels: enhancement

#813 add acceptance test for validating 404 error handling during import
  CHANGELOG.md
  internal/service/static_ip/resource_static_ip_test.go
Labels: enhancement

#818 drop deprecated resources from sample project
  .gitignore
  CHANGELOG.md
  sample_project/sample.tf
Labels: enhancement

#817 update account authentication SAML fields
  CHANGELOG.md
  docs/data-sources/account_authentication.md
  docs/resources/account_authentication.md
  go.mod
  go.sum
  internal/service/account/resource_account_authentication.go
Labels: enhancement

#816 add Flink SQL validation
  CHANGELOG.md
  internal/schemautil/custom_diff.go
  internal/service/flink/resource_flink_job.go
  internal/service/flink/resource_flink_table.go
  internal/service/flink/resource_flink_test.go
Labels: enhancement

#819 add outputs example to the sample project
  CHANGELOG.md
  sample_project/outputs.tf
Labels: enhancement

#820 v3.4.0 pre release
  CHANGELOG.md
  internal/acctest/acctest.go
  internal/schemautil/schemautil.go
Labels: pre-release

#822 service project vpc id error handling
  .github/workflows/acceptance-tests.yml
  CHANGELOG.md
  internal/schemautil/helpers.go
  internal/schemautil/service.go
  internal/service/service_integration/datasource_service_integration.go
  internal/service/static_ip/resource_static_ip.go
  internal/service/vpc/resource_project_vpc_test.go
Labels: bug

#824 fix version ldflag
  .goreleaser.yml
  CHANGELOG.md
  internal/provider/provider.go
Labels: bug

#825 improve Makefile
  .github/workflows/acceptance-tests.yml
  .github/workflows/unit-tests.yml
  CHANGELOG.md
  Makefile
Labels: enhancement, documentation

#826 add sweeper for account authentication
  CHANGELOG.md
  internal/service/account/sweep.go
Labels: enhancement

#828 fix Markdown formatting in CHANGELOG.md
  CHANGELOG.md
Labels: documentation

#827 make use of BUILD_DEV_DIR in Makefile
  CHANGELOG.md
  Makefile
Labels: bug

#829 use Changelog Enforcer GitHub Action
  .github/workflows/acceptance-tests.yml
  .github/workflows/changelog-checker.yml
  .github/workflows/changelog-enforcer.yml
  .github/workflows/lint.yml
  .github/workflows/release-artifacts.yml
  .github/workflows/sweep.yml
  .github/workflows/unit-tests.yml
  CHANGELOG.md
Labels: enhancement

#836 fix Changelog Enforcer GitHub Actions workflow
  .github/workflows/changelog-enforcer.yml
  CHANGELOG.md
Labels: bug

#835 add dependabot.yml
  .github/dependabot.yml
  CHANGELOG.md
  go.mod
  go.sum
Labels: enhancement

#833 make Makefile variables env changeable
  CHANGELOG.md
  Makefile
Labels: enhancement

#839 prevent changelog enforcement for PRs from dependabot[bot]
  .github/workflows/changelog-enforcer.yml
  CHANGELOG.md
Labels: enhancement

#840 add no changelog label check in changelog-enforcer.yml
  .github/workflows/changelog-enforcer.yml
  CHANGELOG.md
Labels: enhancement
