Repository aiven/terraform-provider-aiven, pull requests merged in 2022-10, with the labels that each got.

#907 feat: add support for properties like ip_filter
  internal/schemautil/schemautil.go
  internal/schemautil/user_config/convert.go
  internal/schemautil/user_config/handle.go
  internal/schemautil/user_config/service_types.go
  internal/schemautil/user_config/util.go
Labels: enhancement, no changelog

#918 rename examples-tests job
  .github/workflows/examples-tests.yml
Labels: enhancement, no changelog

#915 fix: update links to user configuration options in the docs
  docs/guides/syslog-service-integration.md
  docs/index.md
  templates/guides/syslog-service-integration.md
  templates/index.md
Labels: bug, documentation, no changelog

#912 fix: change aiven_project_vpc datasource
  CHANGELOG.md
  docs/data-sources/project_vpc.md
  internal/service/vpc/datasource_project_vpc.go
  internal/service/vpc/resource_project_vpc_test.go
Labels: bug

#922 fix: update auth fields for sweep
  internal/service/account/sweep.go
Labels: no changelog

#924 Fixes rendering of import examples
  docs/resources/service_integration.md
  docs/resources/vpc_peering_connection.md
  templates/resources/service_integration.md.tmpl
  templates/resources/vpc_peering_connection.md.tmpl
Labels: documentation, no changelog

#902 Add deprecation notice to documentation of the `aiven_service_user` r…
  docs/resources/service_user.md
  templates/resources/service_user.md.tmpl
Labels: no changelog

#925 update to the latest terraform sdk
  go.mod
  go.sum
Labels: no changelog

#932 feat: add a converter for the service user configuration options ip_f…
  CHANGELOG.md
  internal/schemautil/ipfilter.go
Labels: enhancement

#928 fix service component optional parameters filters
  CHANGELOG.md
  internal/service/service_component/datasource_service_component.go
  internal/service/service_component/datasource_service_component_test.go
Labels: enhancement

#934 pre-release: v3.8.0
  CHANGELOG.md
  internal/schemautil/user_config.go
Labels: pre-release

#935 docs: update available clickhouse integrations
  CHANGELOG.md
  docs/resources/clickhouse.md
  internal/service/clickhouse/resource_clickhouse.go
Labels: enhancement

#941 fix vpc peering connection `terraform import`
  CHANGELOG.md
  internal/service/vpc/resource_aws_vpc_peering_connection.go
  internal/service/vpc/resource_azure_vpc_peering_connection.go
  internal/service/vpc/resource_gcp_vpc_peering_connection.go
  internal/service/vpc/resource_transit_gateway_vpc_attachement.go
  internal/service/vpc/resource_vpc_peering_connection.go
Labels: bug

#944 fix(common): GetServiceUserValidateFunc
  CHANGELOG.md
  internal/schemautil/common.go
Labels: bug
