Repository aiven/terraform-provider-aiven, pull requests merged in 2022-08, with the labels that each got.

#842 update Changelog Enforcer workflow
  .github/workflows/changelog-enforcer.yml
  CHANGELOG.md
Labels: enhancement

#845 add CodeQL workflow
  .github/workflows/codeql.yml
  CHANGELOG.md
Labels: enhancement

#847 add opensearch_index support to aiven_flink_table
  CHANGELOG.md
  docs/resources/flink_table.md
  go.mod
  go.sum
  internal/service/flink/resource_flink_table.go
  internal/service/flink/resource_flink_test.go
Labels: enhancement

#850 run JetBrains code cleanup
  internal/acctest/provider_test.go
  internal/service/clickhouse/role.go
  internal/service/kafka/cache/kafka_acl_cache.go
  internal/service/kafka/cache/kafka_topic_cache.go
  main.go
Labels: enhancement, no changelog

#851 fix workflow formatting
  .github/workflows/codeql.yml
  .github/workflows/lint.yml
  .github/workflows/release-artifacts.yml
  .github/workflows/unit-tests.yml
Labels: enhancement, no changelog

#852 fix code warnings and errors
  examples/account/README.md
  examples/postgres/bin/apply
  examples/postgres/bin/destroy
  internal/provider/provider.go
  internal/schemautil/common.go
  internal/schemautil/schemautil.go
  internal/schemautil/service.go
  internal/schemautil/templates/gen.sh
  internal/schemautil/templates/schema.go
  internal/schemautil/user_config.go
  internal/service/database/datasource_database.go
  internal/service/database/resource_database.go
  internal/service/kafka/kafka_acl_cache.go
  internal/service/kafka/kafka_topic_availability.go
  internal/service/kafka/kafka_topic_cache.go
  internal/service/kafka/kafka_topic_cache_test.go
  internal/service/kafka/kafka_topic_create.go
  internal/service/kafka/resource_kafka_acl.go
  internal/service/kafka/resource_kafka_topic.go
  internal/service/mysql/resource_mysql_database_test.go
  internal/service/pg/resource_pg_database_test.go
  internal/service/service_integration/resource_service_integration.go
  internal/service/service_integration/resource_service_integration_endpoint.go
  internal/service/service_user/datasource_service_user.go
  internal/service/service_user/resource_service_user.go
  internal/service/vpc/datasource_vpc_peering_connection.go
  internal/service/vpc/resource_azure_privatelink_connection_approve.go
  internal/service/vpc/resource_transit_gateway_vpc_attachement.go
  internal/service/vpc/resource_vpc_peering_connection.go
Labels: enhancement, no changelog

#848 kafka topic waiter add not found checks
  CHANGELOG.md
  go.mod
  go.sum
  internal/service/kafka/kafka_topic_availability.go
Labels: enhancement

#856 small .golangci.yml fix
  .golangci.yml
  internal/schemautil/common.go
Labels: enhancement, no changelog

#849 add PostgreSQL max connections and PgBouncer outputs
  CHANGELOG.md
  Makefile
  docs/data-sources/pg.md
  docs/resources/pg.md
  internal/schemautil/service.go
  internal/service/pg/resource_pg.go
  internal/service/pg/resource_service_pg_test.go
  sample_project/outputs.tf
Labels: enhancement

#859 add revive linter
  .golangci.yml
  CHANGELOG.md
Labels: enhancement

#860 update CODEOWNERS
  .github/CODEOWNERS
Labels: enhancement, no changelog

#861 fix release artifacts workflow
  .github/workflows/release-artifacts.yml
Labels: bug, no changelog

#862 add skip workflows label support
  .github/workflows/changelog-enforcer.yml
  .github/workflows/codeql.yml
  .github/workflows/dependency-review.yml
  .github/workflows/lint.yml
  .github/workflows/unit-tests.yml
Labels: enhancement, no changelog

#865 fix title case in unit-tests.yml
  .github/workflows/unit-tests.yml
Labels: enhancement, no changelog

#869 v3.5.1 pre-release
  CHANGELOG.md
Labels: pre-release

#878 pre-release v3.6.0
  CHANGELOG.md
Labels: pre-release
