Repository aiven/terraform-provider-aiven, pull requests merged in 2023-03, with the labels that each got.

#1077 fix: add commit message prefix to dependabot
  .github/dependabot.yml
Labels: no changelog

#1075 fix(project): add_account_owners_admin_access
  CHANGELOG.md
  internal/schemautil/schemautil.go
  internal/service/project/project.go
Labels: bug

#1079 feat(serviceintegration): add integration_type enum validation, add d…
  CHANGELOG.md
  docs/data-sources/service_integration.md
  docs/resources/service_integration.md
  internal/schemautil/common.go
  internal/service/serviceintegration/service_integration.go
Labels: enhancement, documentation

#1082 revert: fix: add commit message prefix to dependabot (#1077)
  .github/dependabot.yml
Labels: no changelog

#1078 feat: rename flink application version field from plural singular
  CHANGELOG.md
  docs/data-sources/flink_application_version.md
  docs/resources/flink_application_version.md
  internal/service/flink/flink_application_version.go
  internal/service/flink/flink_application_version_test.go
Labels: enhancement

#1089 fix(kafkatopic): conflict on create existing topic
  CHANGELOG.md
  internal/sdkprovider/service/kafka/kafka_topic_create.go
  internal/sdkprovider/service/kafka/kafka_topic_test.go
Labels: bug

#1087 fix(docs): update flink example version
  docs/resources/flink.md
  examples/resources/aiven_flink/resource.tf
Labels: documentation, no changelog

#1091 ci(acctest): fix project structure
  Makefile
Labels: bug, no changelog

#1092 refactor(sdkprovider): fix imports
  internal/sdkprovider/provider/provider.go
Labels: bug, no changelog

#1093 fix(sweep): import path in dependant modules
  internal/sdkprovider/service/account/sweep.go
  internal/sdkprovider/service/cassandra/sweep.go
  internal/sdkprovider/service/clickhouse/sweep.go
  internal/sdkprovider/service/flink/sweep.go
  internal/sdkprovider/service/grafana/sweep.go
  internal/sdkprovider/service/influxdb/sweep.go
  internal/sdkprovider/service/kafka/sweep.go
  internal/sdkprovider/service/m3db/sweep.go
  internal/sdkprovider/service/mysql/sweep.go
  internal/sdkprovider/service/opensearch/sweep.go
  internal/sdkprovider/service/pg/sweep.go
  internal/sdkprovider/service/project/sweep.go
  internal/sdkprovider/service/redis/sweep.go
  internal/sdkprovider/service/serviceintegration/sweep.go
  internal/sdkprovider/service/staticip/sweep.go
  internal/sweep/sweep.go
Labels: no changelog

#1094 chore(release): v4.1.1
  CHANGELOG.md
Labels: release

#1095 chore(release): v3.13.1
  CHANGELOG.md
  internal/service/kafka/kafka_topic_create.go
  internal/service/kafka/kafka_topic_test.go
Labels: release

#1098 refactor(schemautil): global default timeout minutes
  internal/schemautil/service.go
Labels: go, no changelog

#1096 fix(apiconvert): ToAPI for objects and arrays
  CHANGELOG.md
  internal/schemautil/userconfig/apiconvert/toapi.go
  internal/schemautil/userconfig/apiconvert/toapi_test.go
Labels: bug

#1090 feat(provider): new framework boilerplate
  .goreleaser.yml
  go.mod
  go.sum
  internal/acctest/acctest.go
  internal/acctest/provider_test.go
  internal/provider/provider.go
  internal/provider/provider_test.go
  internal/schemautil/service.go
  internal/sdkprovider/provider/provider.go
  main.go
Labels: enhancement, no changelog

#1102 chore(release): v4.1.2
  CHANGELOG.md
Labels: release

#1103 chore(changelog): return missing header
  CHANGELOG.md
Labels: enhancement, no changelog

#1108 chore(release): v4.1.3
  CHANGELOG.md
  main.go
Labels: release

#1110 feat(m3db): add configuration options
  CHANGELOG.md
  docs/data-sources/m3db.md
  docs/resources/m3db.md
  docs/resources/mysql.md
  docs/resources/opensearch.md
  docs/resources/pg.md
  docs/resources/redis.md
  go.mod
  go.sum
  internal/schemautil/userconfig/dist/service_types.go
  main.go
Labels: enhancement

#1111 feat(kafka_connector): make config non-sensitive
  CHANGELOG.md
  docs/data-sources/kafka_connector.md
  docs/resources/kafka_connector.md
  internal/sdkprovider/service/kafka/kafka_connector.go
Labels: enhancement

#1112 feat(userconfig): add ip_filter, namespaces string alias fields
  CHANGELOG.md
  docs/data-sources/cassandra.md
  docs/data-sources/clickhouse.md
  docs/data-sources/flink.md
  docs/data-sources/grafana.md
  docs/data-sources/influxdb.md
  docs/data-sources/kafka.md
  docs/data-sources/kafka_connect.md
  docs/data-sources/kafka_mirrormaker.md
  docs/data-sources/m3aggregator.md
  docs/data-sources/m3db.md
  docs/data-sources/mysql.md
  docs/data-sources/opensearch.md
  docs/data-sources/pg.md
  docs/data-sources/redis.md
  docs/resources/cassandra.md
  docs/resources/clickhouse.md
  docs/resources/flink.md
  docs/resources/grafana.md
  docs/resources/influxdb.md
  docs/resources/kafka.md
  docs/resources/kafka_connect.md
  docs/resources/kafka_mirrormaker.md
  docs/resources/m3aggregator.md
  docs/resources/m3db.md
  docs/resources/mysql.md
  docs/resources/opensearch.md
  docs/resources/pg.md
  docs/resources/redis.md
  internal/schemautil/mutations.go
  internal/schemautil/service.go
  internal/schemautil/userconfig/dist/service_types.go
  internal/schemautil/userconfig/handle.go
Labels: enhancement
