Repository aiven/terraform-provider-aiven, pull requests merged in 2023-05, with the labels that each got.

#1141 fix(account): authentication SAML field mapping set
  CHANGELOG.md
  internal/sdkprovider/service/account/account_authentication.go
  internal/sdkprovider/service/account/account_authentication_test.go
Labels: bug

#1147 fix: adjust generated SQL for ClickHouse privilege grants
  CHANGELOG.md
  docs/resources/clickhouse_grant.md
  examples/resources/aiven_clickhouse_grant/resource.tf
  internal/sdkprovider/service/clickhouse/grant.go
Labels: bug

#1153 fix(userconfig): required for top level fields
  CHANGELOG.md
  docs/data-sources/opensearch.md
  docs/resources/mysql.md
  docs/resources/opensearch.md
  docs/resources/service_integration.md
  docs/resources/service_integration_endpoint.md
  internal/schemautil/userconfig/dist/integration_endpoint_types.go
  internal/schemautil/userconfig/dist/integration_types.go
  internal/schemautil/userconfig/dist/service_types.go
  internal/schemautil/userconfig/userconfig_test.go
Labels: bug

#1143 docs(static_ip_addresses): instructions for creating static IP addresses
  docs/guides/creating-static-ip-addresses.md
  templates/guides/creating-static-ip-addresses.md
Labels: documentation, no changelog

#1152 fix(docs): remove optional mark from kafka's computed fields
  docs/resources/kafka.md
  internal/sdkprovider/service/kafka/kafka.go
Labels: no changelog

#1151 chore: deprecate disk_space option
  CHANGELOG.md
  docs/resources/cassandra.md
  docs/resources/clickhouse.md
  docs/resources/flink.md
  docs/resources/grafana.md
  docs/resources/influxdb.md
  docs/resources/kafka.md
  docs/resources/kafka_connect.md
  docs/resources/kafka_mirrormaker.md
  docs/resources/m3aggregator.md
  docs/resources/m3db.md
  docs/resources/mysql.md
  docs/resources/opensearch.md
  docs/resources/pg.md
  docs/resources/redis.md
  internal/schemautil/service.go
Labels: enhancement

#1159 ci(commitlint): ignore dependabot's commit messages
  commitlint.config.js
Labels: enhancement, no changelog

#1161 ci: add userconfig-generate-schema.yml workflow
  .github/workflows/userconfig-generate-schema.yml
Labels: enhancement, no changelog

#1158 docs: add missing import statements
  docs/resources/cassandra_user.md
  docs/resources/clickhouse_user.md
  docs/resources/influxdb_user.md
  docs/resources/kafka_user.md
  docs/resources/m3db_user.md
  docs/resources/mysql_user.md
  docs/resources/opensearch_user.md
  docs/resources/redis_user.md
  examples/data-sources/aiven_elasticsearch/data-source.tf
  examples/data-sources/aiven_elasticsearch_acl/data-source.tf
  examples/data-sources/aiven_elasticsearch_acl_config/data-source.tf
  examples/data-sources/aiven_elasticsearch_acl_rule/data-source.tf
  examples/resources/aiven_cassandra_user/import.sh
  examples/resources/aiven_clickhouse_user/import.sh
  examples/resources/aiven_influxdb_user/import.sh
  examples/resources/aiven_kafka_user/import.sh
  examples/resources/aiven_m3db_user/import.sh
  examples/resources/aiven_mysql_user/import.sh
  examples/resources/aiven_opensearch_user/import.sh
  examples/resources/aiven_redis_user/import.sh
Labels: documentation, no changelog

#1162 chore(release): v4.3.0
  CHANGELOG.md
Labels: release

#1166 ci(userconfig-generate-schema): run make docs
  .github/workflows/userconfig-generate-schema.yml
Labels: enhancement, no changelog

#1176 chore(release): v4.4.0
  CHANGELOG.md
Labels: release

#1181 refactor: use default validation.StringInSlice
  internal/schemautil/common.go
  internal/schemautil/service.go
  internal/sdkprovider/service/kafka/mirrormaker_replication_flow.go
  internal/sdkprovider/service/kafka/mirrormaker_replication_flow_test.go
  internal/sdkprovider/service/serviceintegration/service_integration.go
  internal/sdkprovider/service/serviceintegration/service_integration_endpoint.go
Labels: no changelog

#1179 fix(kafka_topic): 404 error handling
  CHANGELOG.md
  internal/sdkprovider/service/kafka/kafka_topic.go
  internal/sdkprovider/service/kafka/kafka_topic_cache.go
  internal/sdkprovider/service/kafka/kafka_topic_cache_test.go
  internal/sdkprovider/service/kafka/kafka_topic_wait.go
Labels: bug

#1180 fix(kafka_schema): suppress diff schema_type on resource import
  CHANGELOG.md
  internal/sdkprovider/service/kafka/kafka_schema.go
Labels: bug
