Repository aiven/terraform-provider-aiven, pull requests merged in 2023-11, with the labels that each got.

#1425 fix(schemautil): unmarshalling empty userconfig crash
  CHANGELOG.md
  Makefile
  internal/schemautil/schemautil.go
  main.go
Labels: bug

#1428 chore: merge v4 into main (06-11-2023)
  CHANGELOG.md
  Makefile
  internal/schemautil/schemautil.go
  internal/schemautil/userconfig/apiconvert/fromapi.go
  internal/schemautil/userconfig/apiconvert/fromapi_test.go
  internal/schemautil/userconfig/apiconvert/toapi.go
  internal/schemautil/userconfig/apiconvert/toapi_test.go
  internal/schemautil/userconfig/apiconvert/util.go
  internal/schemautil/userconfig/apiconvert/util_test.go
  internal/schemautil/userconfig/convert.go
  internal/schemautil/userconfig/desc.go
  internal/schemautil/userconfig/handle.go
  internal/schemautil/userconfig/stateupgrader/typeupgrader/typeupgrader.go
  internal/schemautil/userconfig/stateupgrader/typeupgrader/typeupgrader_test.go
  internal/schemautil/userconfig/stateupgrader/v0/cassandra/cassandra.go
  internal/schemautil/userconfig/stateupgrader/v0/flink/flink.go
  internal/schemautil/userconfig/stateupgrader/v0/grafana/grafana.go
  internal/schemautil/userconfig/stateupgrader/v0/influxdb/influxdb.go
  internal/schemautil/userconfig/stateupgrader/v0/kafka/kafka.go
  internal/schemautil/userconfig/stateupgrader/v0/kafka/kafka_connect.go
  internal/schemautil/userconfig/stateupgrader/v0/kafka/kafka_mirrormaker.go
  internal/schemautil/userconfig/stateupgrader/v0/kafka/kafka_topic.go
  internal/schemautil/userconfig/stateupgrader/v0/m3/m3aggregator.go
  internal/schemautil/userconfig/stateupgrader/v0/m3/m3db.go
  internal/schemautil/userconfig/stateupgrader/v0/mysql/mysql.go
  internal/schemautil/userconfig/stateupgrader/v0/opensearch/opensearch.go
  internal/schemautil/userconfig/stateupgrader/v0/pg/pg.go
  internal/schemautil/userconfig/stateupgrader/v0/redis/redis.go
  internal/schemautil/userconfig/stateupgrader/v0/serviceintegration/service_integration.go
  internal/schemautil/userconfig/stateupgrader/v0/serviceintegration/service_integration_endpoint.go
  internal/schemautil/userconfig/userconfig_test.go
  internal/schemautil/userconfig/util.go
  internal/sdkprovider/service/kafkatopic/kafka_topic.go
  internal/sdkprovider/service/kafkatopic/kafka_topic_cache.go
  internal/sdkprovider/service/kafkatopic/kafka_topic_exists.go
  internal/sdkprovider/service/kafkatopic/kafka_topic_test.go
  internal/sdkprovider/service/kafkatopic/kafka_topic_wait.go
  internal/sdkprovider/service/organization/organization_user.go
  main.go
Labels: enhancement, no changelog, skip workflows

#1429 Revert "chore: merge v4 into main (06-11-2023) (#1428)"
  CHANGELOG.md
  Makefile
  internal/schemautil/schemautil.go
  internal/schemautil/userconfig/apiconvert/fromapi.go
  internal/schemautil/userconfig/apiconvert/fromapi_test.go
  internal/schemautil/userconfig/apiconvert/toapi.go
  internal/schemautil/userconfig/apiconvert/toapi_test.go
  internal/schemautil/userconfig/apiconvert/util.go
  internal/schemautil/userconfig/apiconvert/util_test.go
  internal/schemautil/userconfig/convert.go
  internal/schemautil/userconfig/desc.go
  internal/schemautil/userconfig/handle.go
  internal/schemautil/userconfig/stateupgrader/typeupgrader/typeupgrader.go
  internal/schemautil/userconfig/stateupgrader/typeupgrader/typeupgrader_test.go
  internal/schemautil/userconfig/stateupgrader/v0/cassandra/cassandra.go
  internal/schemautil/userconfig/stateupgrader/v0/flink/flink.go
  internal/schemautil/userconfig/stateupgrader/v0/grafana/grafana.go
  internal/schemautil/userconfig/stateupgrader/v0/influxdb/influxdb.go
  internal/schemautil/userconfig/stateupgrader/v0/kafka/kafka.go
  internal/schemautil/userconfig/stateupgrader/v0/kafka/kafka_connect.go
  internal/schemautil/userconfig/stateupgrader/v0/kafka/kafka_mirrormaker.go
  internal/schemautil/userconfig/stateupgrader/v0/kafka/kafka_topic.go
  internal/schemautil/userconfig/stateupgrader/v0/m3/m3aggregator.go
  internal/schemautil/userconfig/stateupgrader/v0/m3/m3db.go
  internal/schemautil/userconfig/stateupgrader/v0/mysql/mysql.go
  internal/schemautil/userconfig/stateupgrader/v0/opensearch/opensearch.go
  internal/schemautil/userconfig/stateupgrader/v0/pg/pg.go
  internal/schemautil/userconfig/stateupgrader/v0/redis/redis.go
  internal/schemautil/userconfig/stateupgrader/v0/serviceintegration/service_integration.go
  internal/schemautil/userconfig/stateupgrader/v0/serviceintegration/service_integration_endpoint.go
  internal/schemautil/userconfig/userconfig_test.go
  internal/schemautil/userconfig/util.go
  internal/sdkprovider/service/kafkatopic/kafka_topic.go
  internal/sdkprovider/service/kafkatopic/kafka_topic_cache.go
  internal/sdkprovider/service/kafkatopic/kafka_topic_exists.go
  internal/sdkprovider/service/kafkatopic/kafka_topic_test.go
  internal/sdkprovider/service/kafkatopic/kafka_topic_wait.go
  internal/sdkprovider/service/organization/organization_user.go
  main.go
Labels: skip workflows

#1433 docs: document other env vars for make test-acc
  CONTRIBUTING.md
Labels: documentation, no changelog

#1436 ci(acctest): disable v4 workflow
  .github/workflows/acceptance-tests-v4.yml
Labels: enhancement, no changelog, github_actions

#1437 test(examples): fix semgrep failing on math/rand import
  examples_tests/base.go
Labels: enhancement, no changelog

#1439 revert(plugin): restore service integration SDKv2 files
  CHANGELOG.md
  docs/data-sources/service_integration.md
  docs/resources/service_integration.md
  internal/plugin/provider.go
  internal/plugin/service/serviceintegration/models.go
  internal/plugin/service/serviceintegration/service_integration_data_source.go
  internal/plugin/service/serviceintegration/service_integration_resource.go
  internal/plugin/service/serviceintegration/userconfig.go
  internal/plugin/service/userconfig/integration/clickhousekafka/clickhouse_kafka.go
  internal/plugin/service/userconfig/integration/clickhousekafka/clickhouse_kafka_test.go
  internal/plugin/service/userconfig/integration/clickhousepostgresql/clickhouse_postgresql.go
  internal/plugin/service/userconfig/integration/clickhousepostgresql/clickhouse_postgresql_test.go
  internal/plugin/service/userconfig/integration/datadog/datadog.go
  internal/plugin/service/userconfig/integration/datadog/datadog_test.go
  internal/plugin/service/userconfig/integration/externalawscloudwatchmetrics/external_aws_cloudwatch_metrics.go
  internal/plugin/service/userconfig/integration/externalawscloudwatchmetrics/external_aws_cloudwatch_metrics_test.go
  internal/plugin/service/userconfig/integration/kafkaconnect/kafka_connect.go
  internal/plugin/service/userconfig/integration/kafkaconnect/kafka_connect_test.go
  internal/plugin/service/userconfig/integration/kafkalogs/kafka_logs.go
  internal/plugin/service/userconfig/integration/kafkalogs/kafka_logs_test.go
  internal/plugin/service/userconfig/integration/kafkamirrormaker/kafka_mirrormaker.go
  internal/plugin/service/userconfig/integration/kafkamirrormaker/kafka_mirrormaker_test.go
  internal/plugin/service/userconfig/integration/logs/logs.go
  internal/plugin/service/userconfig/integration/logs/logs_test.go
  internal/plugin/service/userconfig/integration/metrics/metrics.go
  internal/plugin/service/userconfig/integration/metrics/metrics_test.go
  internal/sdkprovider/provider/provider.go
  internal/sdkprovider/service/serviceintegration/service_integration.go
  internal/sdkprovider/service/serviceintegration/service_integration_data_source.go
  internal/sdkprovider/service/serviceintegration/service_integration_test.go
  main.go
  ucgenerator/main.go
  ucgenerator/models.go
  ucgenerator/tests.go
Labels: go

#1434 chore(changelog): improve header
  CHANGELOG.md
Labels: documentation, no changelog

#1442 fix(apiconvert): never skip basic auth username/password
  CHANGELOG.md
  internal/schemautil/userconfig/apiconvert/toapi.go
  internal/sdkprovider/service/serviceintegration/service_integration_endpoint_test.go
Labels: bug

#1349 refactor(kafka_topic): add KafkaTopic repository
  go.mod
  go.sum
  internal/sdkprovider/kafkatopicrepository/create.go
  internal/sdkprovider/kafkatopicrepository/create_test.go
  internal/sdkprovider/kafkatopicrepository/delete.go
  internal/sdkprovider/kafkatopicrepository/delete_test.go
  internal/sdkprovider/kafkatopicrepository/read.go
  internal/sdkprovider/kafkatopicrepository/repository.go
  internal/sdkprovider/kafkatopicrepository/repository_test.go
  internal/sdkprovider/kafkatopicrepository/update.go
  internal/sdkprovider/service/kafkatopic/kafka_topic.go
  internal/sdkprovider/service/kafkatopic/kafka_topic_cache.go
  internal/sdkprovider/service/kafkatopic/kafka_topic_cache_test.go
  internal/sdkprovider/service/kafkatopic/kafka_topic_exists.go
  internal/sdkprovider/service/kafkatopic/kafka_topic_test.go
  internal/sdkprovider/service/kafkatopic/kafka_topic_wait.go
Labels: enhancement, no changelog

#1447 feat(mirrormaker): add emit_backward_heartbeats_enabled field support
  CHANGELOG.md
  docs/data-sources/mirrormaker_replication_flow.md
  docs/resources/mirrormaker_replication_flow.md
  go.mod
  go.sum
  internal/sdkprovider/service/kafka/mirrormaker_replication_flow.go
  internal/sdkprovider/service/kafka/mirrormaker_replication_flow_test.go
Labels: enhancement

#1448 build(deps): bump aiven-go-client to v2.4.0
  go.mod
  go.sum
Labels: dependencies, no changelog

#1451 feat: make sure emails are lowercase and valid
  CHANGELOG.md
  docs/data-sources/account_team_member.md
  docs/data-sources/organization_user.md
  docs/data-sources/project_user.md
  docs/resources/account_team_member.md
  docs/resources/organization_user.md
  docs/resources/project_user.md
  internal/schemautil/schemautil.go
  internal/sdkprovider/service/account/account_team_member.go
  internal/sdkprovider/service/organization/organization_user.go
  internal/sdkprovider/service/project/project_user.go
Labels: enhancement

#1452 chore: backports d0ae4f6 to v3
  .github/workflows/lint.yml
  CHANGELOG.md
  docs/data-sources/account_team_member.md
  docs/data-sources/project_user.md
  docs/resources/account_team_member.md
  docs/resources/project_user.md
  go.mod
  go.sum
  internal/schemautil/schemautil.go
  internal/service/account/account_team_member.go
  internal/service/project/project_user.go
Labels: enhancement

#1453 chore(backport): deprecate unclean_leader_election_enable in aiven_kafka_topic
  CHANGELOG.md
  docs/resources/kafka_topic.md
  internal/service/kafka/kafka_topic.go
Labels: enhancement

#1457 feat(service): add connection_info field to components
  CHANGELOG.md
  docs/data-sources/cassandra.md
  docs/data-sources/clickhouse.md
  docs/data-sources/flink.md
  docs/data-sources/grafana.md
  docs/data-sources/influxdb.md
  docs/data-sources/kafka.md
  docs/data-sources/kafka_connect.md
  docs/data-sources/kafka_mirrormaker.md
  docs/data-sources/m3aggregator.md
  docs/data-sources/m3db.md
  docs/data-sources/mysql.md
  docs/data-sources/opensearch.md
  docs/data-sources/pg.md
  docs/data-sources/redis.md
  docs/resources/cassandra.md
  docs/resources/clickhouse.md
  docs/resources/flink.md
  docs/resources/grafana.md
  docs/resources/influxdb.md
  docs/resources/kafka.md
  docs/resources/kafka_connect.md
  docs/resources/kafka_mirrormaker.md
  docs/resources/m3aggregator.md
  docs/resources/m3db.md
  docs/resources/mysql.md
  docs/resources/opensearch.md
  docs/resources/pg.md
  docs/resources/redis.md
  internal/schemautil/service.go
Labels: enhancement

#1456 feat: add external_postgresql and external_google_cloud_bigquery
  CHANGELOG.md
  docs/data-sources/service_integration_endpoint.md
  docs/resources/service_integration_endpoint.md
  internal/sdkprovider/service/serviceintegration/service_integration_endpoint.go
Labels: enhancement

#1459 chore(service): rename connection_info field to connection_uri
  CHANGELOG.md
  docs/data-sources/cassandra.md
  docs/data-sources/clickhouse.md
  docs/data-sources/flink.md
  docs/data-sources/grafana.md
  docs/data-sources/influxdb.md
  docs/data-sources/kafka.md
  docs/data-sources/kafka_connect.md
  docs/data-sources/kafka_mirrormaker.md
  docs/data-sources/m3aggregator.md
  docs/data-sources/m3db.md
  docs/data-sources/mysql.md
  docs/data-sources/opensearch.md
  docs/data-sources/pg.md
  docs/data-sources/redis.md
  docs/resources/cassandra.md
  docs/resources/clickhouse.md
  docs/resources/flink.md
  docs/resources/grafana.md
  docs/resources/influxdb.md
  docs/resources/kafka.md
  docs/resources/kafka_connect.md
  docs/resources/kafka_mirrormaker.md
  docs/resources/m3aggregator.md
  docs/resources/m3db.md
  docs/resources/mysql.md
  docs/resources/opensearch.md
  docs/resources/pg.md
  docs/resources/redis.md
  internal/schemautil/service.go
Labels: enhancement
