Repository aiven/terraform-provider-aiven, pull requests merged in 2023-02, with the labels that each got.

#1051 feat(flink): application resource
  CHANGELOG.md
  go.mod
  go.sum
  internal/provider/provider.go
  internal/service/flink/flink_application.go
  internal/service/flink/flink_test.go
Labels: enhancement

#1053 add external_aws_cloudwatch_metrics integration type
  CHANGELOG.md
  docs/data-sources/service_integration.md
  docs/resources/flink_application.md
  docs/resources/service_integration.md
  internal/service/serviceintegration/service_integration.go
Labels: enhancement

#1055 fix(kafka): default_acl
  CHANGELOG.md
  internal/schemautil/schemautil.go
  internal/service/kafka/kafka.go
Labels: bug

#1059 test(kafka): fix default_acl behavior
  internal/service/kafka/kafka_test.go
Labels: bug, no changelog

#1060 fix(schemautil): CreateOnlyDiffSuppressFunc
  CHANGELOG.md
  internal/schemautil/schemautil.go
Labels: bug

#1061 fix(schemautil): maintenance_window_dow=never resource update
  CHANGELOG.md
  internal/schemautil/helpers.go
  internal/schemautil/service.go
Labels: bug

#1039 fix(docs): index.md provider version
  docs/index.md
  templates/index.md
Labels: documentation, no changelog

#1066 ci(lint): add commitlint
  .github/workflows/lint.yml
  CONTRIBUTING.md
Labels: enhancement, no changelog, github_actions

#1067 fix(sweep): use accounts with test prefix
  internal/service/account/sweep.go
Labels: bug, no changelog

#1071 docs(changelog): drop wrong entries
  CHANGELOG.md
Labels: documentation
