Repository aiven/terraform-provider-aiven, pull requests merged in 2023-10, with the labels that each got.

#1373 fix(project_user): invite error handling
  CHANGELOG.md
  internal/sdkprovider/service/project/project_user.go
Labels: bug

#1369 feat(kafka): allow protobuf schema
  CHANGELOG.md
  docs/data-sources/kafka_schema.md
  docs/data-sources/kafka_schema_configuration.md
  docs/resources/kafka_schema.md
  internal/sdkprovider/service/kafkaschema/kafka_schema.go
  internal/sdkprovider/service/kafkaschema/kafka_schema_test.go
Labels: enhancement

#1375 chore(release): v4.9.1
  CHANGELOG.md
Labels: release

#1342 feat(plugin): add new user config generator
  CHANGELOG.md
  Makefile
  docs/data-sources/service_integration.md
  docs/resources/service_integration.md
  go.mod
  go.sum
  internal/plugin/provider.go
  internal/plugin/service/serviceintegration/models.go
  internal/plugin/service/serviceintegration/service_integration_data_source.go
  internal/plugin/service/serviceintegration/service_integration_resource.go
  internal/plugin/service/serviceintegration/userconfig.go
  internal/plugin/service/userconfig/integration/clickhousekafka/clickhouse_kafka.go
  internal/plugin/service/userconfig/integration/clickhousekafka/clickhouse_kafka_test.go
  internal/plugin/service/userconfig/integration/clickhousepostgresql/clickhouse_postgresql.go
  internal/plugin/service/userconfig/integration/clickhousepostgresql/clickhouse_postgresql_test.go
  internal/plugin/service/userconfig/integration/datadog/datadog.go
  internal/plugin/service/userconfig/integration/datadog/datadog_test.go
  internal/plugin/service/userconfig/integration/externalawscloudwatchmetrics/external_aws_cloudwatch_metrics.go
  internal/plugin/service/userconfig/integration/externalawscloudwatchmetrics/external_aws_cloudwatch_metrics_test.go
  internal/plugin/service/userconfig/integration/kafkaconnect/kafka_connect.go
  internal/plugin/service/userconfig/integration/kafkaconnect/kafka_connect_test.go
  internal/plugin/service/userconfig/integration/kafkalogs/kafka_logs.go
  internal/plugin/service/userconfig/integration/kafkalogs/kafka_logs_test.go
  internal/plugin/service/userconfig/integration/kafkamirrormaker/kafka_mirrormaker.go
  internal/plugin/service/userconfig/integration/kafkamirrormaker/kafka_mirrormaker_test.go
  internal/plugin/service/userconfig/integration/logs/logs.go
  internal/plugin/service/userconfig/integration/logs/logs_test.go
  internal/plugin/service/userconfig/integration/metrics/metrics.go
  internal/plugin/service/userconfig/integration/metrics/metrics_test.go
  internal/plugin/util/schema.go
  internal/plugin/util/wait.go
  internal/schemautil/plugin.go
  internal/schemautil/userconfig/dist/integration_endpoint_types.go
  internal/schemautil/userconfig/dist/integration_types.go
  internal/schemautil/userconfig/dist/service_types.go
  internal/sdkprovider/provider/provider.go
  internal/sdkprovider/service/kafkatopic/kafka_topic_cache.go
  internal/sdkprovider/service/serviceintegration/service_integration_test.go
  main.go
  ucgenerator/main.go
  ucgenerator/models.go
  ucgenerator/tests.go
Labels: enhancement

#1377 fix(organization_user): serialize create_time to string
  CHANGELOG.md
  internal/sdkprovider/service/organization/organization_user.go
Labels: bug

#1381 ci: fix code generation
  .github/workflows/userconfig-generate-schema.yml
Labels: no changelog

#1382 feat(plugin): use set instead of list
  CHANGELOG.md
  docs/data-sources/service_integration.md
  docs/resources/service_integration.md
  internal/plugin/service/serviceintegration/models.go
  internal/plugin/service/serviceintegration/userconfig.go
  internal/plugin/service/userconfig/integration/clickhousekafka/clickhouse_kafka.go
  internal/plugin/service/userconfig/integration/clickhousepostgresql/clickhouse_postgresql.go
  internal/plugin/service/userconfig/integration/datadog/datadog.go
  internal/plugin/service/userconfig/integration/externalawscloudwatchmetrics/external_aws_cloudwatch_metrics.go
  internal/plugin/service/userconfig/integration/kafkaconnect/kafka_connect.go
  internal/plugin/service/userconfig/integration/kafkalogs/kafka_logs.go
  internal/plugin/service/userconfig/integration/kafkamirrormaker/kafka_mirrormaker.go
  internal/plugin/service/userconfig/integration/logs/logs.go
  internal/plugin/service/userconfig/integration/metrics/metrics.go
  internal/schemautil/plugin.go
  internal/sdkprovider/service/serviceintegration/service_integration.go
  internal/sdkprovider/service/serviceintegration/service_integration_data_source.go
  ucgenerator/main.go
Labels: no changelog

#1391 fix(go.mod): fix broken dependency
  go.mod
Labels: no changelog

#1392 fix: user config marshal error omitted
  internal/plugin/service/serviceintegration/service_integration_resource.go
  internal/plugin/service/serviceintegration/userconfig.go
  internal/plugin/service/userconfig/integration/clickhousekafka/clickhouse_kafka_test.go
  internal/plugin/service/userconfig/integration/clickhousepostgresql/clickhouse_postgresql_test.go
  internal/plugin/service/userconfig/integration/datadog/datadog_test.go
  internal/plugin/service/userconfig/integration/externalawscloudwatchmetrics/external_aws_cloudwatch_metrics_test.go
  internal/plugin/service/userconfig/integration/kafkaconnect/kafka_connect_test.go
  internal/plugin/service/userconfig/integration/kafkalogs/kafka_logs_test.go
  internal/plugin/service/userconfig/integration/kafkamirrormaker/kafka_mirrormaker_test.go
  internal/plugin/service/userconfig/integration/logs/logs_test.go
  internal/plugin/service/userconfig/integration/metrics/metrics_test.go
  internal/schemautil/plugin.go
  internal/schemautil/userconfig/dist/integration_endpoint_types.go
  internal/schemautil/userconfig/dist/integration_types.go
  internal/schemautil/userconfig/dist/service_types.go
  ucgenerator/tests.go
Labels: no changelog

#1395 test(opensearch): fix weak password error
  internal/sdkprovider/service/opensearch/opensearch_security_plugin_config_test.go
  internal/sdkprovider/service/opensearch/opensearch_user_test.go
Labels: bug, no changelog

#1398 test: fix failing billing group test
  internal/sdkprovider/service/project/billing_group_test.go
Labels: bug, no changelog

#1390 chore: deprecating account and project user
  CHANGELOG.md
  internal/sdkprovider/service/account/account_team.go
  internal/sdkprovider/service/account/account_team_member.go
  internal/sdkprovider/service/project/project_user.go
Labels: documentation

#1404 test(project): fix failing tests
  internal/sdkprovider/service/project/project_user_test.go
Labels: bug, no changelog

#1405 test(account): fix failing team tests
  .github/workflows/acceptance-tests.yml
  internal/sdkprovider/service/account/account_authentication_test.go
  internal/sdkprovider/service/account/account_team_data_source_test.go
  internal/sdkprovider/service/account/account_team_member_data_source_test.go
  internal/sdkprovider/service/account/account_team_member_test.go
  internal/sdkprovider/service/account/account_team_project_test.go
  internal/sdkprovider/service/account/account_team_test.go
Labels: bug, no changelog

#1407 test(project): fix missing organization link
  internal/sdkprovider/service/project/project_user_test.go
Labels: bug, no changelog

#1408 fix(mysql): use correct read context fn
  CHANGELOG.md
  internal/sdkprovider/service/mysql/mysql_user.go
Labels: bug

#1406 test(flink): fix application version flakiness
  internal/sdkprovider/service/flink/flink_application_version.go
Labels: bug, no changelog

#1416 chore(changelog): drop v4 entry
  CHANGELOG.md
Labels: documentation, no changelog

#1421 chore(changelog): fix typo
  CHANGELOG.md
Labels: documentation

#1420 chore(userconfig): improve naming and docs
  Makefile
  internal/schemautil/userconfig/apiconvert/fromapi.go
  internal/schemautil/userconfig/apiconvert/fromapi_test.go
  internal/schemautil/userconfig/apiconvert/toapi.go
  internal/schemautil/userconfig/apiconvert/toapi_test.go
  internal/schemautil/userconfig/apiconvert/util.go
  internal/schemautil/userconfig/apiconvert/util_test.go
  internal/schemautil/userconfig/convert.go
  internal/schemautil/userconfig/desc.go
  internal/schemautil/userconfig/handle.go
  internal/schemautil/userconfig/stateupgrader/typeupgrader/typeupgrader.go
  internal/schemautil/userconfig/stateupgrader/typeupgrader/typeupgrader_test.go
  internal/schemautil/userconfig/stateupgrader/v0/cassandra/cassandra.go
  internal/schemautil/userconfig/stateupgrader/v0/flink/flink.go
  internal/schemautil/userconfig/stateupgrader/v0/grafana/grafana.go
  internal/schemautil/userconfig/stateupgrader/v0/influxdb/influxdb.go
  internal/schemautil/userconfig/stateupgrader/v0/kafka/kafka.go
  internal/schemautil/userconfig/stateupgrader/v0/kafka/kafka_connect.go
  internal/schemautil/userconfig/stateupgrader/v0/kafka/kafka_mirrormaker.go
  internal/schemautil/userconfig/stateupgrader/v0/kafka/kafka_topic.go
  internal/schemautil/userconfig/stateupgrader/v0/m3/m3aggregator.go
  internal/schemautil/userconfig/stateupgrader/v0/m3/m3db.go
  internal/schemautil/userconfig/stateupgrader/v0/mysql/mysql.go
  internal/schemautil/userconfig/stateupgrader/v0/opensearch/opensearch.go
  internal/schemautil/userconfig/stateupgrader/v0/pg/pg.go
  internal/schemautil/userconfig/stateupgrader/v0/redis/redis.go
  internal/schemautil/userconfig/stateupgrader/v0/serviceintegration/service_integration.go
  internal/schemautil/userconfig/stateupgrader/v0/serviceintegration/service_integration_endpoint.go
  internal/schemautil/userconfig/userconfig_test.go
  internal/schemautil/userconfig/util.go
Labels: enhancement, documentation, no changelog
