Repository aiven/terraform-provider-aiven, pull requests merged in 2023-08, with the labels that each got.

#1278 fix(project): incorrect account_id behavior in mixed constraint setup
  CHANGELOG.md
  internal/sdkprovider/service/project/project.go
Labels: bug

#1279 chore(tests): run organization tests
  .github/workflows/acceptance-tests.yml
Labels: no changelog

#1217 chore: use client's retries
  CHANGELOG.md
  go.mod
  go.sum
  internal/sdkprovider/service/kafka/kafka_connector.go
  internal/sdkprovider/service/kafka/kafka_connector_test.go
  internal/sdkprovider/service/kafka/kafka_topic.go
  internal/sdkprovider/service/kafka/kafka_topic_cache.go
  internal/sdkprovider/service/kafka/kafka_topic_create.go
  internal/sdkprovider/service/kafka/kafka_topic_data_source_test.go
  internal/sdkprovider/service/kafka/kafka_topic_test.go
  internal/sdkprovider/service/kafka/kafka_topic_wait.go
  internal/sdkprovider/service/serviceintegration/service_integration.go
  internal/sdkprovider/service/vpc/project_vpc_test.go
Labels: enhancement

#1289 fix(account): deletion flakiness
  CHANGELOG.md
  internal/sdkprovider/service/account/account.go
Labels: bug

#1292 fix(kafka_connector): set a minite timeout for create retries
  internal/sdkprovider/service/kafka/kafka_connector.go
Labels: no changelog

#1295 test(project): broken without account or organization link
  internal/sdkprovider/service/account/account_test.go
  internal/sdkprovider/service/organization/organization_test.go
  internal/sdkprovider/service/project/project_test.go
Labels: bug, no changelog

#1256 refactor(kafka_schema): simplify kafka schema import
  internal/schemautil/schemautil.go
  internal/sdkprovider/service/kafka/kafka_schema.go
Labels: no changelog, refactor

#1305 revert(kafka): remove the tiered storage functionality
  docs/data-sources/kafka.md
  docs/resources/kafka.md
  internal/schemautil/userconfig/dist/service_types.go
  main.go
Labels: no changelog

#1306 release: v4.8.0
  CHANGELOG.md
Labels: release

#1307 chore(release): v4.8.1
  CHANGELOG.md
Labels: release

#1309 fix: remove beta properties
  go.mod
  go.sum
  internal/schemautil/userconfig/apiconvert/fromapi_test.go
  main.go
Labels: no changelog

#1311 fix: sdk provider config
  internal/sdkprovider/provider/provider.go
Labels: no changelog

#1313 fix(transit_gateway_vpc_attachment): send empty slices on update, not nil
  CHANGELOG.md
  internal/sdkprovider/service/vpc/transit_gateway_vpc_attachment.go
Labels: bug

#1315 fix(migrations): ip filter migrations
  CHANGELOG.md
  internal/schemautil/mutations.go
Labels: bug

#1322 refactor(kafka_topic_cache): init cache on module level
  internal/sdkprovider/service/kafka/kafka_topic.go
  internal/sdkprovider/service/kafka/kafka_topic_cache.go
  internal/sdkprovider/service/kafka/kafka_topic_cache_test.go
Labels: no changelog

#1321 chore(organization): drop obsolete resources and data sources
  internal/sdkprovider/service/organization/organization.go
  internal/sdkprovider/service/organization/organization_data_source.go
  internal/sdkprovider/service/organization/organization_data_source_test.go
  internal/sdkprovider/service/organization/organization_test.go
Labels: no changelog

#1325 refactor(kafka): split kafka package to run tests faster
  .github/workflows/acceptance-tests.yml
  internal/sdkprovider/provider/provider.go
  internal/sdkprovider/service/kafka/kafka_test.go
  internal/sdkprovider/service/kafkaschema/kafka_schema.go
  internal/sdkprovider/service/kafkaschema/kafka_schema_configuration.go
  internal/sdkprovider/service/kafkaschema/kafka_schema_configuration_data_source.go
  internal/sdkprovider/service/kafkaschema/kafka_schema_configuration_test.go
  internal/sdkprovider/service/kafkaschema/kafka_schema_data_source.go
  internal/sdkprovider/service/kafkaschema/kafka_schema_registry_acl.go
  internal/sdkprovider/service/kafkaschema/kafka_schema_registry_acl_data_source.go
  internal/sdkprovider/service/kafkaschema/kafka_schema_registry_acl_test.go
  internal/sdkprovider/service/kafkaschema/kafka_schema_test.go
  internal/sdkprovider/service/kafkatopic/kafka_topic.go
  internal/sdkprovider/service/kafkatopic/kafka_topic_cache.go
  internal/sdkprovider/service/kafkatopic/kafka_topic_cache_test.go
  internal/sdkprovider/service/kafkatopic/kafka_topic_create.go
  internal/sdkprovider/service/kafkatopic/kafka_topic_data_source.go
  internal/sdkprovider/service/kafkatopic/kafka_topic_data_source_test.go
  internal/sdkprovider/service/kafkatopic/kafka_topic_test.go
  internal/sdkprovider/service/kafkatopic/kafka_topic_wait.go
Labels: no changelog

#1328 fix(apiconvert): toapi improper omitting
  CHANGELOG.md
  internal/schemautil/userconfig/apiconvert/toapi.go
  internal/schemautil/userconfig/apiconvert/toapi_test.go
Labels: bug

#1331 docs(clickhouse): highlight how to grant privilege on all tables
  docs/resources/clickhouse_grant.md
  internal/sdkprovider/service/clickhouse/clickhouse_grant.go
Labels: documentation, no changelog
