Repository aiven/terraform-provider-aiven, pull requests merged in 2023-06, with the labels that each got.

#1188 fix(kafka_topic): fix kafka topic 404 error handling
  CHANGELOG.md
  internal/service/kafka/kafka_topic_cache.go
  internal/service/kafka/kafka_topic_wait.go
Labels: bug

#1194 fix(apiconvert): not being able to unset ip_filter and alike
  CHANGELOG.md
  internal/schemautil/userconfig/apiconvert/toapi.go
  internal/schemautil/userconfig/apiconvert/toapi_test.go
Labels: bug

#1204 fix(vpc): cidrs handled improperly
  CHANGELOG.md
  docs/resources/transit_gateway_vpc_attachment.md
  internal/schemautil/schemautil.go
  internal/schemautil/userconfig/apiconvert/fromapi.go
  internal/schemautil/userconfig/apiconvert/toapi.go
  internal/sdkprovider/service/vpc/transit_gateway_vpc_attachment.go
  internal/sdkprovider/service/vpc/transit_gateway_vpc_attachment_data_source.go
  internal/sdkprovider/service/vpc/transit_gateway_vpc_attachment_test.go
  internal/sdkprovider/service/vpc/vpc_peering_connection.go
Labels: bug

#1207 chore(release): v4.5.0
  CHANGELOG.md
Labels: release

#1218 fix(organization): wrong ID used
  CHANGELOG.md
  internal/sdkprovider/service/opensearch/opensearch_acl_config.go
  internal/sdkprovider/service/opensearch/opensearch_acl_rule.go
  internal/sdkprovider/service/organization/organization.go
  internal/sdkprovider/service/organization/organizational_unit.go
  internal/sdkprovider/service/organization/util.go
Labels: bug

#1219 fix: fix typo in a debug log message
  internal/sdkprovider/service/project/project.go
Labels: no changelog

#1222 test(vpc): fix free tier error
  internal/sdkprovider/service/vpc/project_vpc_test.go
Labels: enhancement, no changelog

#1223 feat(flink): application deployment
  CHANGELOG.md
  go.mod
  go.sum
  internal/sdkprovider/provider/provider.go
  internal/sdkprovider/service/flink/flink_application_deployment.go
  internal/sdkprovider/service/flink/flink_application_version_test.go
Labels: enhancement

#1230 feat(project): cascading account_id in pj and bg resources
  CHANGELOG.md
  docs/data-sources/billing_group.md
  docs/data-sources/project.md
  docs/resources/billing_group.md
  docs/resources/project.md
  internal/schemautil/helpers.go
  internal/sdkprovider/service/organization/organization.go
  internal/sdkprovider/service/organization/organizational_unit.go
  internal/sdkprovider/service/organization/util.go
  internal/sdkprovider/service/project/billing_group.go
  internal/sdkprovider/service/project/project.go
  internal/sdkprovider/service/project/project_test.go
  internal/sdkprovider/service/project/util.go
Labels: enhancement
