Repository aiven/terraform-provider-aiven, pull requests merged in 2023-12, with the labels that each got.

#1461 fix(kafka_topic): remove expect non empty diff in test
  internal/sdkprovider/service/kafkatopic/kafka_topic_test.go
Labels: bug, no changelog

#1465 feat(sweeper): add billing group support
  internal/sdkprovider/service/project/sweep.go
Labels: enhancement, no changelog

#1468 chore: deprecate aiven_account_authentication resource
  CHANGELOG.md
  internal/sdkprovider/service/account/account_authentication.go
  internal/sdkprovider/service/account/account_authentication_data_source.go
  internal/sdkprovider/service/account/account_authentication_test.go
Labels: enhancement

#1471 fix(account_team_member): no err on deletion if it does not exist
  CHANGELOG.md
  internal/sdkprovider/service/account/account_team_member.go
Labels: bug

#1473 fix(mirrormaker_replication_flow): race on create/update/delete opera…
  CHANGELOG.md
  internal/sdkprovider/service/kafka/mirrormaker_replication_flow.go
Labels: bug

#1472 ci(test): proper concurrency support
  .github/workflows/acceptance-tests.yml
  .github/workflows/examples-tests.yml
  Makefile
  go.mod
  internal/schemautil/userconfig/userconfig_test.go
  tools/go.mod
  tools/go.sum
  tools/main.go
  tools/selproj/README.md
  tools/selproj/client.go
  tools/selproj/go.mod
  tools/selproj/go.sum
  tools/selproj/main.go
  tools/selproj/mock_client.go
  tools/selproj/selectproject.go
  tools/selproj/selectproject_test.go
Labels: enhancement, no changelog

#1485 ci(test): proper project name prefix var substitution
  .github/workflows/acceptance-tests.yml
  .github/workflows/examples-tests.yml
  .github/workflows/sweep.yml
  tools/selproj/README.md
  tools/selproj/main.go
  tools/selproj/selectproject.go
  tools/selproj/selectproject_test.go
Labels: bug, no changelog

#1491 fix(kafka_topic): migration from v3
  CHANGELOG.md
  internal/schemautil/userconfig/stateupgrader/v0/kafka/kafka_topic.go
Labels: bug

#1494 fix(service): v3 to v4 migration cloud_name field
  CHANGELOG.md
  internal/schemautil/service.go
Labels: bug

#1493 chore(release): v4.10.0
  CHANGELOG.md
Labels: release

#1484 feat(org_user): deprecating resource, new datasource
  CHANGELOG.md
  docs/data-sources/organization_user.md
  docs/resources/organization_user.md
  internal/sdkprovider/service/organization/organization_user.go
  internal/sdkprovider/service/organization/organization_user_data_source.go
  internal/sdkprovider/service/organization/organization_user_data_source_test.go
Labels: enhancement

#1495 chore(changelog): fix after automerge
  CHANGELOG.md
Labels: enhancement

#1496 feat(organization): add support for group projects
  CHANGELOG.md
  docs/resources/organization_group_project.md
  go.mod
  go.sum
  internal/plugin/provider.go
  internal/plugin/service/organization/organization_group_project.go
  internal/plugin/service/organization/organization_group_project_test.go
Labels: enhancement
