Repository aiven/terraform-provider-aiven, pull requests merged in 2023-04, with the labels that each got.

#1119 fix: add conflicting with logic for namespaces and ip_filters
  CHANGELOG.md
  internal/schemautil/custom_diff.go
  internal/sdkprovider/service/m3db/m3db_test.go
Labels: bug

#1121 ci(lint): drop forced Go version in golangci-lint
  .golangci.yml
Labels: enhancement, no changelog

#1120 chore: replace exp with go-api-schemas
  go.mod
  go.sum
  internal/schemautil/database.go
  internal/schemautil/userconfig/userconfig_test.go
  internal/schemautil/userconfig/util.go
  internal/schemautil/wait.go
  internal/sdkprovider/service/kafka/kafka_connector.go
  internal/sdkprovider/service/kafka/kafka_topic.go
  internal/sdkprovider/service/kafka/kafka_topic_create.go
  internal/sdkprovider/service/kafka/kafka_topic_wait.go
  internal/sdkprovider/service/pg/pg.go
  internal/sdkprovider/service/project/project.go
  internal/sdkprovider/service/serviceintegration/service_integration.go
  internal/sdkprovider/service/staticip/static_ip.go
  internal/sdkprovider/service/vpc/aws_privatelink.go
  internal/sdkprovider/service/vpc/aws_vpc_peering_connection.go
  internal/sdkprovider/service/vpc/azure_privatelink.go
  internal/sdkprovider/service/vpc/azure_privatelink_connection_approve.go
  internal/sdkprovider/service/vpc/azure_vpc_peering_connection.go
  internal/sdkprovider/service/vpc/gcp_vpc_peering_connection.go
  internal/sdkprovider/service/vpc/project_vpc.go
  internal/sdkprovider/service/vpc/vpc_peering_connection.go
  tools/go.mod
  tools/go.sum
Labels: enhancement, no changelog

#1118 fix(apiconvert): double apply necessity on migration
  CHANGELOG.md
  internal/schemautil/userconfig/apiconvert/toapi.go
  internal/schemautil/userconfig/apiconvert/toapi_test.go
  internal/schemautil/userconfig/dist/service_types.go
  internal/schemautil/userconfig/handle.go
Labels: bug

#1127 chore(release): v4.2.1
  CHANGELOG.md
Labels: release

#1129 docs(service_integration_endpoint): endpoint_type
  CHANGELOG.md
  docs/data-sources/service_integration_endpoint.md
  docs/resources/service_integration_endpoint.md
  internal/sdkprovider/service/serviceintegration/service_integration_endpoint.go
Labels: documentation

#1132 feat: drop signalfx from supported integration types
  CHANGELOG.md
  docs/data-sources/service_integration_endpoint.md
  docs/resources/service_integration_endpoint.md
  internal/schemautil/userconfig/stateupgrader/v0/serviceintegration/service_integration_endpoint.go
  internal/sdkprovider/service/serviceintegration/service_integration_endpoint.go
Labels: enhancement

#1135 fix(mysql): user creation authentication field
  CHANGELOG.md
  go.mod
  go.sum
  internal/sdkprovider/service/mysql/mysql_user.go
Labels: bug
