Repository aiven/terraform-provider-aiven, pull requests merged in 2023-01, with the labels that each got.

#1015 add mysql example test
  .github/workflows/examples-tests.yml
  examples/kafka_connect/provider.tf
  examples/kafka_connectors/os_sink/provider.tf
  examples/kafka_connectors/os_sink/services.tf
  examples/kafka_prometheus/provider.tf
  examples/mysql/provider.tf
  examples/mysql/service.tf
  examples/mysql/variables.tf
  examples/postgres/provider.tf
  examples_tests/base.go
  examples_tests/base_test.go
  examples_tests/kafka_connect_test.go
  examples_tests/kafka_connector_test.go
  examples_tests/kafka_prometheus_test.go
  examples_tests/mysql_test.go
  examples_tests/postgres_test.go
  sample_project/sample.tf
Labels: no changelog

#1008 recreate missing kafka topics
  CHANGELOG.md
  examples_tests/base.go
  go.mod
  go.sum
  internal/common/client.go
  internal/provider/provider.go
  internal/service/kafka/datasource_kafka_topic.go
  internal/service/kafka/datasource_kafka_topic_test.go
  internal/service/kafka/kafka_topic_availability.go
  internal/service/kafka/kafka_topic_cache.go
  internal/service/kafka/resource_kafka_topic.go
  internal/service/kafka/resource_kafka_topic_test.go
  internal/sweep/sweep.go
Labels: enhancement

#1031 release: v3.11.0
  CHANGELOG.md
Labels: release

#1032 add service integration endpoints sweeper
  internal/service/account/sweep.go
  internal/service/cassandra/sweep.go
  internal/service/clickhouse/sweep.go
  internal/service/flink/sweep.go
  internal/service/grafana/sweep.go
  internal/service/influxdb/sweep.go
  internal/service/kafka/sweep.go
  internal/service/m3db/sweep.go
  internal/service/mysql/sweep.go
  internal/service/opensearch/sweep.go
  internal/service/pg/sweep.go
  internal/service/project/sweep.go
  internal/service/redis/sweep.go
  internal/service/service_integration/sweep.go
  internal/service/static_ip/sweep.go
  internal/sweep/sweep.go
  internal/sweep/sweep_test.go
Labels: no changelog

#1024 feat(stateupgrader): mysql v0
  internal/schemautil/userconfig/stateupgrader/upgraders.go
  internal/schemautil/userconfig/stateupgrader/v0/resource_mysql.go
  internal/service/mysql/resource_mysql.go
Labels: enhancement

#1026 feat(stateupgrader): pg v0
  internal/schemautil/userconfig/stateupgrader/upgraders.go
  internal/schemautil/userconfig/stateupgrader/v0/resource_pg.go
  internal/service/pg/resource_pg.go
Labels: enhancement

#1027 feat(stateupgrader): redis v0
  internal/schemautil/userconfig/stateupgrader/upgraders.go
  internal/schemautil/userconfig/stateupgrader/v0/resource_redis.go
  internal/service/redis/resource_redis.go
Labels: enhancement

#1029 feat(stateupgrader): service integration v0
  internal/schemautil/userconfig/stateupgrader/upgraders.go
  internal/schemautil/userconfig/stateupgrader/v0/resource_service_integration.go
  internal/service/service_integration/resource_service_integration.go
Labels: enhancement

#1036 remove deprecated resources
  CHANGELOG.md
  docs/data-sources/database.md
  docs/data-sources/service_user.md
  docs/data-sources/vpc_peering_connection.md
  docs/resources/database.md
  docs/resources/kafka_user.md
  docs/resources/opensearch_acl_config.md
  docs/resources/opensearch_acl_rule.md
  docs/resources/service_user.md
  docs/resources/vpc_peering_connection.md
  examples/data-sources/aiven_database/data-source.tf
  examples/data-sources/aiven_service_user/data-source.tf
  examples/data-sources/aiven_vpc_peering_connection/data-source.tf
  examples/elasticsearch/elasticsearch_acl.tf
  examples/elasticsearch/elasticsearch_service.tf
  examples/elasticsearch/project.tf
  examples/elasticsearch/provider.tf
  examples/elasticsearch/variables.tf
  examples/kafka_connectors/mongo_sink/services.tf
  examples/opensearch/opensearch_acl.tf
  examples/opensearch/opensearch_service.tf
  examples/resources/aiven_database/import.sh
  examples/resources/aiven_database/resource.tf
  examples/resources/aiven_elasticsearch/import.sh
  examples/resources/aiven_elasticsearch/resource.tf
  examples/resources/aiven_elasticsearch_acl/import.sh
  examples/resources/aiven_elasticsearch_acl/resource.tf
  examples/resources/aiven_elasticsearch_acl_config/import.sh
  examples/resources/aiven_elasticsearch_acl_config/resource.tf
  examples/resources/aiven_elasticsearch_acl_rule/import.sh
  examples/resources/aiven_elasticsearch_acl_rule/resource.tf
  examples/resources/aiven_kafka_user/resource.tf
  examples/resources/aiven_opensearch_acl_config/resource.tf
  examples/resources/aiven_opensearch_acl_rule/resource.tf
  examples/resources/aiven_service_user/import.sh
  examples/resources/aiven_service_user/resource.tf
  examples/resources/aiven_vpc_peering_connection/import.sh
  examples/resources/aiven_vpc_peering_connection/resource.tf
  internal/acctest/acctest.go
  internal/provider/provider.go
  internal/service/connectionpool/connection_pool_test.go
  internal/service/database/database.go
  internal/service/database/database_data_source.go
  internal/service/database/database_test.go
  internal/service/opensearch/opensearch_acl_config_test.go
  internal/service/opensearch/opensearch_acl_rule_test.go
  internal/service/serviceuser/service_user.go
  internal/service/serviceuser/service_user_data_source.go
  internal/service/serviceuser/service_user_test.go
  internal/service/vpc/transit_gateway_vpc_attachement_data_source.go
  internal/service/vpc/vpc_peering_connection.go
  internal/service/vpc/vpc_peering_connection_data_source.go
  templates/resources/service_user.md.tmpl
  templates/resources/vpc_peering_connection.md.tmpl
Labels: enhancement

#1038 fix(flink): incorrect state name spelling
  CHANGELOG.md
  internal/service/flink/flink_job.go
Labels: bug

#1040 refactor(stateupgrader): match with repo struct
  internal/schemautil/userconfig/stateupgrader/upgraders.go
  internal/schemautil/userconfig/stateupgrader/v0/cassandra/cassandra.go
  internal/schemautil/userconfig/stateupgrader/v0/flink/flink.go
  internal/schemautil/userconfig/stateupgrader/v0/grafana/grafana.go
  internal/schemautil/userconfig/stateupgrader/v0/influxdb/influxdb.go
  internal/schemautil/userconfig/stateupgrader/v0/kafka/kafka.go
  internal/schemautil/userconfig/stateupgrader/v0/kafka/kafka_connect.go
  internal/schemautil/userconfig/stateupgrader/v0/kafka/kafka_mirrormaker.go
  internal/schemautil/userconfig/stateupgrader/v0/m3/m3aggregator.go
  internal/schemautil/userconfig/stateupgrader/v0/m3/m3db.go
  internal/schemautil/userconfig/stateupgrader/v0/mysql/mysql.go
  internal/schemautil/userconfig/stateupgrader/v0/opensearch/opensearch.go
  internal/schemautil/userconfig/stateupgrader/v0/pg/pg.go
  internal/schemautil/userconfig/stateupgrader/v0/redis/redis.go
  internal/schemautil/userconfig/stateupgrader/v0/serviceintegration/service_integration.go
  internal/schemautil/userconfig/stateupgrader/v0/serviceintegration/service_integration_endpoint.go
Labels: refactor

#1042 sweep test-tf prefix too
  internal/sweep/sweep.go
Labels: no changelog

#1043 feat(userconfig): default values
  internal/schemautil/userconfig/convert.go
  internal/schemautil/userconfig/dist/integration_endpoint_types.go
  internal/schemautil/userconfig/dist/integration_types.go
  internal/schemautil/userconfig/dist/service_types.go
  internal/schemautil/userconfig/handle.go
Labels: enhancement

#1047 chore: mark flink job and table resources as deprecated
  internal/schemautil/common.go
  internal/service/flink/flink_job.go
  internal/service/flink/flink_table.go
Labels: no changelog

#1048 chore(flink): drop deprecated resources
  CHANGELOG.md
  docs/resources/flink_job.md
  docs/resources/flink_table.md
  examples/flink/main.tf
  examples/resources/aiven_flink_job/resource.tf
  examples/resources/aiven_flink_table/import.sh
  examples/resources/aiven_flink_table/resource.tf
  internal/provider/provider.go
  internal/service/flink/flink_job.go
  internal/service/flink/flink_table.go
  internal/service/flink/flink_test.go
Labels: enhancement
