Repository aiven/terraform-provider-aiven, pull requests merged in 2023-07, with the labels that each got.

#1238 fix(opensearch): typo
  docs/data-sources/opensearch_user.md
  internal/sdkprovider/service/opensearch/opensearch_user_data_source.go
Labels: no changelog

#1242 chore(project): rename owner_entity_id to parent_id
  CHANGELOG.md
  docs/data-sources/billing_group.md
  docs/data-sources/project.md
  docs/resources/billing_group.md
  docs/resources/project.md
  internal/sdkprovider/service/project/billing_group.go
  internal/sdkprovider/service/project/project.go
  internal/sdkprovider/service/project/project_test.go
  internal/sdkprovider/service/project/util.go
Labels: enhancement

#1244 chore(go): upgrade go 1.19
  .github/workflows/acceptance-tests.yml
  .github/workflows/examples-tests.yml
  .github/workflows/lint.yml
  .github/workflows/release-artifacts.yml
  .github/workflows/sweep.yml
  .github/workflows/unit-tests.yml
  go.mod
  tools/go.mod
Labels: no changelog

#1234 fix(kafka_schema): compatibility_level import shows non empty plan
  CHANGELOG.md
  internal/schemautil/schemautil.go
  internal/sdkprovider/service/kafka/kafka_schema.go
  internal/sdkprovider/service/kafka/kafka_schema_test.go
Labels: bug

#1249 chore(ci): quiet terraform fmt linter
  Makefile
Labels: no changelog

#1246 feat(organization): user resource and data source
  CHANGELOG.md
  internal/sdkprovider/provider/provider.go
  internal/sdkprovider/service/organization/organization_user.go
  internal/sdkprovider/service/organization/organization_user_data_source.go
  internal/sdkprovider/service/organization/organization_user_data_source_test.go
  internal/sdkprovider/service/organization/organization_user_test.go
Labels: enhancement

#1255 chore(release): v4.7.0
  CHANGELOG.md
Labels: release

#1258 chore: fix Privatelink typo
  CHANGELOG.md
  internal/sdkprovider/service/vpc/aws_privatelink_test.go
  internal/sdkprovider/service/vpc/azure_privatelink_connection_approve_test.go
Labels: enhancement

#1259 feat(vpc): gcp privatelink
  CHANGELOG.md
  internal/sdkprovider/provider/provider.go
  internal/sdkprovider/service/vpc/azure_privatelink_connection_approve.go
  internal/sdkprovider/service/vpc/azure_privatelink_connection_approve_test.go
  internal/sdkprovider/service/vpc/azure_privatelink_test.go
  internal/sdkprovider/service/vpc/gcp_privatelink.go
  internal/sdkprovider/service/vpc/gcp_privatelink_connection_approve.go
  internal/sdkprovider/service/vpc/gcp_privatelink_data_source.go
  internal/sdkprovider/service/vpc/gcp_privatelink_test.go
  internal/sdkprovider/service/vpc/util_test.go
Labels: enhancement

#1266 chore(release): v4.8.0
  CHANGELOG.md
Labels: release

#1264 feat(org): add org user group support
  CHANGELOG.md
  docs/data-sources/organization_user_group.md
  docs/resources/organization_user_group.md
  go.sum
  internal/sdkprovider/provider/provider.go
  internal/sdkprovider/service/organization/organization_user_group.go
  internal/sdkprovider/service/organization/organization_user_group_data_source.go
  internal/sdkprovider/service/organization/organization_user_group_test.go
Labels: enhancement

#1277 fix(frameworkprovider): failing build
  internal/provider/provider.go
  internal/sdkprovider/provider/provider.go
  main.go
Labels: bug, no changelog
