Repository aiven/terraform-provider-aiven, pull requests merged in 2023-09, with the labels that each got.

#1335 docs(clickhouse): remove deprecation warnings
  internal/sdkprovider/service/clickhouse/clickhouse_grant.go
  internal/sdkprovider/service/clickhouse/clickhouse_role.go
  internal/sdkprovider/service/clickhouse/clickhouse_user.go
  internal/sdkprovider/service/clickhouse/common.go
Labels: documentation, no changelog

#1347 fix(kafkatopic): cache invalidation
  internal/sdkprovider/service/kafkatopic/kafka_topic_cache.go
Labels: no changelog

#1348 test(connectionpool): fix misuse of wrong user resource
  internal/sdkprovider/service/connectionpool/connection_pool_test.go
Labels: bug, no changelog

#1350 docs(sample_project): replace deprecated ip_filter argument
  sample_project/sample.tf
Labels: documentation, no changelog

#1353 chore(project): deprecate obsolete fields
  CHANGELOG.md
  docs/resources/project.md
  internal/sdkprovider/service/project/project.go
  internal/sdkprovider/service/project/project_test.go
Labels: enhancement

#1361 fix(kafkatopic): acc tests but reverting performance fix
  CHANGELOG.md
  internal/sdkprovider/service/kafkatopic/kafka_topic_test.go
  internal/sdkprovider/service/kafkatopic/kafka_topic_wait.go
Labels: no changelog

#1360 fix(kafkatopic): replication for startup-2 plan
  internal/sdkprovider/service/kafkatopic/kafka_topic_test.go
Labels: no changelog

#1352 chore(release): v4.9.0
  CHANGELOG.md
Labels: release

#1364 feat(pg): allow to modify user replication settings
  CHANGELOG.md
  docs/data-sources/pg_user.md
  docs/resources/pg_user.md
  internal/sdkprovider/service/pg/pg_user.go
  internal/sdkprovider/service/pg/pg_user_test.go
Labels: enhancement, skip workflows

#1365 test(kafka): fix mirrormaker invalid offset syncs topic location
  internal/sdkprovider/service/kafka/mirrormaker_replication_flow_test.go
Labels: enhancement, no changelog

#1370 fix(ci): codeql job
  .github/workflows/codeql.yml
Labels: no changelog, github_actions

#1357 feat(kafkatopic): creation simplification
  internal/sdkprovider/service/kafkatopic/kafka_topic.go
  internal/sdkprovider/service/kafkatopic/kafka_topic_cache.go
  internal/sdkprovider/service/kafkatopic/kafka_topic_create.go
Labels: no changelog

#1371 fix(project_user): invite error handling
  CHANGELOG.md
  internal/service/kafka/kafka_topic_cache_test.go
  internal/service/project/project_user.go
Labels: no changelog
