Repository aiven/terraform-provider-aiven, pull requests merged in 2024-08, with the labels that each got.

#1799 chore(release): v4.22.0
  CHANGELOG.md
Labels: release

#1806 docs: improve pg documentation
  docs/data-sources/pg.md
  docs/data-sources/pg_database.md
  docs/data-sources/pg_user.md
  docs/resources/pg.md
  docs/resources/pg_database.md
  docs/resources/pg_user.md
  examples/data-sources/aiven_pg/data-source.tf
  examples/data-sources/aiven_pg_database/data-source.tf
  examples/data-sources/aiven_pg_user/data-source.tf
  examples/resources/aiven_pg/import.sh
  examples/resources/aiven_pg/resource.tf
  examples/resources/aiven_pg_database/import.sh
  examples/resources/aiven_pg_database/resource.tf
  examples/resources/aiven_pg_user/import.sh
  examples/resources/aiven_pg_user/resource.tf
  internal/sdkprovider/service/pg/pg.go
  internal/sdkprovider/service/pg/pg_data_source.go
  internal/sdkprovider/service/pg/pg_database.go
  internal/sdkprovider/service/pg/pg_database_data_source.go
  internal/sdkprovider/service/pg/pg_user.go
  internal/sdkprovider/service/pg/pg_user_data_source.go
Labels: documentation, no changelog

#1805 docs: update additional_disk_space attribute description
  docs/data-sources/cassandra.md
  docs/data-sources/clickhouse.md
  docs/data-sources/dragonfly.md
  docs/data-sources/flink.md
  docs/data-sources/grafana.md
  docs/data-sources/kafka.md
  docs/data-sources/kafka_connect.md
  docs/data-sources/kafka_mirrormaker.md
  docs/data-sources/m3aggregator.md
  docs/data-sources/m3db.md
  docs/data-sources/mysql.md
  docs/data-sources/opensearch.md
  docs/data-sources/pg.md
  docs/data-sources/redis.md
  docs/data-sources/thanos.md
  docs/data-sources/valkey.md
  docs/resources/cassandra.md
  docs/resources/clickhouse.md
  docs/resources/dragonfly.md
  docs/resources/flink.md
  docs/resources/grafana.md
  docs/resources/kafka.md
  docs/resources/kafka_connect.md
  docs/resources/kafka_mirrormaker.md
  docs/resources/m3aggregator.md
  docs/resources/m3db.md
  docs/resources/mysql.md
  docs/resources/opensearch.md
  docs/resources/pg.md
  docs/resources/redis.md
  docs/resources/thanos.md
  docs/resources/valkey.md
  internal/schemautil/service.go
Labels: documentation, no changelog

#1814 fix: mark attributes of sensitive blocks as sensitive
  CHANGELOG.md
  docs/resources/cassandra.md
  docs/resources/clickhouse.md
  docs/resources/dragonfly.md
  docs/resources/flink.md
  docs/resources/grafana.md
  docs/resources/kafka.md
  docs/resources/m3aggregator.md
  docs/resources/m3db.md
  docs/resources/mysql.md
  docs/resources/opensearch.md
  docs/resources/pg.md
  docs/resources/redis.md
  docs/resources/thanos.md
  docs/resources/valkey.md
  internal/schemautil/service.go
  internal/sdkprovider/provider/provider.go
  internal/sdkprovider/provider/provider_test.go
  internal/sdkprovider/service/cassandra/cassandra.go
  internal/sdkprovider/service/clickhouse/clickhouse.go
  internal/sdkprovider/service/dragonfly/dragonfly.go
  internal/sdkprovider/service/flink/flink.go
  internal/sdkprovider/service/grafana/grafana.go
  internal/sdkprovider/service/influxdb/influxdb.go
  internal/sdkprovider/service/kafka/kafka.go
  internal/sdkprovider/service/m3db/m3aggregator.go
  internal/sdkprovider/service/m3db/m3db.go
  internal/sdkprovider/service/mysql/mysql.go
  internal/sdkprovider/service/opensearch/opensearch.go
  internal/sdkprovider/service/pg/pg.go
  internal/sdkprovider/service/redis/redis.go
  internal/sdkprovider/service/thanos/thanos.go
  internal/sdkprovider/service/valkey/valkey.go
  internal/server/server.go
  internal/sweep/sweep_test.go
  main.go
Labels: bug

#1815 chore(release): v4.24.0
  CHANGELOG.md
Labels: release

#1813 refactor: return plain error
  internal/common/client.go
  internal/sdkprovider/service/kafka/kafka_mirrormaker_replication_flow_data_source.go
  internal/sdkprovider/service/kafka/mirrormaker_replication_flow.go
  internal/sdkprovider/service/organization/organization_application_user.go
  internal/sdkprovider/service/organization/organization_application_user_data_source.go
  internal/sdkprovider/service/organization/organization_application_user_token.go
  internal/sdkprovider/service/valkey/valkey_user.go
  internal/sdkprovider/service/valkey/valkey_user_data_source.go
Labels: no changelog
