Repository aiven/terraform-provider-aiven, pull requests merged in 2024-02, with the labels that each got.

#1576 ci(lint): add prealloc
  .golangci.yml
  internal/schemautil/common.go
  internal/schemautil/service.go
  internal/schemautil/userconfig/util.go
  internal/sdkprovider/service/flink/flink_application_version.go
  internal/sdkprovider/service/kafka/kafka_connector.go
  internal/sdkprovider/service/kafkatopic/kafka_topic.go
  internal/sdkprovider/service/project/project.go
  internal/sdkprovider/service/vpc/aws_privatelink.go
  internal/sdkprovider/service/vpc/azure_privatelink.go
Labels: enhancement, no changelog

#1574 docs: add organizations example
  examples/account/README.md
  examples/account/accounts.tf
  examples/account/assets/accounts_modal.png
  examples/account/assets/admin_rbac.png
  examples/account/assets/dev_rbac.png
  examples/account/assets/teams.png
  examples/account/assets/unassigned_rbac.png
  examples/organization/README.md
  examples/organization/org_units_projects.tf
  examples/organization/secrets.tfvars.tmp
Labels: documentation, no changelog

#1578 ci(checkout): add missing fetch-depth
  .github/workflows/acceptance-tests.yml
  .github/workflows/examples-tests.yml
Labels: enhancement, no changelog

#1579 docs: fix links and project names
  README.md
  docs/guides/creating-static-ip-addresses.md
  docs/index.md
  examples/organization/README.md
  examples/organization/org_units_projects.tf
  examples/organization/secrets.tfvars.tmp
  internal/sdkprovider/service/kafka/kafka.go
  internal/sdkprovider/service/kafkatopic/kafka_topic.go
  internal/sdkprovider/service/vpc/azure_vpc_peering_connection_test.go
  templates/guides/creating-static-ip-addresses.md
  templates/index.md
Labels: documentation, no changelog

#1580 docs: create new get started example
  examples/get-started/README.md
  examples/get-started/get-started.tf
  examples/getting-started.tf
Labels: documentation, no changelog

#1582 docs: make deprecation warning bold
  docs/resources/organization_user.md
  internal/sdkprovider/service/organization/organization_user.go
Labels: documentation, no changelog

#1583 fix(organization_user_group): make description field required
  CHANGELOG.md
  docs/resources/organization_user_group.md
  internal/sdkprovider/service/organization/organization_user_group.go
Labels: bug

#1586 docs(security): change bugbounty provider from h1 to bugcrowd
  SECURITY.md
Labels: enhancement, documentation, no changelog

#1588 chore(go): upgrade go 1.22
  CHANGELOG.md
  CONTRIBUTING.md
  go.mod
  tools/go.mod
  tools/selproj/go.mod
Labels: enhancement

#1591 remove InfluxDB and ElasticSearch mentions from the docs
  Makefile
  docs/data-sources/influxdb.md
  docs/data-sources/influxdb_database.md
  docs/data-sources/influxdb_user.md
  docs/data-sources/service_integration.md
  docs/guides/examples.md
  docs/guides/syslog-service-integration.md
  docs/resources/influxdb.md
  docs/resources/influxdb_database.md
  docs/resources/influxdb_user.md
  docs/resources/kafka.md
  docs/resources/kafka_connector.md
  docs/resources/service_integration.md
  examples/gcp_marketplace/main.tf
  examples/kafka_connectors/mongo_sink/services.tf
  examples/kafka_connectors/os_sink/services.tf
  examples/kafka_mirrormaker/kafka.tf
  examples/kafka_mirrormaker_bidirectional/kafka.tf
  examples/kafka_mirrormaker_global/kafka.tf
  examples/kafka_prometheus/services.tf
  examples/kafka_schemas/kafka_service.tf
  examples/resources/aiven_kafka/resource.tf
  examples/resources/aiven_kafka_connector/resource.tf
  internal/sdkprovider/service/serviceintegration/service_integration_endpoint_test.go
  sample_project/outputs.tf
  sample_project/sample.tf
  templates/data-sources/service_integration.md.tmpl
  templates/guides/examples.md
  templates/guides/syslog-service-integration.md
  templates/resources/service_integration.md.tmpl
Labels: documentation, no changelog

#1598 fix: termination_protection diff `true -> null`
  CHANGELOG.md
  internal/schemautil/service.go
Labels: bug

#1599 fix(docs): fix examples list links
  docs/guides/examples.md
  templates/guides/examples.md
Labels: no changelog

#1601 docs: add teams deprecation info to relevant resources
  docs/resources/account_team.md
  docs/resources/account_team_member.md
  docs/resources/account_team_project.md
  examples/resources/aiven_account_team/resource.tf
  examples/resources/aiven_account_team_member/resource.tf
  examples/resources/aiven_account_team_project/resource.tf
  internal/sdkprovider/service/account/account_team.go
  internal/sdkprovider/service/account/account_team_member.go
  internal/sdkprovider/service/account/account_team_project.go
  templates/resources/account_team.md.tmpl
  templates/resources/account_team_member.md.tmpl
  templates/resources/account_team_project.md.tmpl
Labels: documentation, no changelog

#1604 chore(release): v4.14.0
  CHANGELOG.md
Labels: release

#1609 fix(aiven_kafka_schema): update schema version
  CHANGELOG.md
  internal/sdkprovider/service/kafkaschema/kafka_schema.go
  internal/sdkprovider/service/kafkaschema/kafka_schema_test.go
Labels: bug

#1605 refactor(aiven_service_integration): new user configs
  CHANGELOG.md
  docs/resources/service_integration.md
  internal/sdkprovider/service/serviceintegration/service_integration.go
  internal/sdkprovider/service/serviceintegration/service_integration_data_source.go
  internal/sdkprovider/userconfig/integration/clickhouse_kafka.go
  internal/sdkprovider/userconfig/integration/clickhouse_postgresql.go
  internal/sdkprovider/userconfig/integration/datadog.go
  internal/sdkprovider/userconfig/integration/external_aws_cloudwatch_metrics.go
  internal/sdkprovider/userconfig/integration/integration.go
  internal/sdkprovider/userconfig/integration/kafka_connect.go
  internal/sdkprovider/userconfig/integration/kafka_logs.go
  internal/sdkprovider/userconfig/integration/kafka_mirrormaker.go
  internal/sdkprovider/userconfig/integration/logs.go
  internal/sdkprovider/userconfig/integration/metrics.go
  main.go
Labels: enhancement

#1611 fix(flink): poll application deployment deletion
  CHANGELOG.md
  internal/plugin/util/wait.go
  internal/sdkprovider/service/flink/flink_application_deployment.go
Labels: bug

#1612 chore: remove unnecessary comment
  internal/sdkprovider/provider/provider.go
  internal/sdkprovider/service/project/project.go
Labels: enhancement, no changelog

#1614 test(flink_application_version): fix incorrect sql
  docs/resources/flink_application_version.md
  docs/resources/kafka_schema.md
  examples/flink/main.tf
  examples/kafka_schemas/kafka_schema.tf
  examples/resources/aiven_flink_application_version/resource.tf
  examples/resources/aiven_kafka_schema/resource.tf
  internal/sdkprovider/service/flink/flink_application_version_test.go
  internal/sdkprovider/service/kafkaschema/kafka_schema_test.go
Labels: enhancement, no changelog

#1615 refactor(userconfig): generate types list, rename integrations
  internal/sdkprovider/service/serviceintegration/service_integration.go
  internal/sdkprovider/userconfig/service/service.go
  internal/sdkprovider/userconfig/serviceintegration/clickhouse_kafka.go
  internal/sdkprovider/userconfig/serviceintegration/clickhouse_postgresql.go
  internal/sdkprovider/userconfig/serviceintegration/datadog.go
  internal/sdkprovider/userconfig/serviceintegration/external_aws_cloudwatch_metrics.go
  internal/sdkprovider/userconfig/serviceintegration/kafka_connect.go
  internal/sdkprovider/userconfig/serviceintegration/kafka_logs.go
  internal/sdkprovider/userconfig/serviceintegration/kafka_mirrormaker.go
  internal/sdkprovider/userconfig/serviceintegration/logs.go
  internal/sdkprovider/userconfig/serviceintegration/metrics.go
  internal/sdkprovider/userconfig/serviceintegration/serviceintegration.go
  ucgenerator/main.go
Labels: no changelog

#1620 docs: add deprecation notice to account and authentication resources
  docs/resources/account.md
  docs/resources/account_authentication.md
  internal/sdkprovider/service/account/account.go
  internal/sdkprovider/service/account/account_authentication.go
Labels: documentation, no changelog

#1625 fix(kafka_schema): protobuf normalization
  CHANGELOG.md
  internal/sdkprovider/service/kafkaschema/kafka_schema.go
Labels: bug

#1623 refactor(aiven_service_integration_endpoint): new user configs
  CHANGELOG.md
  docs/data-sources/service_integration_endpoint.md
  docs/resources/service_integration_endpoint.md
  internal/sdkprovider/service/serviceintegration/service_integration.go
  internal/sdkprovider/service/serviceintegration/service_integration_endpoint.go
  internal/sdkprovider/service/serviceintegration/service_integration_endpoint_data_source.go
  internal/sdkprovider/userconfig/serviceintegrationendpoint/datadog.go
  internal/sdkprovider/userconfig/serviceintegrationendpoint/external_aws_cloudwatch_logs.go
  internal/sdkprovider/userconfig/serviceintegrationendpoint/external_aws_cloudwatch_metrics.go
  internal/sdkprovider/userconfig/serviceintegrationendpoint/external_elasticsearch_logs.go
  internal/sdkprovider/userconfig/serviceintegrationendpoint/external_google_cloud_bigquery.go
  internal/sdkprovider/userconfig/serviceintegrationendpoint/external_google_cloud_logging.go
  internal/sdkprovider/userconfig/serviceintegrationendpoint/external_kafka.go
  internal/sdkprovider/userconfig/serviceintegrationendpoint/external_opensearch_logs.go
  internal/sdkprovider/userconfig/serviceintegrationendpoint/external_postgresql.go
  internal/sdkprovider/userconfig/serviceintegrationendpoint/external_schema_registry.go
  internal/sdkprovider/userconfig/serviceintegrationendpoint/jolokia.go
  internal/sdkprovider/userconfig/serviceintegrationendpoint/prometheus.go
  internal/sdkprovider/userconfig/serviceintegrationendpoint/rsyslog.go
  internal/sdkprovider/userconfig/serviceintegrationendpoint/serviceintegrationendpoint.go
  ucgenerator/main.go
Labels: enhancement
