Repository aiven/terraform-provider-aiven, pull requests merged in 2024-04, with the labels that each got.

#1679 chore(statechangeconf): unified delay and mintimeout values
  CHANGELOG.md
  internal/common/client.go
  internal/schemautil/database.go
  internal/schemautil/wait.go
  internal/sdkprovider/service/kafka/kafka_connector.go
  internal/sdkprovider/service/pg/pg.go
  internal/sdkprovider/service/project/project.go
  internal/sdkprovider/service/serviceintegration/service_integration.go
  internal/sdkprovider/service/staticip/static_ip.go
  internal/sdkprovider/service/vpc/aws_privatelink.go
  internal/sdkprovider/service/vpc/aws_vpc_peering_connection.go
  internal/sdkprovider/service/vpc/azure_privatelink.go
  internal/sdkprovider/service/vpc/azure_privatelink_connection_approve.go
  internal/sdkprovider/service/vpc/azure_vpc_peering_connection.go
  internal/sdkprovider/service/vpc/gcp_privatelink.go
  internal/sdkprovider/service/vpc/gcp_privatelink_connection_approve.go
  internal/sdkprovider/service/vpc/gcp_vpc_peering_connection.go
  internal/sdkprovider/service/vpc/project_vpc.go
  internal/sdkprovider/service/vpc/vpc_peering_connection.go
Labels: enhancement

#1685 ci(release-artifacts): incorrect reference in ldflags
  .goreleaser.yml
Labels: bug, no changelog

#1681 docs(kafka_schema_registry_acl): add example and import cmd
  docs/resources/kafka_schema_registry_acl.md
  examples/resources/aiven_kafka_schema_registry_acl/import.sh
  examples/resources/aiven_kafka_schema_registry_acl/resource.tf
Labels: documentation, no changelog

#1687 ci(incacctests): add sweeping functionality
  .github/workflows/incremental-acceptance-tests.yml
Labels: enhancement, no changelog

#1689 docs: update kafka and topic documentation
  docs/data-sources/kafka.md
  docs/data-sources/kafka_topic.md
  docs/resources/kafka.md
  docs/resources/kafka_topic.md
  examples/data-sources/aiven_kafka/data-source.tf
  examples/data-sources/aiven_kafka_topic/data-source.tf
  examples/resources/aiven_kafka/import.sh
  examples/resources/aiven_kafka/resource.tf
  examples/resources/aiven_kafka_topic/import.sh
  examples/resources/aiven_kafka_topic/resource.tf
  internal/sdkprovider/service/kafka/kafka.go
  internal/sdkprovider/service/kafka/kafka_data_source.go
  internal/sdkprovider/service/kafkatopic/kafka_topic.go
  internal/sdkprovider/service/kafkatopic/kafka_topic_data_source.go
Labels: documentation, no changelog

#1690 docs(userconfig): uppercase first description letter
  docs/resources/cassandra.md
  docs/resources/opensearch.md
  docs/resources/service_integration.md
  internal/sdkprovider/userconfig/service/cassandra.go
  internal/sdkprovider/userconfig/service/opensearch.go
  internal/sdkprovider/userconfig/serviceintegration/metrics.go
  internal/sdkprovider/userconfig/serviceintegration/prometheus.go
  ucgenerator/main.go
Labels: no changelog

#1680 docs(service_integrations): update
  docs/data-sources/service_integration.md
  docs/resources/service_integration.md
  examples/data-sources/aiven_service_integration/data-source.tf
  examples/resources/aiven_service_integration/import.sh
  examples/resources/aiven_service_integration/resource.tf
  internal/sdkprovider/service/serviceintegration/service_integration.go
  internal/sdkprovider/service/serviceintegration/service_integration_data_source.go
  templates/data-sources/service_integration.md.tmpl
  templates/resources/service_integration.md.tmpl
Labels: documentation, no changelog

#1691 fix(kafka_topic): send false values
  CHANGELOG.md
  internal/sdkprovider/service/kafkatopic/kafka_topic.go
Labels: bug

#1692 feat(aiven_kafka_topic): validate conflict on plan
  CHANGELOG.md
  internal/sdkprovider/kafkatopicrepository/read.go
  internal/sdkprovider/kafkatopicrepository/repository.go
  internal/sdkprovider/service/kafkatopic/kafka_topic.go
  internal/sdkprovider/service/kafkatopic/kafka_topic_test.go
Labels: enhancement

#1699 chore: remove generic service connection info
  CHANGELOG.md
  internal/schemautil/service.go
Labels: no changelog

#1701 feat(userconfigs): add map type support
  internal/sdkprovider/userconfig/converters/converters.go
  internal/sdkprovider/userconfig/service/kafka.go
  internal/sdkprovider/userconfig/service/service.go
  internal/sdkprovider/userconfig/service/thanos.go
  ucgenerator/main.go
  ucgenerator/models.go
Labels: enhancement, no changelog

#1700 chore: remove redundant service connection info
  CHANGELOG.md
  docs/data-sources/cassandra.md
  docs/data-sources/clickhouse.md
  docs/data-sources/dragonfly.md
  docs/data-sources/grafana.md
  docs/data-sources/kafka_connect.md
  docs/data-sources/kafka_mirrormaker.md
  docs/data-sources/m3aggregator.md
  docs/data-sources/m3db.md
  docs/data-sources/mysql.md
  docs/data-sources/redis.md
  docs/resources/cassandra.md
  docs/resources/clickhouse.md
  docs/resources/dragonfly.md
  docs/resources/grafana.md
  docs/resources/kafka_connect.md
  docs/resources/kafka_mirrormaker.md
  docs/resources/m3aggregator.md
  docs/resources/m3db.md
  docs/resources/mysql.md
  docs/resources/redis.md
  internal/schemautil/service.go
  internal/sdkprovider/service/cassandra/cassandra.go
  internal/sdkprovider/service/clickhouse/clickhouse.go
  internal/sdkprovider/service/dragonfly/dragonfly.go
  internal/sdkprovider/service/grafana/grafana.go
  internal/sdkprovider/service/kafka/kafka_connect.go
  internal/sdkprovider/service/kafka/kafka_mirrormaker.go
  internal/sdkprovider/service/m3db/m3aggregator.go
  internal/sdkprovider/service/m3db/m3db.go
  internal/sdkprovider/service/mysql/mysql.go
  internal/sdkprovider/service/redis/redis.go
Labels: enhancement

#1705 ci(incacctest): different running approach
  .github/workflows/incremental-acceptance-tests.yml
Labels: enhancement, no changelog

#1706 ci(incacctest): add result job
  .github/workflows/incremental-acceptance-tests.yml
Labels: enhancement, no changelog

#1707 feat(userconfigs): expand maps
  CHANGELOG.md
  docs/resources/kafka.md
  docs/resources/kafka_connect.md
  docs/resources/pg.md
  docs/resources/service_integration_endpoint.md
  internal/sdkprovider/userconfig/converters/converters.go
  internal/sdkprovider/userconfig/converters/utils.go
  internal/sdkprovider/userconfig/converters/utils_test.go
  internal/sdkprovider/userconfig/diff/diff.go
  internal/sdkprovider/userconfig/service/kafka.go
  internal/sdkprovider/userconfig/service/kafka_connect.go
  internal/sdkprovider/userconfig/service/pg.go
  internal/sdkprovider/userconfig/service/service.go
  internal/sdkprovider/userconfig/serviceintegration/serviceintegration.go
  internal/sdkprovider/userconfig/serviceintegrationendpoint/external_google_cloud_bigquery.go
  internal/sdkprovider/userconfig/serviceintegrationendpoint/external_google_cloud_logging.go
  internal/sdkprovider/userconfig/serviceintegrationendpoint/serviceintegrationendpoint.go
  ucgenerator/main.go
  ucgenerator/models.go
Labels: enhancement, no changelog

#1702 feat: thanos support
  .github/workflows/incremental-acceptance-tests.yml
  CHANGELOG.md
  Makefile
  docs/data-sources/thanos.md
  docs/resources/thanos.md
  go.mod
  go.sum
  internal/schemautil/service.go
  internal/sdkprovider/provider/provider.go
  internal/sdkprovider/service/thanos/sweep.go
  internal/sdkprovider/service/thanos/thanos.go
  internal/sdkprovider/service/thanos/thanos_data_source.go
  internal/sdkprovider/service/thanos/thanos_test.go
  internal/sdkprovider/userconfig/service/service.go
  internal/sdkprovider/userconfig/service/thanos.go
Labels: enhancement

#1712 chore(release): v4.16.0
  CHANGELOG.md
Labels: release
