Repository aiven/terraform-provider-aiven, pull requests merged in 2024-09, with the labels that each got.

#1825 chore: disable project user tests
  internal/sdkprovider/service/project/project_user_data_source_test.go
  internal/sdkprovider/service/project/project_user_test.go
Labels: no changelog

#1836 Fix typo in service schema
  docs/data-sources/cassandra.md
  docs/data-sources/clickhouse.md
  docs/data-sources/dragonfly.md
  docs/data-sources/flink.md
  docs/data-sources/grafana.md
  docs/data-sources/kafka.md
  docs/data-sources/kafka_connect.md
  docs/data-sources/kafka_mirrormaker.md
  docs/data-sources/m3aggregator.md
  docs/data-sources/m3db.md
  docs/data-sources/mysql.md
  docs/data-sources/opensearch.md
  docs/data-sources/pg.md
  docs/data-sources/redis.md
  docs/data-sources/thanos.md
  docs/data-sources/valkey.md
  docs/resources/cassandra.md
  docs/resources/clickhouse.md
  docs/resources/dragonfly.md
  docs/resources/flink.md
  docs/resources/grafana.md
  docs/resources/kafka.md
  docs/resources/kafka_connect.md
  docs/resources/kafka_mirrormaker.md
  docs/resources/m3aggregator.md
  docs/resources/m3db.md
  docs/resources/mysql.md
  docs/resources/opensearch.md
  docs/resources/pg.md
  docs/resources/redis.md
  docs/resources/thanos.md
  docs/resources/valkey.md
  internal/schemautil/service.go
Labels: no changelog

#1834 refactor: unify clients configuration
  examples_tests/base.go
  internal/acctest/acctest.go
  internal/common/client.go
  internal/common/client_test.go
  internal/plugin/provider.go
  internal/schemautil/common.go
  internal/sdkprovider/provider/provider.go
Labels: no changelog

#1827 docs: update get started example
  examples/get-started/README.md
  examples/get-started/get-started.tf
Labels: documentation, no changelog

#1840 docs(pg): clarify pg_user documentation
  docs/data-sources/pg_user.md
  docs/resources/pg_user.md
  examples/resources/aiven_pg_user/resource.tf
  internal/sdkprovider/service/pg/pg_user.go
Labels: documentation, no changelog

#1838 feat: check user config for redacted creds
  internal/schemautil/service.go
  internal/schemautil/service_test.go
  internal/sdkprovider/service/serviceintegration/service_integration_endpoint.go
Labels: no changelog

#1821 docs: improve M3, Grafana, connection pools
  docs/data-sources/connection_pool.md
  docs/data-sources/grafana.md
  docs/data-sources/m3db.md
  docs/data-sources/m3db_user.md
  docs/resources/connection_pool.md
  docs/resources/grafana.md
  docs/resources/m3db.md
  docs/resources/m3db_user.md
  examples/data-sources/aiven_connection_pool/data-source.tf
  examples/data-sources/aiven_grafana/data-source.tf
  examples/data-sources/aiven_m3db/data-source.tf
  examples/data-sources/aiven_m3db_user/data-source.tf
  examples/resources/aiven_connection_pool/import.sh
  examples/resources/aiven_connection_pool/resource.tf
  examples/resources/aiven_grafana/import.sh
  examples/resources/aiven_grafana/resource.tf
  examples/resources/aiven_m3db/import.sh
  examples/resources/aiven_m3db/resource.tf
  examples/resources/aiven_m3db_user/import.sh
  examples/resources/aiven_m3db_user/resource.tf
  internal/sdkprovider/service/connectionpool/connection_pool.go
  internal/sdkprovider/service/connectionpool/connection_pool_data_source.go
  internal/sdkprovider/service/grafana/grafana.go
  internal/sdkprovider/service/grafana/grafana_data_source.go
  internal/sdkprovider/service/m3db/m3db.go
  internal/sdkprovider/service/m3db/m3db_data_source.go
  internal/sdkprovider/service/m3db/m3db_user.go
  internal/sdkprovider/service/m3db/m3db_user_data_source.go
Labels: documentation, no changelog

#1844 chore: use service module from the gen client
  go.mod
  go.sum
  internal/sdkprovider/service/serviceintegration/service_integration.go
  internal/sdkprovider/service/serviceintegration/service_integration_endpoint.go
Labels: no changelog

#1847 chore(release): v4.25.0
  CHANGELOG.md
Labels: release

#1852 docs(permission): add example usage
  docs/resources/organization_permission.md
  examples/resources/aiven_organization_permission/import.sh
  examples/resources/aiven_organization_permission/resource.tf
  internal/sdkprovider/service/organization/organization_permission.go
Labels: documentation, no changelog

#1854 chore(release): v4.26.0
  CHANGELOG.md
Labels: release

#1855 fix: add version to .goreleaser.yml
  .goreleaser.yml
Labels: no changelog
