Repository aiven/terraform-provider-aiven, pull requests merged in 2024-01, with the labels that each got.

#1498 chore(changelog): 4.11.0 release notes
  CHANGELOG.md
Labels: release

#1501 fix(kafka_topic): insufficient brokers error
  CHANGELOG.md
  internal/sdkprovider/kafkatopicrepository/create.go
Labels: bug

#1499 feat(kafkatopic): tiered storage support
  CHANGELOG.md
  docs/data-sources/kafka_topic.md
  docs/resources/kafka_topic.md
  go.mod
  go.sum
  internal/sdkprovider/service/kafkatopic/kafka_topic.go
Labels: enhancement

#1503 chore(release): v4.12.0
  CHANGELOG.md
Labels: release

#1504 docs(kafkatopic): return dot instead of underscore
  docs/resources/kafka_topic.md
  internal/sdkprovider/service/kafkatopic/kafka_topic.go
Labels: documentation, no changelog

#1511 fix(kafkatopic): temporarily disable local_retention_* fields
  CHANGELOG.md
  docs/resources/kafka_topic.md
  go.mod
  go.sum
  internal/sdkprovider/service/kafkatopic/kafka_topic.go
Labels: bug

#1512 revert: add connection poll sweeper
  internal/sdkprovider/service/connectionpool/sweep.go
Labels: no changelog

#1510 feat(sweep): connection pool support
  internal/sdkprovider/service/connectionpool/sweep.go
Labels: enhancement, no changelog

#1518 refactor: deduplicate beta checks
  internal/acctest/acctest.go
  internal/plugin/provider.go
  internal/plugin/service/organization/organization_application_user_test.go
  internal/plugin/service/organization/organization_group_project_test.go
  internal/plugin/service/organization/organization_user_group_member_test.go
  internal/plugin/util/helpers.go
Labels: enhancement, no changelog

#1520 refactor(acctest): skip option support
  internal/acctest/acctest.go
  internal/plugin/service/organization/organization_application_user_test.go
  internal/plugin/service/organization/organization_group_project_test.go
  internal/plugin/service/organization/organization_user_group_member_test.go
Labels: enhancement, no changelog

#1521 fix(kafka_topic): config optional fields
  CHANGELOG.md
  go.mod
  go.sum
  internal/sdkprovider/service/kafkatopic/kafka_topic.go
  internal/sdkprovider/service/kafkatopic/kafka_topic_test.go
Labels: bug

#1525 test: add sweepers for organization resources
  internal/common/error.go
  internal/schemautil/database.go
  internal/schemautil/service_user.go
  internal/schemautil/wait.go
  internal/sdkprovider/service/account/account_authentication.go
  internal/sdkprovider/service/account/account_team.go
  internal/sdkprovider/service/account/account_team_member.go
  internal/sdkprovider/service/account/account_team_project.go
  internal/sdkprovider/service/clickhouse/clickhouse_user.go
  internal/sdkprovider/service/connectionpool/connection_pool.go
  internal/sdkprovider/service/connectionpool/sweep.go
  internal/sdkprovider/service/flink/flink_application.go
  internal/sdkprovider/service/flink/flink_application_version_test.go
  internal/sdkprovider/service/kafka/kafka_acl.go
  internal/sdkprovider/service/kafka/kafka_connector.go
  internal/sdkprovider/service/kafka/kafka_test.go
  internal/sdkprovider/service/kafkaschema/kafka_schema.go
  internal/sdkprovider/service/kafkaschema/kafka_schema_registry_acl.go
  internal/sdkprovider/service/opensearch/opensearch_user.go
  internal/sdkprovider/service/organization/organization_user.go
  internal/sdkprovider/service/organization/sweep.go
  internal/sdkprovider/service/project/billing_group.go
  internal/sdkprovider/service/project/billing_group_test.go
  internal/sdkprovider/service/project/project_user.go
  internal/sdkprovider/service/serviceintegration/service_integration.go
  internal/sdkprovider/service/serviceintegration/service_integration_endpoint.go
  internal/sdkprovider/service/serviceintegration/service_integration_test.go
  internal/sdkprovider/service/serviceintegration/sweep.go
  internal/sdkprovider/service/staticip/static_ip.go
  internal/sdkprovider/service/staticip/sweep.go
  internal/sdkprovider/service/vpc/aws_privatelink.go
  internal/sdkprovider/service/vpc/aws_vpc_peering_connection.go
  internal/sdkprovider/service/vpc/azure_privatelink.go
  internal/sdkprovider/service/vpc/azure_privatelink_test.go
  internal/sdkprovider/service/vpc/azure_vpc_peering_connection.go
  internal/sdkprovider/service/vpc/gcp_privatelink.go
  internal/sdkprovider/service/vpc/gcp_privatelink_test.go
  internal/sdkprovider/service/vpc/gcp_vpc_peering_connection.go
  internal/sdkprovider/service/vpc/sweep.go
  internal/sweep/sweep.go
  internal/sweep/sweep_test.go
Labels: enhancement, no changelog

#1527 docs: rewrite descriptions for groups resources
  docs/data-sources/organization_user_group.md
  docs/resources/organization_group_project.md
  docs/resources/organization_user_group.md
  docs/resources/organization_user_group_member.md
  internal/plugin/service/organization/organization_group_project.go
  internal/plugin/service/organization/organization_user_group_member.go
  internal/sdkprovider/service/organization/organization_user_group.go
  internal/sdkprovider/service/organization/organization_user_group_data_source.go
Labels: documentation, no changelog

#1522 feat(organization): application user tokens support
  CHANGELOG.md
  docs/resources/organization_application_user_token.md
  docs/resources/organization_user_group_member.md
  internal/plugin/errmsg/errmsg.go
  internal/plugin/provider.go
  internal/plugin/service/organization/organization_application_user.go
  internal/plugin/service/organization/organization_application_user_data_source.go
  internal/plugin/service/organization/organization_application_user_test.go
  internal/plugin/service/organization/organization_application_user_token.go
  internal/plugin/service/organization/organization_user_group_member.go
  internal/plugin/service/organization/organization_user_group_member_test.go
  internal/plugin/util/diag.go
  internal/plugin/util/helpers.go
  internal/plugin/util/pluginhelpers.go
  internal/schemautil/plugin.go
Labels: enhancement

#1529 test: enable vpc sweepers
  internal/sdkprovider/service/vpc/sweep.go
  internal/sweep/sweep_test.go
Labels: enhancement, no changelog

#1526 chore(vpc): fix tests conflict
  internal/sdkprovider/service/vpc/project_vpc_test.go
  tools/selproj/client.go
  tools/selproj/mock_client.go
  tools/selproj/selectproject.go
  tools/selproj/selectproject_test.go
Labels: no changelog

#1530 chore(kafka_topic): improve config zero-value test
  internal/sdkprovider/service/kafkatopic/kafka_topic_test.go
Labels: no changelog

#1531 chore(imports): improve regexp
  Makefile
  internal/schemautil/database.go
  internal/schemautil/service_user.go
  internal/schemautil/wait.go
  internal/sdkprovider/service/organization/organization_user_data_source.go
  internal/sdkprovider/service/organization/sweep.go
Labels: no changelog

#1533 chore(release): v4.13.0
  CHANGELOG.md
Labels: release

#1539 test: add sweepers check
  Makefile
  internal/sdkprovider/service/account/sweep.go
  internal/sdkprovider/service/cassandra/sweep.go
  internal/sdkprovider/service/clickhouse/sweep.go
  internal/sdkprovider/service/connectionpool/sweep.go
  internal/sdkprovider/service/flink/sweep.go
  internal/sdkprovider/service/grafana/sweep.go
  internal/sdkprovider/service/influxdb/sweep.go
  internal/sdkprovider/service/kafka/sweep.go
  internal/sdkprovider/service/m3db/sweep.go
  internal/sdkprovider/service/mysql/sweep.go
  internal/sdkprovider/service/opensearch/sweep.go
  internal/sdkprovider/service/organization/sweep.go
  internal/sdkprovider/service/pg/sweep.go
  internal/sdkprovider/service/project/sweep.go
  internal/sdkprovider/service/redis/sweep.go
  internal/sdkprovider/service/serviceintegration/sweep.go
  internal/sdkprovider/service/staticip/sweep.go
  internal/sdkprovider/service/vpc/sweep.go
  internal/sweep/sweep.go
  internal/sweep/sweep_test.go
Labels: enhancement, no changelog

#1542 ci: add sweep check
  .github/workflows/lint.yml
  Makefile
  internal/sdkprovider/service/account/sweep.go
  internal/sdkprovider/service/connectionpool/sweep.go
  internal/sdkprovider/service/organization/sweep.go
  internal/sdkprovider/service/project/sweep.go
  internal/sdkprovider/service/serviceintegration/sweep.go
  internal/sdkprovider/service/staticip/sweep.go
  internal/sdkprovider/service/vpc/sweep.go
  internal/sweep/sweep.go
  internal/sweep/sweep_test.go
Labels: enhancement, no changelog

#1546 fix(org): org user and group member model fill
  CHANGELOG.md
  internal/plugin/service/organization/organization_application_user.go
  internal/plugin/service/organization/organization_user_group_member.go
Labels: bug

#1547 docs(kafka_topic): fix local_retention field desc
  docs/resources/kafka_topic.md
  internal/sdkprovider/service/kafkatopic/kafka_topic.go
Labels: documentation, no changelog

#1550 feat(flink): add pre deletion check
  CHANGELOG.md
  internal/sdkprovider/service/flink/flink.go
Labels: enhancement

#1562 docs: update app users description
  docs/resources/organization_application_user.md
  internal/plugin/service/organization/organization_application_user.go
Labels: documentation, no changelog

#1557 docs: improve descriptions for billing groups
  docs/data-sources/billing_group.md
  docs/resources/billing_group.md
  internal/sdkprovider/service/project/billing_group.go
  internal/sdkprovider/service/project/billing_group_data_source.go
Labels: documentation, no changelog

#1561 ci(lint): add errorlint
  .golangci.yml
  internal/schemautil/service.go
  internal/sdkprovider/kafkatopicrepository/create.go
  internal/sdkprovider/kafkatopicrepository/create_test.go
  internal/sdkprovider/kafkatopicrepository/read.go
  internal/sdkprovider/kafkatopicrepository/repository_test.go
  internal/sdkprovider/service/account/account_team_member_test.go
  internal/sdkprovider/service/account/account_team_project_test.go
  internal/sdkprovider/service/account/account_team_test.go
  internal/sdkprovider/service/account/account_test.go
  internal/sdkprovider/service/account/sweep.go
  internal/sdkprovider/service/cassandra/cassandra_user_test.go
  internal/sdkprovider/service/clickhouse/clickhouse_user_test.go
  internal/sdkprovider/service/clickhouse/role.go
  internal/sdkprovider/service/connectionpool/connection_pool_test.go
  internal/sdkprovider/service/influxdb/influxdb_database_test.go
  internal/sdkprovider/service/influxdb/influxdb_user_test.go
  internal/sdkprovider/service/kafka/kafka_acl_test.go
  internal/sdkprovider/service/kafka/kafka_connector_test.go
  internal/sdkprovider/service/kafka/kafka_test.go
  internal/sdkprovider/service/kafka/kafka_user_test.go
  internal/sdkprovider/service/kafka/mirrormaker_replication_flow_test.go
  internal/sdkprovider/service/kafkaschema/kafka_schema_registry_acl_test.go
  internal/sdkprovider/service/kafkaschema/kafka_schema_test.go
  internal/sdkprovider/service/m3db/m3db_user_test.go
  internal/sdkprovider/service/mysql/mysql_database_test.go
  internal/sdkprovider/service/mysql/mysql_user_test.go
  internal/sdkprovider/service/opensearch/opensearch_acl_config_test.go
  internal/sdkprovider/service/opensearch/opensearch_acl_rule_test.go
  internal/sdkprovider/service/opensearch/opensearch_user.go
  internal/sdkprovider/service/opensearch/opensearch_user_test.go
  internal/sdkprovider/service/organization/organization_user_group_test.go
  internal/sdkprovider/service/organization/organization_user_test.go
  internal/sdkprovider/service/pg/pg_database_test.go
  internal/sdkprovider/service/pg/pg_test.go
  internal/sdkprovider/service/pg/pg_user_test.go
  internal/sdkprovider/service/project/billing_group_test.go
  internal/sdkprovider/service/project/project.go
  internal/sdkprovider/service/project/project_test.go
  internal/sdkprovider/service/project/project_user.go
  internal/sdkprovider/service/project/project_user_test.go
  internal/sdkprovider/service/project/sweep.go
  internal/sdkprovider/service/redis/redis_user_test.go
  internal/sdkprovider/service/serviceintegration/service_integration.go
  internal/sdkprovider/service/serviceintegration/service_integration_endpoint_test.go
  internal/sdkprovider/service/serviceintegration/sweep.go
  internal/sdkprovider/service/staticip/static_ip.go
  internal/sdkprovider/service/vpc/azure_privatelink_test.go
  internal/sdkprovider/service/vpc/gcp_privatelink_test.go
  internal/sdkprovider/service/vpc/project_vpc.go
  internal/sdkprovider/service/vpc/project_vpc_test.go
  internal/sdkprovider/service/vpc/sweep.go
  internal/sdkprovider/service/vpc/vpc_peering_connection.go
  internal/sweep/sweep.go
Labels: no changelog

#1514 docs: update flink_application_version docs
  CHANGELOG.md
  docs/resources/flink_application_version.md
  examples/resources/aiven_flink_application_version/resource.tf
Labels: documentation

#1563 chore(changelog): fix typo
  CHANGELOG.md
Labels: documentation, no changelog, skip workflows

#1569 fix(kafkaschema): diff suppress json object, acceptance tests
  CHANGELOG.md
  internal/schemautil/service.go
  internal/sdkprovider/service/account/account_team_member_test.go
  internal/sdkprovider/service/account/account_team_project_test.go
  internal/sdkprovider/service/account/account_team_test.go
  internal/sdkprovider/service/account/account_test.go
  internal/sdkprovider/service/account/sweep.go
  internal/sdkprovider/service/cassandra/cassandra_user_test.go
  internal/sdkprovider/service/clickhouse/clickhouse_user_test.go
  internal/sdkprovider/service/clickhouse/role.go
  internal/sdkprovider/service/connectionpool/connection_pool_test.go
  internal/sdkprovider/service/influxdb/influxdb_database_test.go
  internal/sdkprovider/service/influxdb/influxdb_user_test.go
  internal/sdkprovider/service/kafka/kafka_acl_test.go
  internal/sdkprovider/service/kafka/kafka_connector_test.go
  internal/sdkprovider/service/kafka/kafka_user_test.go
  internal/sdkprovider/service/kafka/mirrormaker_replication_flow_test.go
  internal/sdkprovider/service/kafkaschema/kafka_schema.go
  internal/sdkprovider/service/kafkaschema/kafka_schema_registry_acl_test.go
  internal/sdkprovider/service/kafkaschema/kafka_schema_test.go
  internal/sdkprovider/service/m3db/m3db_user_test.go
  internal/sdkprovider/service/mysql/mysql_database_test.go
  internal/sdkprovider/service/mysql/mysql_user_test.go
  internal/sdkprovider/service/opensearch/opensearch_acl_config_test.go
  internal/sdkprovider/service/opensearch/opensearch_acl_rule_test.go
  internal/sdkprovider/service/opensearch/opensearch_user.go
  internal/sdkprovider/service/opensearch/opensearch_user_test.go
  internal/sdkprovider/service/organization/organization_user_group_test.go
  internal/sdkprovider/service/organization/organization_user_test.go
  internal/sdkprovider/service/pg/pg_database_test.go
  internal/sdkprovider/service/pg/pg_user_test.go
  internal/sdkprovider/service/project/billing_group_test.go
  internal/sdkprovider/service/project/project.go
  internal/sdkprovider/service/project/project_test.go
  internal/sdkprovider/service/project/project_user.go
  internal/sdkprovider/service/project/project_user_test.go
  internal/sdkprovider/service/project/sweep.go
  internal/sdkprovider/service/redis/redis_user_test.go
  internal/sdkprovider/service/serviceintegration/service_integration_endpoint_test.go
  internal/sdkprovider/service/vpc/azure_privatelink_test.go
  internal/sdkprovider/service/vpc/gcp_privatelink_test.go
  internal/sdkprovider/service/vpc/project_vpc.go
  internal/sdkprovider/service/vpc/project_vpc_test.go
Labels: bug
