Repository aiven/terraform-provider-aiven, pull requests merged in 2024-03, with the labels that each got.

#1631 ci(selproj): add setup-go step
  .github/workflows/acceptance-tests.yml
  .github/workflows/examples-tests.yml
Labels: enhancement, no changelog

#1635 fix: require explicit flag to purge ip_filter
  internal/sdkprovider/userconfig/converters/converters.go
Labels: bug, no changelog

#1641 chore(userconfig/converters): improve ip_filter safeguard
  CHANGELOG.md
  internal/sdkprovider/userconfig/converters/converters.go
Labels: enhancement

#1644 fix(userconfig/converters): missing negation in ip_filter safeguard
  internal/sdkprovider/userconfig/converters/converters.go
Labels: bug, no changelog

#1648 feat(userconfig/desc): add entity and availability types
  docs/resources/organization_application_user.md
  docs/resources/organization_application_user_token.md
  docs/resources/organization_group_project.md
  docs/resources/organization_user_group_member.md
  internal/plugin/service/organization/organization_application_user.go
  internal/plugin/service/organization/organization_application_user_token.go
  internal/plugin/service/organization/organization_group_project.go
  internal/plugin/service/organization/organization_user_group_member.go
  internal/schemautil/userconfig/desc.go
  internal/sdkprovider/service/organization/organization_user_data_source.go
Labels: enhancement, no changelog

#1642 docs: update org units resource and data source
  docs/data-sources/organizational_unit.md
  docs/resources/organizational_unit.md
  examples/data-sources/aiven_organizational_unit/data-source.tf
  examples/resources/aiven_organizational_unit/import.sh
  examples/resources/aiven_organizational_unit/resource.tf
  internal/sdkprovider/service/organization/organizational_unit.go
  internal/sdkprovider/service/organization/organizational_unit_data_source.go
Labels: documentation, no changelog

#1654 docs: add environment variables to main page
  docs/index.md
  templates/index.md
Labels: documentation, no changelog

#1647 fix(ip_filter_object): use set type
  CHANGELOG.md
  docs/data-sources/cassandra.md
  docs/data-sources/clickhouse.md
  docs/data-sources/flink.md
  docs/data-sources/grafana.md
  docs/data-sources/kafka.md
  docs/data-sources/kafka_connect.md
  docs/data-sources/kafka_mirrormaker.md
  docs/data-sources/m3aggregator.md
  docs/data-sources/m3db.md
  docs/data-sources/mysql.md
  docs/data-sources/opensearch.md
  docs/data-sources/pg.md
  docs/data-sources/redis.md
  docs/resources/cassandra.md
  docs/resources/clickhouse.md
  docs/resources/flink.md
  docs/resources/grafana.md
  docs/resources/kafka.md
  docs/resources/kafka_connect.md
  docs/resources/kafka_mirrormaker.md
  docs/resources/m3aggregator.md
  docs/resources/m3db.md
  docs/resources/mysql.md
  docs/resources/opensearch.md
  docs/resources/pg.md
  docs/resources/redis.md
  internal/sdkprovider/service/grafana/grafana_test.go
  internal/sdkprovider/userconfig/converters/converters.go
  internal/sdkprovider/userconfig/converters/utils.go
  internal/sdkprovider/userconfig/diff/diff.go
  internal/sdkprovider/userconfig/service/cassandra.go
  internal/sdkprovider/userconfig/service/clickhouse.go
  internal/sdkprovider/userconfig/service/flink.go
  internal/sdkprovider/userconfig/service/grafana.go
  internal/sdkprovider/userconfig/service/influxdb.go
  internal/sdkprovider/userconfig/service/kafka.go
  internal/sdkprovider/userconfig/service/kafka_connect.go
  internal/sdkprovider/userconfig/service/kafka_mirrormaker.go
  internal/sdkprovider/userconfig/service/m3aggregator.go
  internal/sdkprovider/userconfig/service/m3db.go
  internal/sdkprovider/userconfig/service/mysql.go
  internal/sdkprovider/userconfig/service/opensearch.go
  internal/sdkprovider/userconfig/service/pg.go
  internal/sdkprovider/userconfig/service/redis.go
  ucgenerator/main.go
Labels: bug, enhancement

#1651 fix(mirrormaker_replication_flow): incorrect behavior of schema fields
  CHANGELOG.md
  docs/resources/mirrormaker_replication_flow.md
  go.mod
  go.sum
  internal/sdkprovider/service/kafka/mirrormaker_replication_flow.go
Labels: bug

#1650 fix(aiven_service_integration_endpoint): can't create external_postgresql
  CHANGELOG.md
  internal/schemautil/service.go
  internal/sdkprovider/service/cassandra/cassandra.go
  internal/sdkprovider/service/clickhouse/clickhouse.go
  internal/sdkprovider/service/dragonfly/dragonfly.go
  internal/sdkprovider/service/flink/flink.go
  internal/sdkprovider/service/grafana/grafana.go
  internal/sdkprovider/service/influxdb/influxdb.go
  internal/sdkprovider/service/kafka/kafka.go
  internal/sdkprovider/service/kafka/kafka_connect.go
  internal/sdkprovider/service/kafka/kafka_mirrormaker.go
  internal/sdkprovider/service/m3db/m3aggregator.go
  internal/sdkprovider/service/m3db/m3db.go
  internal/sdkprovider/service/mysql/mysql.go
  internal/sdkprovider/service/opensearch/opensearch.go
  internal/sdkprovider/service/pg/pg.go
  internal/sdkprovider/service/redis/redis.go
  internal/sdkprovider/service/serviceintegration/service_integration.go
  internal/sdkprovider/service/serviceintegration/service_integration_endpoint.go
  internal/sdkprovider/service/serviceintegration/service_integration_endpoint_test.go
  internal/sdkprovider/userconfig/converters/converters.go
Labels: bug

#1629 chore: release dragonfly
  CHANGELOG.md
  docs/data-sources/dragonfly.md
  docs/resources/dragonfly.md
  internal/sdkprovider/provider/provider.go
  internal/sdkprovider/service/dragonfly/dragonfly_test.go
  internal/sdkprovider/userconfig/service/dragonfly.go
  internal/sdkprovider/userconfig/service/service.go
  main.go
Labels: enhancement

#1626 test(acctest): incremental run support
  .github/workflows/incremental-acceptance-tests.yml
Labels: enhancement, no changelog

#1658 refactor: encapsulate user config checks
  internal/sdkprovider/service/serviceintegration/service_integration.go
  internal/sdkprovider/userconfig/converters/converters.go
  internal/sdkprovider/userconfig/service/service.go
  internal/sdkprovider/userconfig/serviceintegration/serviceintegration.go
  internal/sdkprovider/userconfig/serviceintegrationendpoint/serviceintegrationendpoint.go
  main.go
  ucgenerator/main.go
Labels: no changelog

#1661 refactor(userconfig): remove old user config files
  internal/plugin/util/helpers.go
  internal/plugin/util/pluginhelpers.go
  internal/schemautil/mutations.go
  internal/schemautil/mutations_test.go
  internal/schemautil/schemautil.go
  internal/schemautil/schemautil_test.go
  internal/schemautil/userconfig/.gitignore
  internal/schemautil/userconfig/apiconvert/fromapi.go
  internal/schemautil/userconfig/apiconvert/fromapi_test.go
  internal/schemautil/userconfig/apiconvert/toapi.go
  internal/schemautil/userconfig/apiconvert/toapi_test.go
  internal/schemautil/userconfig/apiconvert/util.go
  internal/schemautil/userconfig/apiconvert/util_test.go
  internal/schemautil/userconfig/const.go
  internal/schemautil/userconfig/convert.go
  internal/schemautil/userconfig/dist/integration_endpoint_types.go
  internal/schemautil/userconfig/dist/integration_types.go
  internal/schemautil/userconfig/dist/service_types.go
  internal/schemautil/userconfig/handle.go
  internal/schemautil/userconfig/userconfig_test.go
  internal/schemautil/userconfig/util.go
Labels: no changelog

#1662 refactor: mark user_group_member and group_project as ga
  CHANGELOG.md
  docs/resources/organization_group_project.md
  docs/resources/organization_user_group_member.md
  internal/plugin/provider.go
  internal/plugin/service/organization/organization_group_project.go
  internal/plugin/service/organization/organization_user_group_member.go
Labels: enhancement

#1668 chore(release): v4.15.0
  CHANGELOG.md
Labels: release

#1671 docs: update dragonfly and add example
  docs/data-sources/dragonfly.md
  docs/resources/dragonfly.md
  examples/data-sources/aiven_dragonfly/data-source.tf
  examples/dragonfly/provider.tf
  examples/dragonfly/service.tf
  examples/dragonfly/variables.tf
  examples/resources/aiven_dragonfly/import.sh
  examples/resources/aiven_dragonfly/resource.tf
  internal/sdkprovider/service/dragonfly/dragonfly.go
  internal/sdkprovider/service/dragonfly/dragonfly_data_source.go
Labels: documentation, no changelog

#1639 docs: add LA note and update app users
  docs/data-sources/organization_application_user.md
  docs/resources/organization_application_user.md
  docs/resources/organization_application_user_token.md
  examples/data-sources/aiven_organization_application_user/data-source.tf
  examples/resources/aiven_organization_application_user/import.sh
  examples/resources/aiven_organization_application_user/resource.tf
  examples/resources/aiven_organization_application_user_token/import.sh
  examples/resources/aiven_organization_application_user_token/resource.tf
  internal/plugin/service/organization/organization_application_user.go
  internal/plugin/service/organization/organization_application_user_data_source.go
  internal/plugin/service/organization/organization_application_user_token.go
  internal/schemautil/userconfig/desc.go
Labels: documentation, no changelog

#1673 docs: remove duplicate example usage
  docs/resources/organization_group_project.md
  examples/resources/aiven_organization_group_project/resource copy.tf
  examples/resources/aiven_organization_group_project/resource.tf
Labels: documentation, no changelog

#1674 docs: update project and billing group resources
  docs/data-sources/billing_group.md
  docs/data-sources/cassandra.md
  docs/data-sources/clickhouse.md
  docs/data-sources/dragonfly.md
  docs/data-sources/flink.md
  docs/data-sources/grafana.md
  docs/data-sources/kafka.md
  docs/data-sources/kafka_connect.md
  docs/data-sources/kafka_mirrormaker.md
  docs/data-sources/m3aggregator.md
  docs/data-sources/m3db.md
  docs/data-sources/mysql.md
  docs/data-sources/opensearch.md
  docs/data-sources/pg.md
  docs/data-sources/project.md
  docs/data-sources/redis.md
  docs/resources/billing_group.md
  docs/resources/cassandra.md
  docs/resources/clickhouse.md
  docs/resources/dragonfly.md
  docs/resources/flink.md
  docs/resources/grafana.md
  docs/resources/kafka.md
  docs/resources/kafka_connect.md
  docs/resources/kafka_mirrormaker.md
  docs/resources/m3aggregator.md
  docs/resources/m3db.md
  docs/resources/mysql.md
  docs/resources/opensearch.md
  docs/resources/organization_group_project.md
  docs/resources/pg.md
  docs/resources/project.md
  docs/resources/redis.md
  examples/data-sources/aiven_billing_group/data-source.tf
  examples/data-sources/aiven_project/data-source.tf
  examples/resources/aiven_billing_group/import.sh
  examples/resources/aiven_billing_group/resource.tf
  examples/resources/aiven_organization_group_project/resource.tf
  examples/resources/aiven_project/import.sh
  examples/resources/aiven_project/resource.tf
  internal/schemautil/service.go
  internal/sdkprovider/service/project/billing_group.go
  internal/sdkprovider/service/project/billing_group_data_source.go
  internal/sdkprovider/service/project/project.go
  internal/sdkprovider/service/project/project_data_source.go
Labels: documentation, no changelog

#1677 ci(dependabot): run on weekly basis
  .github/dependabot.yml
Labels: enhancement, no changelog
