Repository aiven/terraform-provider-aiven, pull requests merged in 2024-12, with the labels that each got.

#1928 fix(service_integration): remove v2 client checks
  internal/sdkprovider/service/serviceintegration/service_integration.go
  internal/sdkprovider/service/serviceintegration/service_integration_endpoint_test.go
  internal/sdkprovider/service/serviceintegration/sweep.go
Labels: no changelog

#1929 chore(release): v4.30.0
  CHANGELOG.md
  internal/sdkprovider/service/kafka/kafka_native_acl.go
Labels: release

#1930 refactor(organization_user_group): replaced client-v2 with avngen
  internal/sdkprovider/service/organization/organization_user_group.go
  internal/sdkprovider/service/organization/organization_user_group_data_source.go
  internal/sdkprovider/service/organization/organization_user_group_test.go
Labels: no changelog

#1934 fix: make fmt-imports
  Makefile
  internal/sdkprovider/service/organization/organization_user_group_data_source.go
Labels: no changelog

#1932 refactor(organization_user): replaced client-v2 with avngen
  internal/sdkprovider/service/organization/organization_user.go
  internal/sdkprovider/service/organization/organization_user_data_source.go
  internal/sdkprovider/service/organization/organization_user_data_source_test.go
  internal/sdkprovider/service/organization/organization_user_test.go
Labels: no changelog

#1931 docs: update Kafka ACL docs
  docs/resources/kafka_acl.md
  docs/resources/kafka_native_acl.md
  examples/resources/aiven_kafka_native_acl/import.sh
  examples/resources/aiven_kafka_native_acl/resource.tf
  internal/sdkprovider/service/kafka/kafka_acl.go
  internal/sdkprovider/service/kafka/kafka_native_acl.go
Labels: documentation, no changelog

#1940 refactor(organizational_unit): replaced client-v2 with avngen
  internal/schemautil/helpers.go
  internal/schemautil/helpers_test.go
  internal/sdkprovider/service/organization/organizational_unit.go
  internal/sdkprovider/service/organization/organizational_unit_data_source.go
  internal/sdkprovider/service/organization/organizational_unit_test.go
  internal/sdkprovider/service/project/billing_group.go
  internal/sdkprovider/service/project/project.go
  internal/sdkprovider/service/project/util.go
Labels: no changelog

#1933 docs: add org level permissions example
  docs/resources/organization_permission.md
  examples/resources/aiven_organization_permission/resource.tf
  internal/sdkprovider/service/organization/organization_permission.go
Labels: documentation, no changelog

#1950 chore(release): v4.31.0
  CHANGELOG.md
  docs/resources/alloydbomni.md
  examples/resources/aiven_alloydbomni/import.sh
  examples/resources/aiven_alloydbomni/resource.tf
  go.mod
  go.sum
  internal/sdkprovider/service/serviceintegration/service_integration.go
Labels: release

#1954 docs: fix typo in guide
  docs/guides/update-deprecated-resources.md
  templates/guides/update-deprecated-resources.md
Labels: documentation, no changelog

#1966 refactor(account_team): replaced client-v2 with avngen
  .golangci.yml
  internal/sdkprovider/service/account/account_team.go
  internal/sdkprovider/service/account/account_team_data_source.go
  internal/sdkprovider/service/account/account_team_test.go
Labels: no changelog

#1963 refactor(account_team_member): replaced client-v2 with avngen
  internal/sdkprovider/service/account/account_team_member.go
  internal/sdkprovider/service/account/account_team_member_data_source.go
  internal/sdkprovider/service/account/account_team_member_test.go
Labels: no changelog

#1965 refactor(account): replaced client-v2 with avngen
  internal/sdkprovider/service/account/account.go
  internal/sdkprovider/service/account/account_data_source.go
  internal/sdkprovider/service/account/account_test.go
Labels: no changelog
