Repository aiven/terraform-provider-aiven, pull requests merged in 2024-05, with the labels that each got.

#1713 fix(kafka_connector): ignore 201 create error
  CHANGELOG.md
  internal/sdkprovider/service/kafka/kafka_connector.go
Labels: bug

#1714 feat: remove beta flag from app users and tokens
  CHANGELOG.md
  docs/resources/organization_application_user.md
  docs/resources/organization_application_user_token.md
  internal/plugin/provider.go
  internal/plugin/service/organization/organization_application_user.go
  internal/plugin/service/organization/organization_application_user_token.go
Labels: enhancement

#1719 chore(release): v4.17.0
  CHANGELOG.md
Labels: release

#1720 docs: add frontmatter to docs homepage
  docs/index.md
  templates/index.md
Labels: documentation, no changelog

#1721 fix: convert ip_filter values into the target type
  CHANGELOG.md
  internal/sdkprovider/userconfig/converters/converters.go
  internal/sdkprovider/userconfig/converters/utils.go
  internal/sdkprovider/userconfig/converters/utils_test.go
Labels: bug

#1725 chore(incacctests): temporarily disable
  .github/workflows/incremental-acceptance-tests.yml
Labels: enhancement, no changelog

#1722 docs(mirromaker): added valid options for config
  docs/data-sources/mirrormaker_replication_flow.md
  docs/resources/mirrormaker_replication_flow.md
  internal/sdkprovider/service/kafka/mirrormaker_replication_flow.go
Labels: no changelog

#1726 feat: add missing connection info to various service types
  .github/workflows/acceptance-tests.yml
  CHANGELOG.md
  docs/data-sources/cassandra.md
  docs/data-sources/clickhouse.md
  docs/data-sources/dragonfly.md
  docs/data-sources/flink.md
  docs/data-sources/grafana.md
  docs/data-sources/kafka.md
  docs/data-sources/m3aggregator.md
  docs/data-sources/m3db.md
  docs/data-sources/mysql.md
  docs/data-sources/opensearch.md
  docs/data-sources/pg.md
  docs/data-sources/redis.md
  docs/data-sources/thanos.md
  docs/resources/cassandra.md
  docs/resources/clickhouse.md
  docs/resources/dragonfly.md
  docs/resources/grafana.md
  docs/resources/kafka.md
  docs/resources/m3aggregator.md
  docs/resources/m3db.md
  docs/resources/mysql.md
  docs/resources/opensearch.md
  docs/resources/pg.md
  docs/resources/redis.md
  docs/resources/thanos.md
  go.mod
  go.sum
  internal/schemautil/service.go
  internal/sdkprovider/service/cassandra/cassandra.go
  internal/sdkprovider/service/cassandra/cassandra_test.go
  internal/sdkprovider/service/clickhouse/clickhouse.go
  internal/sdkprovider/service/clickhouse/clickhouse_test.go
  internal/sdkprovider/service/dragonfly/dragonfly.go
  internal/sdkprovider/service/dragonfly/dragonfly_test.go
  internal/sdkprovider/service/flink/flink.go
  internal/sdkprovider/service/flink/flink_test.go
  internal/sdkprovider/service/grafana/grafana.go
  internal/sdkprovider/service/grafana/grafana_test.go
  internal/sdkprovider/service/influxdb/influxdb.go
  internal/sdkprovider/service/influxdb/influxdb_user_test.go
  internal/sdkprovider/service/kafka/kafka.go
  internal/sdkprovider/service/kafka/kafka_test.go
  internal/sdkprovider/service/m3db/m3aggregator.go
  internal/sdkprovider/service/m3db/m3aggregator_test.go
  internal/sdkprovider/service/m3db/m3db.go
  internal/sdkprovider/service/m3db/m3db_test.go
  internal/sdkprovider/service/mysql/mysql.go
  internal/sdkprovider/service/mysql/mysql_test.go
  internal/sdkprovider/service/opensearch/opensearch.go
  internal/sdkprovider/service/opensearch/opensearch_test.go
  internal/sdkprovider/service/pg/pg.go
  internal/sdkprovider/service/pg/pg_test.go
  internal/sdkprovider/service/redis/redis.go
  internal/sdkprovider/service/redis/redis_test.go
  internal/sdkprovider/service/thanos/thanos.go
  internal/sdkprovider/service/thanos/thanos_test.go
Labels: enhancement

#1733 docs: add enum values
  docs/resources/cassandra.md
  docs/resources/dragonfly.md
  docs/resources/flink.md
  docs/resources/grafana.md
  docs/resources/kafka.md
  docs/resources/kafka_connect.md
  docs/resources/m3aggregator.md
  docs/resources/m3db.md
  docs/resources/mysql.md
  docs/resources/opensearch.md
  docs/resources/pg.md
  docs/resources/redis.md
  docs/resources/service_integration.md
  docs/resources/service_integration_endpoint.md
  internal/sdkprovider/userconfig/service/cassandra.go
  internal/sdkprovider/userconfig/service/dragonfly.go
  internal/sdkprovider/userconfig/service/flink.go
  internal/sdkprovider/userconfig/service/grafana.go
  internal/sdkprovider/userconfig/service/kafka.go
  internal/sdkprovider/userconfig/service/kafka_connect.go
  internal/sdkprovider/userconfig/service/m3aggregator.go
  internal/sdkprovider/userconfig/service/m3db.go
  internal/sdkprovider/userconfig/service/mysql.go
  internal/sdkprovider/userconfig/service/opensearch.go
  internal/sdkprovider/userconfig/service/pg.go
  internal/sdkprovider/userconfig/service/redis.go
  internal/sdkprovider/userconfig/serviceintegration/clickhouse_kafka.go
  internal/sdkprovider/userconfig/serviceintegration/external_aws_cloudwatch_logs.go
  internal/sdkprovider/userconfig/serviceintegration/external_elasticsearch_logs.go
  internal/sdkprovider/userconfig/serviceintegration/external_opensearch_logs.go
  internal/sdkprovider/userconfig/serviceintegration/kafka_logs.go
  internal/sdkprovider/userconfig/serviceintegration/kafka_mirrormaker.go
  internal/sdkprovider/userconfig/serviceintegration/logs.go
  internal/sdkprovider/userconfig/serviceintegrationendpoint/datadog.go
  internal/sdkprovider/userconfig/serviceintegrationendpoint/external_kafka.go
  internal/sdkprovider/userconfig/serviceintegrationendpoint/external_postgresql.go
  internal/sdkprovider/userconfig/serviceintegrationendpoint/external_schema_registry.go
  internal/sdkprovider/userconfig/serviceintegrationendpoint/rsyslog.go
  ucgenerator/main.go
  ucgenerator/models.go
Labels: no changelog

#1732 chore(release): v4.18.0
  CHANGELOG.md
Labels: release

#1742 chore(release): v4.19.0
  CHANGELOG.md
Labels: release
