Repository aiven/terraform-provider-aiven, pull requests merged in 2024-06, with the labels that each got.

#1748 chore(ci): remove deprecated gorelease args and options
  .github/workflows/release-artifacts.yml
  .goreleaser.yml
Labels: no changelog

#1747 chore(release): v4.19.1
  CHANGELOG.md
Labels: release

#1761 docs: fix broken links to conceptual docs
  docs/data-sources/project.md
  docs/resources/organization.md
  docs/resources/organization_group_project.md
  docs/resources/organization_user_group.md
  docs/resources/organization_user_group_member.md
  docs/resources/organizational_unit.md
  docs/resources/project.md
  examples/organization/README.md
  internal/plugin/service/organization/organization_group_project.go
  internal/plugin/service/organization/organization_resource.go
  internal/plugin/service/organization/organization_user_group_member.go
  internal/sdkprovider/service/organization/organization_user_group.go
  internal/sdkprovider/service/organization/organizational_unit.go
  internal/sdkprovider/service/project/project.go
Labels: documentation, no changelog

#1753 docs(clickhouse): update clickhouse examples to align with docs
  examples/clickhouse/services.tf
  examples/clickhouse_integrations/kafka_source/access.tf
Labels: enhancement, no changelog

#1757 fix(organization_user_group): make name field required
  CHANGELOG.md
  docs/resources/organization_user_group.md
  internal/sdkprovider/service/organization/organization_user_group.go
Labels: bug

#1743 docs: add example values
  docs/resources/cassandra.md
  docs/resources/clickhouse.md
  docs/resources/dragonfly.md
  docs/resources/flink.md
  docs/resources/grafana.md
  docs/resources/kafka.md
  docs/resources/kafka_connect.md
  docs/resources/kafka_mirrormaker.md
  docs/resources/m3aggregator.md
  docs/resources/m3db.md
  docs/resources/mysql.md
  docs/resources/opensearch.md
  docs/resources/pg.md
  docs/resources/redis.md
  docs/resources/service_integration.md
  docs/resources/service_integration_endpoint.md
  docs/resources/thanos.md
  internal/sdkprovider/userconfig/service/cassandra.go
  internal/sdkprovider/userconfig/service/clickhouse.go
  internal/sdkprovider/userconfig/service/dragonfly.go
  internal/sdkprovider/userconfig/service/flink.go
  internal/sdkprovider/userconfig/service/grafana.go
  internal/sdkprovider/userconfig/service/influxdb.go
  internal/sdkprovider/userconfig/service/kafka.go
  internal/sdkprovider/userconfig/service/kafka_connect.go
  internal/sdkprovider/userconfig/service/kafka_mirrormaker.go
  internal/sdkprovider/userconfig/service/m3aggregator.go
  internal/sdkprovider/userconfig/service/m3db.go
  internal/sdkprovider/userconfig/service/mysql.go
  internal/sdkprovider/userconfig/service/opensearch.go
  internal/sdkprovider/userconfig/service/pg.go
  internal/sdkprovider/userconfig/service/redis.go
  internal/sdkprovider/userconfig/service/thanos.go
  internal/sdkprovider/userconfig/serviceintegration/clickhouse_kafka.go
  internal/sdkprovider/userconfig/serviceintegration/clickhouse_postgresql.go
  internal/sdkprovider/userconfig/serviceintegration/datadog.go
  internal/sdkprovider/userconfig/serviceintegration/external_aws_cloudwatch_metrics.go
  internal/sdkprovider/userconfig/serviceintegration/kafka_connect.go
  internal/sdkprovider/userconfig/serviceintegration/kafka_logs.go
  internal/sdkprovider/userconfig/serviceintegration/kafka_mirrormaker.go
  internal/sdkprovider/userconfig/serviceintegration/logs.go
  internal/sdkprovider/userconfig/serviceintegration/metrics.go
  internal/sdkprovider/userconfig/serviceintegration/prometheus.go
  internal/sdkprovider/userconfig/serviceintegrationendpoint/datadog.go
  internal/sdkprovider/userconfig/serviceintegrationendpoint/external_aws_cloudwatch_logs.go
  internal/sdkprovider/userconfig/serviceintegrationendpoint/external_aws_cloudwatch_metrics.go
  internal/sdkprovider/userconfig/serviceintegrationendpoint/external_elasticsearch_logs.go
  internal/sdkprovider/userconfig/serviceintegrationendpoint/external_google_cloud_bigquery.go
  internal/sdkprovider/userconfig/serviceintegrationendpoint/external_google_cloud_logging.go
  internal/sdkprovider/userconfig/serviceintegrationendpoint/external_kafka.go
  internal/sdkprovider/userconfig/serviceintegrationendpoint/external_opensearch_logs.go
  internal/sdkprovider/userconfig/serviceintegrationendpoint/external_postgresql.go
  internal/sdkprovider/userconfig/serviceintegrationendpoint/external_schema_registry.go
  internal/sdkprovider/userconfig/serviceintegrationendpoint/jolokia.go
  internal/sdkprovider/userconfig/serviceintegrationendpoint/prometheus.go
  internal/sdkprovider/userconfig/serviceintegrationendpoint/rsyslog.go
  ucgenerator/main.go
  ucgenerator/models.go
Labels: no changelog

#1768 chore: skip account team tests
  internal/sdkprovider/service/account/account_team_data_source_test.go
  internal/sdkprovider/service/account/account_team_member_data_source_test.go
  internal/sdkprovider/service/account/account_team_member_test.go
  internal/sdkprovider/service/account/account_team_project_test.go
  internal/sdkprovider/service/account/account_team_test.go
Labels: no changelog

#1770 docs: update deprecation information for account_authentication resource
  docs/resources/account_authentication.md
  internal/sdkprovider/service/account/account_authentication.go
  templates/resources/account_authentication.md.tmpl
Labels: documentation, no changelog

#1774 fix(tests): ssl_mode is required
  internal/sdkprovider/service/serviceintegration/service_integration_endpoint_test.go
Labels: no changelog

#1776 chore(release): v4.20.0
  CHANGELOG.md
Labels: release
