Repository aiven/terraform-provider-aiven, pull requests merged in 2025-05, with the labels that each got.

#2197 feat: add state to expandData
  docs/data-sources/organization_address.md
  docs/data-sources/organization_billing_group.md
  docs/resources/organization_address.md
  docs/resources/organization_billing_group.md
  internal/plugin/service/organization/address/address.go
  internal/plugin/service/organization/address/address_test.go
  internal/plugin/service/organization/address/zz_converters.go
  internal/plugin/service/organization/address/zz_datasource.go
  internal/plugin/service/organization/address/zz_resource.go
  internal/plugin/service/organization/billinggroup/billing_group.go
  internal/plugin/service/organization/billinggroup/zz_converters.go
  internal/plugin/service/organization/billinggroup/zz_datasource.go
  internal/plugin/service/organization/billinggroup/zz_resource.go
  internal/plugin/service/organization/billinggrouplist/zz_converters.go
  internal/plugin/service/organization/organization/organization.go
  internal/plugin/service/organization/organization/zz_converters.go
  internal/plugin/util/converters.go
Labels: no changelog

#2201 chore(go): upgraded mockery to v3
  .mockery.yml
  go.mod
  go.sum
  mocks/client.go
  mocks/resourcedata.go
Labels: no changelog

#2195 docs: move guides to TF docs
  docs/guides/creating-static-ip-addresses.md
  docs/guides/importing-resources.md
  docs/guides/manage-read-replicas.md
  docs/guides/syslog-service-integration.md
  docs/guides/upgrade-guide-v1-to-v2.md
  docs/guides/upgrade-guide-v2-to-v3.md
  docs/guides/upgrade-guide-v3-to-v4.md
  docs/guides/upgrade-guide-version_1_2_4.md
  docs/guides/use-pg-provider-for-config.md
  templates/guides/creating-static-ip-addresses.md
  templates/guides/importing-resources.md
  templates/guides/manage-read-replicas.md
  templates/guides/syslog-service-integration.md
  templates/guides/upgrade-guide-v1-to-v2.md
  templates/guides/upgrade-guide-v2-to-v3.md
  templates/guides/upgrade-guide-v3-to-v4.md
  templates/guides/upgrade-guide-version_1_2_4.md
  templates/guides/use-pg-provider-for-config.md
Labels: documentation, no changelog

#2202 refactor(organization_project): generate resource
  changelog/differ_test.go
  docs/data-sources/organization_project.md
  docs/resources/organization_project.md
  go.mod
  go.sum
  internal/acctest/template/field_extractor_test.go
  internal/acctest/template/generator_framework_test.go
  internal/acctest/template/generator_sdk_test.go
  internal/acctest/template/store_test.go
  internal/plugin/provider.go
  internal/plugin/service/organization/project/project.go
  internal/plugin/service/organization/project/project_test.go
  internal/plugin/service/organization/project/zz_converters.go
  internal/plugin/service/organization/project/zz_datasource.go
  internal/plugin/service/organization/project/zz_resource.go
  internal/schemautil/helpers.go
  internal/schemautil/helpers_test.go
  internal/schemautil/wait.go
  internal/sdkprovider/kafkatopicrepository/create_test.go
  internal/sdkprovider/kafkatopicrepository/delete_test.go
  internal/sdkprovider/provider/provider.go
  internal/sdkprovider/service/kafkatopic/kafka_topic_test.go
  internal/sdkprovider/service/organization/organization_project.go
  internal/sdkprovider/service/organization/organization_project_data_source.go
  internal/sdkprovider/service/vpc/org_vpc_peering_connection_test.go
  internal/sdkprovider/userconfig/converters/converters_test.go
  mocks/client.go
Labels: no changelog

#2207 refactor: unify provider data casting
  internal/plugin/adapter/datasource.go
  internal/plugin/adapter/resource.go
  internal/plugin/provider.go
  internal/plugin/providerdata/provider_data.go
  internal/plugin/service/externalidentity/external_identity_data_source.go
  internal/plugin/service/organization/groupproject/organization_group_project.go
  internal/plugin/service/organization/usergroupmember/organization_user_group_member.go
  internal/plugin/types/provider_data.go
Labels: no changelog

#2214 docs(clickhouse): add instructions for granting global privileges
  docs/resources/clickhouse_grant.md
  examples/resources/aiven_clickhouse_grant/resource.tf
  internal/sdkprovider/service/clickhouse/clickhouse_grant.go
Labels: documentation, no changelog

#2216 docs: make warning about permissions and deprecated project resources…
  docs/guides/update-deprecated-resources.md
  templates/guides/update-deprecated-resources.md
Labels: documentation, no changelog

#2218 chore(release): v4.40.0
  CHANGELOG.md
Labels: release

#2220 chore(make): dropped Makefile
  .golangci.yml
  CONTRIBUTING.md
  Makefile
  Taskfile.dist.yml
  changelog/main.go
  examples_tests/base.go
  internal/acctest/template/store_test.go
  internal/common/client.go
  internal/schemautil/helpers_test.go
  internal/schemautil/schema_converter_test.go
  internal/schemautil/service_user.go
  internal/schemautil/userconfig/stateupgrader/v0/m3/m3aggregator.go
  internal/sdkprovider/kafkatopicrepository/create.go
  internal/sdkprovider/kafkatopicrepository/read.go
  internal/sdkprovider/provider/provider_test.go
  internal/sdkprovider/service/account/account.go
  internal/sdkprovider/service/account/account_team_data_source.go
  internal/sdkprovider/service/account/sweep.go
  internal/sdkprovider/service/alloydbomni/service_account_credentials_validator.go
  internal/sdkprovider/service/clickhouse/clickhouse_database_test.go
  internal/sdkprovider/service/clickhouse/escape.go
  internal/sdkprovider/service/connectionpool/sweep.go
  internal/sdkprovider/service/flink/flink_jar_application_version.go
  internal/sdkprovider/service/governance/governance_access_test.go
  internal/sdkprovider/service/kafka/kafka.go
  internal/sdkprovider/service/kafka/kafka_acl_cache.go
  internal/sdkprovider/service/kafka/kafka_connector.go
  internal/sdkprovider/service/kafka/kafka_mirrormaker.go
  internal/sdkprovider/service/kafka/kafka_quota.go
  internal/sdkprovider/service/kafkaschema/kafka_schema.go
  internal/sdkprovider/service/kafkatopic/kafka_topic.go
  internal/sdkprovider/service/m3db/m3aggregator.go
  internal/sdkprovider/service/m3db/m3db.go
  internal/sdkprovider/service/mysql/mysql.go
  internal/sdkprovider/service/opensearch/common.go
  internal/sdkprovider/service/organization/organization_user.go
  internal/sdkprovider/service/organization/organizational_unit.go
  internal/sdkprovider/service/servicecomponent/service_component_data_source.go
  internal/sdkprovider/service/staticip/sweep.go
  internal/sdkprovider/service/valkey/valkey_user.go
  internal/sdkprovider/service/vpc/aws_privatelink.go
  internal/sdkprovider/service/vpc/azure_privatelink.go
  internal/sdkprovider/service/vpc/azure_privatelink_connection_approve.go
  internal/sdkprovider/service/vpc/gcp_privatelink.go
  internal/sdkprovider/service/vpc/gcp_privatelink_connection_approve.go
  internal/sdkprovider/service/vpc/transit_gateway_vpc_attachment.go
  internal/sdkprovider/service/vpc/vpc_peering_connection_state.go
  internal/sdkprovider/userconfig/converters/converters.go
  internal/sdkprovider/userconfig/converters/utils_test.go
  internal/sweep/sweep.go
  ucgenerator/main.go
Labels: no changelog

#2221 refactor: improve naming in generated files
  internal/acctest/template/store_test.go
  internal/plugin/adapter/common.go
  internal/plugin/adapter/datasource.go
  internal/plugin/adapter/resource.go
  internal/plugin/provider.go
  internal/plugin/service/externalidentity/external_identity_data_source.go
  internal/plugin/service/organization/address/address.go
  internal/plugin/service/organization/address/zz_converters.go
  internal/plugin/service/organization/address/zz_datasource.go
  internal/plugin/service/organization/address/zz_resource.go
  internal/plugin/service/organization/billinggroup/billing_group.go
  internal/plugin/service/organization/billinggroup/zz_converters.go
  internal/plugin/service/organization/billinggroup/zz_datasource.go
  internal/plugin/service/organization/billinggroup/zz_resource.go
  internal/plugin/service/organization/billinggrouplist/billing_group_list.go
  internal/plugin/service/organization/billinggrouplist/zz_converters.go
  internal/plugin/service/organization/billinggrouplist/zz_datasource.go
  internal/plugin/service/organization/groupproject/organization_group_project.go
  internal/plugin/service/organization/organization/organization.go
  internal/plugin/service/organization/organization/zz_converters.go
  internal/plugin/service/organization/organization/zz_datasource.go
  internal/plugin/service/organization/organization/zz_resource.go
  internal/plugin/service/organization/project/project.go
  internal/plugin/service/organization/project/zz_converters.go
  internal/plugin/service/organization/project/zz_datasource.go
  internal/plugin/service/organization/project/zz_resource.go
  internal/plugin/service/organization/usergroupmember/organization_user_group_member.go
Labels: no changelog

#2222 refactor: generate docs with provider-name flag
  TaskInternal.yml
Labels: no changelog

#2224 chore(tests): fixed example tests
  Taskfile.dist.yml
  examples/mysql/output.tf
  examples/mysql/variables.tf
  examples_tests/base.go
  examples_tests/mysql_test.go
Labels: no changelog

#2227 feat: add plugin generator
  TaskInternal.yml
  Taskfile.dist.yml
  definitions/.schema.yml
  definitions/governance_access.yml
  definitions/organization.yml
  definitions/organization_address.yml
  definitions/organization_billing_group.yml
  definitions/organization_billing_group_list.yml
  definitions/organization_project.yml
  generators/changelog/differ.go
  generators/changelog/differ_test.go
  generators/changelog/formatter.go
  generators/changelog/formatter_test.go
  generators/changelog/main.go
  generators/changelog/text.go
  generators/changelog/types.go
  generators/plugin/constants.go
  generators/plugin/expand.go
  generators/plugin/flatten.go
  generators/plugin/item.go
  generators/plugin/main.go
  generators/plugin/models.go
  generators/plugin/openapi.go
  generators/plugin/patching.go
  generators/plugin/schemas.go
  generators/plugin/utils.go
  generators/plugin/validators.go
  generators/userconfig/main.go
  generators/userconfig/models.go
  internal/plugin/service/governance/access/zz_converters.go
  internal/plugin/service/organization/address/zz_converters.go
  internal/plugin/service/organization/billinggroup/zz_converters.go
  internal/plugin/service/organization/organization/organization_test.go
  internal/plugin/service/organization/organization/zz_converters.go
  internal/plugin/service/organization/project/project_test.go
  internal/plugin/service/organization/project/zz_converters.go
  internal/plugin/service/organization/usergroupmember/organization_user_group_member_test.go
  internal/sdkprovider/service/alloydbomni/alloydbomni_test.go
  internal/sdkprovider/service/governance/governance_access_test.go
  internal/sdkprovider/service/organization/organization_permission.go
  internal/sdkprovider/service/organization/organization_permission_test.go
  internal/sdkprovider/service/pg/pg_test.go
  internal/sdkprovider/service/pg/pg_user_test.go
  internal/sdkprovider/service/serviceintegration/service_integration_test.go
  main.go
Labels: no changelog

#2232 docs: fix example usage for aiven_organization_project
  docs/resources/organization_project.md
  examples/resources/aiven_organization_project/resource.tf
Labels: documentation, no changelog
