Repository aiven/terraform-provider-aiven, pull requests merged in 2025-01, with the labels that each got.

#1970 refactor(account_authentication): replaced client-v2 with avngen
  internal/plugin/util/helpers.go
  internal/sdkprovider/service/account/account_authentication.go
  internal/sdkprovider/service/account/account_authentication_data_source.go
Labels: no changelog

#1973 fix(gh_actions): removed duplicated workflows in GitHub Actions
  .github/workflows/changelog-enforcer.yml
  .github/workflows/codeql.yml
  .github/workflows/dependency-review.yml
  .github/workflows/incremental-acceptance-tests.yml
  .github/workflows/lint.yml
  .github/workflows/unit-tests.yml
Labels: no changelog

#1968 refactor(account_team_project): replaced client-v2 with avngen
  internal/sdkprovider/service/account/account_team_project.go
  internal/sdkprovider/service/account/account_team_project_data_source.go
  internal/sdkprovider/service/account/account_team_project_test.go
Labels: no changelog

#1980 feat(kafka_quota): changed request_percentage field to float type
  internal/plugin/util/helpers.go
  internal/sdkprovider/service/account/account.go
  internal/sdkprovider/service/account/account_authentication.go
  internal/sdkprovider/service/kafka/kafka_quota.go
  internal/sdkprovider/service/kafka/kafka_quota_test.go
Labels: no changelog

#1983 feat(kafka_quota): added retries to kafka_quota resource
  internal/sdkprovider/service/kafka/kafka_quota.go
  internal/sdkprovider/service/kafka/kafka_quota_test.go
Labels: no changelog

#1991 chore(release): v4.32.0
  CHANGELOG.md
Labels: release

#1995 docs: update user group member resource description
  docs/resources/organization_user_group_member.md
  internal/plugin/service/organization/organization_user_group_member.go
Labels: documentation, no changelog

#1999 chore(release): v4.33.0
  CHANGELOG.md
Labels: release

#2006 fix: missing mockery tool
  Makefile
Labels: no changelog

#2000 refactor: use ResourceData interface
  internal/schemautil/common.go
  internal/schemautil/resourcedata.go
  internal/schemautil/schemautil.go
  internal/schemautil/service.go
  internal/schemautil/static_ips.go
  internal/schemautil/wait.go
  internal/sdkprovider/userconfig/converters/converters.go
  internal/sdkprovider/userconfig/converters/utils.go
  internal/sdkprovider/userconfig/converters/utils_test.go
  mocks/resourcedata.go
Labels: no changelog

#2013 docs: update description for max_age_seconds for application tokens
  docs/resources/organization_application_user_token.md
  internal/sdkprovider/service/organization/organization_application_user_token.go
Labels: documentation, no changelog

#2005 fix: services always created in the default VPC
  CHANGELOG.md
  internal/sdkprovider/service/grafana/grafana_test.go
Labels: bug

#2012 docs: add eol notice to redis resources
  docs/resources/redis.md
  docs/resources/redis_user.md
  internal/sdkprovider/service/redis/redis.go
  internal/sdkprovider/service/redis/redis_user.go
  templates/resources/redis.md.tmpl
  templates/resources/redis_user.md.tmpl
Labels: documentation, no changelog

#2020 docs: update mirrormaker documentation
  docs/data-sources/kafka_mirrormaker.md
  docs/data-sources/mirrormaker_replication_flow.md
  docs/resources/kafka_mirrormaker.md
  docs/resources/mirrormaker_replication_flow.md
  examples/data-sources/aiven_kafka_mirrormaker/data-source.tf
  examples/data-sources/aiven_mirrormaker_replication_flow/data-source.tf
  examples/resources/aiven_kafka_mirrormaker/import.sh
  examples/resources/aiven_kafka_mirrormaker/resource.tf
  examples/resources/aiven_mirrormaker_replication_flow/import.sh
  examples/resources/aiven_mirrormaker_replication_flow/resource.tf
  internal/sdkprovider/service/kafka/kafka_mirrormaker.go
  internal/sdkprovider/service/kafka/kafka_mirrormaker_data_source.go
  internal/sdkprovider/service/kafka/kafka_mirrormaker_replication_flow_data_source.go
  internal/sdkprovider/service/kafka/mirrormaker_replication_flow.go
Labels: documentation, no changelog

#2018 docs: add EOL notice and migration guide for M3DB
  docs/guides/update-deprecated-resources.md
  docs/resources/m3db.md
  docs/resources/m3db_user.md
  internal/sdkprovider/service/m3db/m3db.go
  internal/sdkprovider/service/m3db/m3db_user.go
  templates/guides/update-deprecated-resources.md
  templates/resources/m3db.md.tmpl
  templates/resources/m3db_user.md.tmpl
Labels: documentation, no changelog

#2024 ci: remove caching action
  .github/workflows/acceptance-tests.yml
Labels: no changelog, github_actions

#2023 chore(release): v4.34.0
  CHANGELOG.md
  docs/data-sources/account_team_project.md
  docs/data-sources/connection_pool.md
  docs/data-sources/mysql_user.md
  docs/data-sources/opensearch_acl_rule.md
  docs/data-sources/service_component.md
  docs/data-sources/valkey.md
  docs/resources/account_team_project.md
  docs/resources/connection_pool.md
  docs/resources/kafka_topic.md
  docs/resources/mysql_user.md
  docs/resources/opensearch_acl_rule.md
  docs/resources/organization_group_project.md
  docs/resources/organization_permission.md
  docs/resources/valkey.md
  go.mod
  go.sum
  internal/sdkprovider/userconfig/service/valkey.go
  mocks/client.go
  mocks/resourcedata.go
Labels: release
