Repository aiven/terraform-provider-aiven, pull requests merged in 2025-02, with the labels that each got.

#2039 fix(aiven_organization_user_group): fixed resource import
  internal/sdkprovider/service/organization/organization_user_group.go
  internal/sdkprovider/service/organization/organization_user_group_test.go
Labels: no changelog

#2032 docs(cassandra): add EOL notice to Cassandra resources
  docs/resources/cassandra.md
  docs/resources/cassandra_user.md
  internal/sdkprovider/service/cassandra/cassandra.go
  internal/sdkprovider/service/cassandra/cassandra_user.go
  templates/resources/cassandra.md.tmpl
  templates/resources/cassandra_user.md.tmpl
Labels: documentation, no changelog

#2021 docs: update descriptions for mysql resources and data sources
  docs/data-sources/mysql.md
  docs/data-sources/mysql_database.md
  docs/data-sources/mysql_user.md
  docs/resources/mysql.md
  docs/resources/mysql_database.md
  docs/resources/mysql_user.md
  examples/data-sources/aiven_mysql/data-source.tf
  examples/data-sources/aiven_mysql_database/data-source.tf
  examples/data-sources/aiven_mysql_user/data-source.tf
  examples/resources/aiven_mysql/import.sh
  examples/resources/aiven_mysql/resource.tf
  examples/resources/aiven_mysql_database/import.sh
  examples/resources/aiven_mysql_database/resource.tf
  examples/resources/aiven_mysql_user/resource.tf
  internal/sdkprovider/service/mysql/mysql.go
  internal/sdkprovider/service/mysql/mysql_data_source.go
  internal/sdkprovider/service/mysql/mysql_database.go
  internal/sdkprovider/service/mysql/mysql_database_data_source.go
  internal/sdkprovider/service/mysql/mysql_user.go
  internal/sdkprovider/service/mysql/mysql_user_data_source.go
Labels: documentation, no changelog

#2049 chore(release): v4.34.2
  CHANGELOG.md
  docs/resources/opensearch.md
  go.mod
  go.sum
  internal/sdkprovider/userconfig/service/opensearch.go
  mocks/client.go
  mocks/resourcedata.go
Labels: release

#2052 fix(service_integration): type `clickhouse_kafka` crashes
  CHANGELOG.md
  internal/sdkprovider/service/serviceintegration/service_integration_test.go
  internal/sdkprovider/userconfig/diff/diff.go
Labels: bug

#2050 fix: formatting for deprecation callouts
  docs/data-sources/account.md
  docs/data-sources/account_authentication.md
  docs/data-sources/organization_user.md
  docs/data-sources/project_user.md
  docs/resources/account.md
  docs/resources/account_authentication.md
  docs/resources/organization_user.md
  docs/resources/project_user.md
  internal/sdkprovider/provider/provider.go
  internal/sdkprovider/service/organization/organization_user.go
  internal/sdkprovider/service/project/project_user.go
Labels: no changelog

#2055 chore(release): v4.35.0
  CHANGELOG.md
Labels: release

#2056 docs: remove references to account IDs
  docs/data-sources/billing_group.md
  docs/data-sources/organization_project.md
  docs/data-sources/project.md
  docs/resources/billing_group.md
  docs/resources/organization_project.md
  docs/resources/project.md
  internal/sdkprovider/service/project/billing_group.go
  internal/sdkprovider/service/project/organization_project.go
  internal/sdkprovider/service/project/project.go
Labels: documentation, no changelog

#2002 feat(organization_vpc): added organization_vpc resource
  Makefile
  docs/data-sources/aws_org_vpc_peering_connection.md
  docs/data-sources/azure_org_vpc_peering_connection.md
  docs/data-sources/gcp_org_vpc_peering_connection.md
  docs/data-sources/organization_vpc.md
  docs/resources/aws_org_vpc_peering_connection.md
  docs/resources/azure_org_vpc_peering_connection.md
  docs/resources/gcp_org_vpc_peering_connection.md
  docs/resources/organization_vpc.md
  examples/resources/aiven_aws_org_vpc_peering_connection/import.sh
  examples/resources/aiven_aws_org_vpc_peering_connection/resource.tf
  examples/resources/aiven_azure_org_vpc_peering_connection/import.sh
  examples/resources/aiven_azure_org_vpc_peering_connection/resource.tf
  examples/resources/aiven_gcp_org_vpc_peering_connection/import.sh
  examples/resources/aiven_gcp_org_vpc_peering_connection/resource.tf
  examples/resources/aiven_organization_vpc/import.sh
  examples/resources/aiven_organization_vpc/resource.tf
  go.mod
  internal/acctest/acctest.go
  internal/acctest/template.go
  internal/common/client.go
  internal/schemautil/schemautil.go
  internal/sdkprovider/provider/provider.go
  internal/sdkprovider/service/project/organization_project_test.go
  internal/sdkprovider/service/vpc/aws_org_vpc_peering_connection.go
  internal/sdkprovider/service/vpc/aws_org_vpc_peering_connection_data_source.go
  internal/sdkprovider/service/vpc/aws_org_vpc_peering_connection_test.go
  internal/sdkprovider/service/vpc/aws_vpc_peering_connection.go
  internal/sdkprovider/service/vpc/azure_org_vpc_peering_connection.go
  internal/sdkprovider/service/vpc/azure_org_vpc_peering_connection_data_source.go
  internal/sdkprovider/service/vpc/azure_org_vpc_peering_connection_test.go
  internal/sdkprovider/service/vpc/azure_vpc_peering_connection.go
  internal/sdkprovider/service/vpc/gcp_org_vpc_peering_connection.go
  internal/sdkprovider/service/vpc/gcp_org_vpc_peering_connection_data_source.go
  internal/sdkprovider/service/vpc/gcp_org_vpc_peering_connection_test.go
  internal/sdkprovider/service/vpc/gcp_vpc_peering_connection.go
  internal/sdkprovider/service/vpc/org_vpc_peering_connection.go
  internal/sdkprovider/service/vpc/org_vpc_peering_connection_test.go
  internal/sdkprovider/service/vpc/organization_vpc.go
  internal/sdkprovider/service/vpc/organization_vpc_data_source.go
  internal/sdkprovider/service/vpc/organization_vpc_test.go
  internal/sdkprovider/service/vpc/sweep.go
  internal/sdkprovider/service/vpc/vpc_peering_connection.go
  internal/sdkprovider/service/vpc/vpc_peering_connection_state.go
Labels: no changelog

#2057 chore(release): v4.36.0
  CHANGELOG.md
Labels: release

#2059 fix(aiven_organization_project): fixed test
  internal/sdkprovider/service/project/organization_project_test.go
Labels: no changelog

#2058 docs: replace sales email address with contact form link
  internal/schemautil/userconfig/desc.go
Labels: documentation, no changelog

#2061 refactor(organization_project): move to organization module
  internal/sdkprovider/provider/provider.go
  internal/sdkprovider/service/organization/organization_project.go
  internal/sdkprovider/service/organization/organization_project_data_source.go
  internal/sdkprovider/service/organization/organization_project_test.go
Labels: no changelog

#2062 docs: fix example usage for billing group data source
  docs/data-sources/billing_group.md
  examples/data-sources/aiven_billing_group/data-source.tf
  internal/sdkprovider/service/project/billing_group_data_source.go
Labels: documentation, no changelog
