Repository aiven/terraform-provider-aiven, pull requests merged in 2025-04, with the labels that each got.

#2125 docs: update user list data source and related docs
  docs/data-sources/organization_application_user.md
  docs/data-sources/organization_user_list.md
  docs/resources/organization_application_user.md
  docs/resources/organization_user_group_member.md
  examples/data-sources/aiven_organization_application_user/data-source.tf
  examples/data-sources/aiven_organization_user_list/data-source.tf
  examples/get-started/README.md
  examples/get-started/get-started.tf
  examples/resources/aiven_organization_application_user/resource.tf
  examples/resources/aiven_organization_user_group_member/resource.tf
  internal/sdkprovider/service/organization/organization_application_user.go
  internal/sdkprovider/service/organization/organization_user_list_data_source.go
Labels: documentation, no changelog

#2130 docs: update kafka connect example for use in Aiven Docs
  examples/kafka_connect/kafka_connect_service.tf
  examples/kafka_connect/kafka_service.tf
  examples/kafka_connect/output.tf
  examples/kafka_connect/variables.tf
  examples_tests/kafka_connect_test.go
Labels: documentation, no changelog

#2105 docs: update migration guide and get started
  docs/guides/update-deprecated-resources.md
  docs/resources/organization_permission.md
  examples/get-started/README.md
  examples/get-started/get-started.tf
  examples/resources/aiven_organization_permission/resource.tf
  templates/guides/update-deprecated-resources.md
Labels: documentation, no changelog

#2138 fix(clickhouse_grant): import
  .semgrep.yml
  CHANGELOG.md
  internal/sdkprovider/service/clickhouse/clickhouse_grant.go
  internal/sdkprovider/service/clickhouse/clickhouse_grant_test.go
Labels: bug

#2139 fix(clickhouse_database): import
  CHANGELOG.md
  internal/sdkprovider/service/clickhouse/clickhouse_database.go
  internal/sdkprovider/service/clickhouse/clickhouse_database_test.go
Labels: bug

#2140 docs: change M3DB to Thanos
  docs/data-sources/service_integration.md
  docs/resources/service_integration.md
  examples/data-sources/aiven_service_integration/data-source.tf
  examples/resources/aiven_service_integration/resource.tf
  sample_project/outputs.tf
  sample_project/sample.tf
Labels: documentation, no changelog

#2136 chore(release): v4.38.0
  .github/workflows/acceptance-tests.yml
  CHANGELOG.md
  Makefile
  docs/data-sources/clickhouse.md
  docs/data-sources/organization_address.md
  docs/data-sources/organization_billing_group.md
  docs/data-sources/organization_billing_group_list.md
  docs/resources/clickhouse.md
  docs/resources/kafka.md
  docs/resources/organization_address.md
  docs/resources/organization_billing_group.md
  examples/postgres/service.tf
  go.mod
  go.sum
  internal/acctest/acctest.go
  internal/acctest/template/store_test.go
  internal/plugin/service/externalidentity/external_identity_data_source_test.go
  internal/plugin/service/organization/address/organization_address_data_source.go
  internal/plugin/service/organization/address/organization_address_resource.go
  internal/plugin/service/organization/address/organization_address_resource_test.go
  internal/plugin/service/organization/address/organization_address_schema.go
  internal/plugin/service/organization/billing/organization_billing_group_data_source.go
  internal/plugin/service/organization/billing/organization_billing_group_list_data_source.go
  internal/plugin/service/organization/billing/organization_billing_group_resource.go
  internal/plugin/service/organization/billing/organization_billing_group_resource_test.go
  internal/plugin/service/organization/billing/organization_billing_group_schema.go
  internal/plugin/service/organization/organization_user_group_member_test.go
  internal/sdkprovider/userconfig/service/clickhouse.go
  internal/sdkprovider/userconfig/service/kafka.go
  internal/sweep/sweep_test.go
Labels: release

#2142 docs: add Thanos examples
  examples/kafka_pg_grafana/README.md
  examples/kafka_pg_grafana/integrations.tf
  examples/kafka_pg_grafana/provider.tf
  examples/kafka_pg_grafana/services.tf
  examples/kafka_pg_grafana/variables.tf
  examples/m3/project.tf
  examples/m3/services_and_integrations.tf
  examples/thanos/provider.tf
  examples/thanos/service.tf
  examples/thanos/variables.tf
  examples/thanos_pg/README.md
  examples/thanos_pg/grafana.tf
  examples/thanos_pg/metrics.tf
  examples/thanos_pg/pg_integration.tf
  examples/thanos_pg/project.tf
  examples/thanos_pg/provider.tf
  examples/thanos_pg/variables.tf
Labels: documentation, no changelog

#2143 docs: add alloydb example for getting started
  examples/alloydbomni/output.tf
  examples/alloydbomni/provider.tf
  examples/alloydbomni/service.tf
  examples/alloydbomni/variables.tf
Labels: documentation, no changelog

#2154 docs: update Aiven description with brand guidelines
  docs/index.md
  templates/index.md
Labels: documentation, no changelog

#2146 docs: update opensearch documentation
  docs/data-sources/opensearch.md
  docs/data-sources/opensearch_acl_config.md
  docs/data-sources/opensearch_acl_rule.md
  docs/data-sources/opensearch_security_plugin_config.md
  docs/data-sources/opensearch_user.md
  docs/resources/opensearch.md
  docs/resources/opensearch_acl_config.md
  docs/resources/opensearch_acl_rule.md
  docs/resources/opensearch_security_plugin_config.md
  docs/resources/opensearch_user.md
  examples/data-sources/aiven_opensearch/data-source.tf
  examples/data-sources/aiven_opensearch_acl_config/data-source.tf
  examples/data-sources/aiven_opensearch_acl_rule/data-source.tf
  examples/data-sources/aiven_opensearch_security_plugin_config/data-source.tf
  examples/data-sources/aiven_opensearch_user/data-source.tf
  examples/resources/aiven_opensearch/import.sh
  examples/resources/aiven_opensearch/resource.tf
  examples/resources/aiven_opensearch_acl_config/import.sh
  examples/resources/aiven_opensearch_acl_config/resource.tf
  examples/resources/aiven_opensearch_acl_rule/resource.tf
  examples/resources/aiven_opensearch_security_plugin_config/import.sh
  examples/resources/aiven_opensearch_security_plugin_config/resource.tf
  examples/resources/aiven_opensearch_user/import.sh
  examples/resources/aiven_opensearch_user/resource.tf
  internal/schemautil/userconfig/stateupgrader/v0/opensearch/opensearch.go
  internal/sdkprovider/service/opensearch/opensearch.go
  internal/sdkprovider/service/opensearch/opensearch_acl_config.go
  internal/sdkprovider/service/opensearch/opensearch_acl_config_data_source.go
  internal/sdkprovider/service/opensearch/opensearch_acl_rule.go
  internal/sdkprovider/service/opensearch/opensearch_acl_rule_data_source.go
  internal/sdkprovider/service/opensearch/opensearch_data_source.go
  internal/sdkprovider/service/opensearch/opensearch_security_plugin_config.go
  internal/sdkprovider/service/opensearch/opensearch_security_plugin_config_data_source.go
  internal/sdkprovider/service/opensearch/opensearch_user.go
  internal/sdkprovider/service/opensearch/opensearch_user_data_source.go
Labels: documentation, no changelog

#2158 docs: refine autoscaler docs
  docs/guides/disk-autoscaler.md
  docs/resources/service_integration.md
  templates/guides/disk-autoscaler.md
  templates/resources/service_integration.md.tmpl
Labels: documentation, no changelog

#2165 fix: sort userconfig enum values
  docs/resources/alloydbomni.md
  internal/sdkprovider/userconfig/service/alloydbomni.go
  ucgenerator/models.go
Labels: no changelog

#2156 refactor(organization_address): generate resource files
  docs/data-sources/organization_address.md
  docs/resources/organization_address.md
  internal/acctest/template/store.go
  internal/plugin/adapter/common.go
  internal/plugin/adapter/datasource.go
  internal/plugin/adapter/resource.go
  internal/plugin/provider.go
  internal/plugin/service/organization/address/organization_address_data_source.go
  internal/plugin/service/organization/address/organization_address_data_source_test.go
  internal/plugin/service/organization/address/organization_address_resource.go
  internal/plugin/service/organization/address/organization_address_schema.go
  internal/plugin/service/organizationaddress/organization_address.go
  internal/plugin/service/organizationaddress/organization_address_test.go
  internal/plugin/service/organizationaddress/zz_converters.go
  internal/plugin/service/organizationaddress/zz_datasource.go
  internal/plugin/service/organizationaddress/zz_resource.go
  internal/plugin/util/converters.go
  internal/server/server.go
Labels: no changelog

#2167 refactor: convertors must return diags
  internal/plugin/service/organizationaddress/zz_converters.go
  internal/plugin/util/converters.go
  internal/schemautil/userconfig/desc.go
Labels: no changelog

#2168 feat: support required+nullable fields
  internal/plugin/service/organizationaddress/zz_converters.go
  internal/plugin/util/converters.go
Labels: no changelog

#2172 fix(sweep): added sweepers for aiven_governance_access
  go.mod
  go.sum
  internal/sdkprovider/service/governance/sweep.go
  internal/sweep/sweep_test.go
  mocks/client.go
Labels: no changelog

#2174 refactor(organization_address): use structs instead of maps
  internal/plugin/provider.go
  internal/plugin/service/organization/address/address.go
  internal/plugin/service/organization/address/address_test.go
  internal/plugin/service/organization/address/zz_converters.go
  internal/plugin/service/organization/address/zz_datasource.go
  internal/plugin/service/organization/address/zz_resource.go
  internal/plugin/service/organizationaddress/zz_converters.go
  internal/plugin/service/organizationaddress/zz_datasource.go
  internal/plugin/service/organizationaddress/zz_resource.go
  internal/plugin/util/converters.go
Labels: no changelog

#2179 docs: add example and update governance access docs
  docs/resources/governance_access.md
  examples/resources/aiven_governance_access/resource.tf
  internal/sdkprovider/service/governance/governance_access.go
Labels: documentation, no changelog

#2183 refactor(organization): generate resource
  CHANGELOG.md
  docs/data-sources/organization.md
  docs/resources/organization.md
  internal/acctest/template/store_test.go
  internal/plugin/adapter/common.go
  internal/plugin/adapter/datasource.go
  internal/plugin/adapter/resource.go
  internal/plugin/provider.go
  internal/plugin/service/organization/org/organization_data_source.go
  internal/plugin/service/organization/org/organization_data_source_test.go
  internal/plugin/service/organization/org/organization_resource.go
  internal/plugin/service/organization/org/organization_schema.go
  internal/plugin/service/organization/organization/organization.go
  internal/plugin/service/organization/organization/organization_test.go
  internal/plugin/service/organization/organization/zz_converters.go
  internal/plugin/service/organization/organization/zz_datasource.go
  internal/plugin/service/organization/organization/zz_resource.go
Labels: no changelog

#2186 fix: set id fields values to update generated resources
  internal/plugin/service/organization/address/address.go
  internal/plugin/service/organization/address/zz_converters.go
  internal/plugin/service/organization/billinggroup/billing_group.go
  internal/plugin/service/organization/billinggroup/zz_converters.go
  internal/plugin/service/organization/billinggrouplist/zz_converters.go
  internal/plugin/service/organization/organization/organization.go
  internal/plugin/service/organization/organization/zz_converters.go
Labels: no changelog

#2187 refactor: generate timeout blocks
  docs/data-sources/organization_address.md
  docs/data-sources/organization_billing_group.md
  docs/data-sources/organization_billing_group_list.md
  docs/resources/organization_address.md
  docs/resources/organization_billing_group.md
  internal/plugin/service/organization/address/zz_datasource.go
  internal/plugin/service/organization/address/zz_resource.go
  internal/plugin/service/organization/billinggroup/zz_datasource.go
  internal/plugin/service/organization/billinggroup/zz_resource.go
  internal/plugin/service/organization/billinggrouplist/zz_datasource.go
Labels: no changelog

#2189 refactor: restructure the organization package
  internal/plugin/provider.go
  internal/plugin/service/organization/project/organization_group_project.go
  internal/plugin/service/organization/project/organization_group_project_test.go
  internal/plugin/service/organization/usergroup/organization_user_group_member.go
  internal/plugin/service/organization/usergroup/organization_user_group_member_test.go
Labels: no changelog
