Repository aiven/terraform-provider-aiven, pull requests merged in 2025-03, with the labels that each got.

#2070 fix(organization_project): added sweeper
  .github/workflows/examples-tests.yml
  docs/resources/kafka.md
  examples/kafka_connectors/mongo_sink/services.tf
  examples/kafka_connectors/os_sink/services.tf
  examples/kafka_mirrormaker/kafka.tf
  examples/kafka_mirrormaker_bidirectional/kafka.tf
  examples/kafka_mirrormaker_global/kafka.tf
  examples/kafka_prometheus/services.tf
  examples/kafka_schemas/kafka_service.tf
  examples/resources/aiven_kafka/resource.tf
  internal/sdkprovider/service/account/sweep.go
  internal/sdkprovider/service/organization/sweep.go
Labels: no changelog

#2075 chore: remove dead code
  internal/plugin/errmsg/errmsg.go
  internal/plugin/util/diag.go
  internal/plugin/util/helpers.go
  internal/schemautil/userconfig/desc.go
Labels: no changelog

#2027 chore(testing): added TF templates for tests
  go.mod
  internal/acctest/template.go
  internal/acctest/template/builder.go
  internal/acctest/template/builder_test.go
  internal/acctest/template/error.go
  internal/acctest/template/external.go
  internal/acctest/template/functions.go
  internal/acctest/template/generator.go
  internal/acctest/template/generator_test.go
  internal/acctest/template/registry.go
  internal/acctest/template/registry_test.go
  internal/acctest/template/store.go
  internal/acctest/template/store_test.go
  internal/acctest/template/template.go
  internal/acctest/template/template_test.go
  internal/acctest/template/usage_example_test.go
  internal/acctest/template_test.go
  internal/sdkprovider/service/kafka/kafka_quota_test.go
  internal/sdkprovider/service/organization/organization_project_test.go
  internal/sdkprovider/service/vpc/aws_org_vpc_peering_connection_test.go
  internal/sdkprovider/service/vpc/azure_org_vpc_peering_connection_test.go
  internal/sdkprovider/service/vpc/gcp_org_vpc_peering_connection_test.go
  internal/sdkprovider/service/vpc/org_vpc_peering_connection_test.go
  internal/sdkprovider/service/vpc/organization_vpc_test.go
Labels: no changelog

#2081 chore(redis): skip redis tests
  internal/sdkprovider/service/redis/redis_test.go
  internal/sdkprovider/service/redis/redis_user_test.go
Labels: no changelog

#2082 docs: add warning to project user and group project resources
  docs/data-sources/project_user.md
  docs/resources/organization_group_project.md
  docs/resources/organization_permission.md
  docs/resources/project_user.md
  internal/plugin/service/organization/organization_group_project.go
  internal/sdkprovider/service/organization/organization_permission.go
  internal/sdkprovider/service/project/project_user.go
Labels: documentation, no changelog

#2078 docs: update application user docs
  docs/data-sources/organization_application_user.md
  docs/resources/organization_application_user.md
  internal/sdkprovider/service/organization/organization_application_user.go
Labels: documentation, no changelog

#2076 docs: update cloud_name description and link to docs
  docs/data-sources/alloydbomni.md
  docs/data-sources/cassandra.md
  docs/data-sources/clickhouse.md
  docs/data-sources/dragonfly.md
  docs/data-sources/flink.md
  docs/data-sources/grafana.md
  docs/data-sources/kafka.md
  docs/data-sources/kafka_connect.md
  docs/data-sources/kafka_mirrormaker.md
  docs/data-sources/m3aggregator.md
  docs/data-sources/m3db.md
  docs/data-sources/mysql.md
  docs/data-sources/opensearch.md
  docs/data-sources/pg.md
  docs/data-sources/redis.md
  docs/data-sources/thanos.md
  docs/data-sources/valkey.md
  docs/resources/alloydbomni.md
  docs/resources/cassandra.md
  docs/resources/clickhouse.md
  docs/resources/dragonfly.md
  docs/resources/flink.md
  docs/resources/grafana.md
  docs/resources/kafka.md
  docs/resources/kafka_connect.md
  docs/resources/kafka_mirrormaker.md
  docs/resources/m3aggregator.md
  docs/resources/m3db.md
  docs/resources/mysql.md
  docs/resources/opensearch.md
  docs/resources/pg.md
  docs/resources/redis.md
  docs/resources/thanos.md
  docs/resources/valkey.md
  internal/schemautil/service.go
Labels: documentation, no changelog

#2089 fix: set ForceNew fields, that are not in the DTO
  CHANGELOG.md
  internal/acctest/template/store_test.go
  internal/schemautil/schemautil.go
  internal/schemautil/schemautil_test.go
  internal/sdkprovider/service/account/account.go
  internal/sdkprovider/service/account/account_team.go
  internal/sdkprovider/service/account/account_team_member.go
  internal/sdkprovider/service/alloydbomni/alloydbomni_database.go
  internal/sdkprovider/service/flink/flink_jar_application.go
  internal/sdkprovider/service/flink/flink_jar_application_deployment.go
  internal/sdkprovider/service/flink/flink_jar_application_version.go
  internal/sdkprovider/service/kafka/kafka_native_acl.go
  internal/sdkprovider/service/kafka/kafka_quota.go
  internal/sdkprovider/service/kafka/mirrormaker_replication_flow.go
  internal/sdkprovider/service/organization/organization_application_user.go
  internal/sdkprovider/service/organization/organization_application_user_token.go
  internal/sdkprovider/service/organization/organization_user_group.go
  internal/sdkprovider/service/organization/organization_user_list_data_source.go
  internal/sdkprovider/service/organization/organizational_unit.go
  internal/sdkprovider/service/pg/pg_user.go
  internal/sdkprovider/service/pg/pg_user_retries_test.go
  internal/sdkprovider/service/pg/pg_user_test.go
Labels: bug

#2095 docs: add instructions on assigning permissions to multiple principals
  docs/resources/organization_permission.md
  internal/sdkprovider/service/organization/organization_permission.go
Labels: documentation, no changelog

#2091 docs: update deprecation guide
  docs/guides/update-deprecated-resources.md
  templates/guides/update-deprecated-resources.md
Labels: documentation, no changelog

#2088 feat: add Plugin Framework resource and datasource support for test template rendering package
  internal/acctest/template/builder.go
  internal/acctest/template/error.go
  internal/acctest/template/field_extractor.go
  internal/acctest/template/field_extractor_test.go
  internal/acctest/template/functions.go
  internal/acctest/template/generator.go
  internal/acctest/template/generator_framework.go
  internal/acctest/template/generator_framework_test.go
  internal/acctest/template/generator_sdk.go
  internal/acctest/template/generator_sdk_test.go
  internal/acctest/template/generator_test.go
  internal/acctest/template/store.go
  internal/acctest/template/store_test.go
  internal/acctest/template/template.go
  internal/acctest/template/template_test.go
Labels: no changelog

#2099 chore(release): v4.37.0
  CHANGELOG.md
Labels: release

#2101 chore(ci): added retries to the acceptance tests on CI
  .github/workflows/acceptance-tests.yml
  scripts/retry_test.sh
Labels: no changelog

#2114 docs: add note that service state cannot be changed with TF
  docs/data-sources/alloydbomni.md
  docs/data-sources/cassandra.md
  docs/data-sources/clickhouse.md
  docs/data-sources/dragonfly.md
  docs/data-sources/flink.md
  docs/data-sources/grafana.md
  docs/data-sources/kafka.md
  docs/data-sources/kafka_connect.md
  docs/data-sources/kafka_mirrormaker.md
  docs/data-sources/m3aggregator.md
  docs/data-sources/m3db.md
  docs/data-sources/mysql.md
  docs/data-sources/opensearch.md
  docs/data-sources/pg.md
  docs/data-sources/redis.md
  docs/data-sources/thanos.md
  docs/data-sources/valkey.md
  docs/resources/alloydbomni.md
  docs/resources/cassandra.md
  docs/resources/clickhouse.md
  docs/resources/dragonfly.md
  docs/resources/flink.md
  docs/resources/grafana.md
  docs/resources/kafka.md
  docs/resources/kafka_connect.md
  docs/resources/kafka_mirrormaker.md
  docs/resources/m3aggregator.md
  docs/resources/m3db.md
  docs/resources/mysql.md
  docs/resources/opensearch.md
  docs/resources/pg.md
  docs/resources/redis.md
  docs/resources/thanos.md
  docs/resources/valkey.md
  internal/schemautil/service.go
Labels: documentation, no changelog

#2110 fix(ci): fix acceptance tests
  .github/workflows/acceptance-tests.yml
  scripts/retry_test.sh
Labels: no changelog

#2109 docs: add guide and example for autoscaler
  docs/data-sources/alloydbomni.md
  docs/data-sources/cassandra.md
  docs/data-sources/clickhouse.md
  docs/data-sources/dragonfly.md
  docs/data-sources/flink.md
  docs/data-sources/grafana.md
  docs/data-sources/kafka.md
  docs/data-sources/kafka_connect.md
  docs/data-sources/kafka_mirrormaker.md
  docs/data-sources/m3aggregator.md
  docs/data-sources/m3db.md
  docs/data-sources/mysql.md
  docs/data-sources/opensearch.md
  docs/data-sources/pg.md
  docs/data-sources/redis.md
  docs/data-sources/thanos.md
  docs/data-sources/valkey.md
  docs/guides/disk-autoscaler.md
  docs/resources/alloydbomni.md
  docs/resources/cassandra.md
  docs/resources/clickhouse.md
  docs/resources/dragonfly.md
  docs/resources/flink.md
  docs/resources/grafana.md
  docs/resources/kafka.md
  docs/resources/kafka_connect.md
  docs/resources/kafka_mirrormaker.md
  docs/resources/m3aggregator.md
  docs/resources/m3db.md
  docs/resources/mysql.md
  docs/resources/opensearch.md
  docs/resources/pg.md
  docs/resources/redis.md
  docs/resources/thanos.md
  docs/resources/valkey.md
  examples/autoscaler_integration/README.md
  examples/autoscaler_integration/autoscaler.tf
  examples/autoscaler_integration/provider.tf
  examples/autoscaler_integration/service.tf
  examples/autoscaler_integration/variables.tf
  internal/schemautil/service.go
  templates/guides/disk-autoscaler.md
Labels: documentation, no changelog
